### ISSUE TITLE
Installation pauses due to missing/deleted plugin git repo

### ISSUE THREAD

**Issue by FazleArefin** [spf13/spf13-vim#1014]
When trying to install **spf13-vim** using ` sh <(curl https://j.mp/spf13-vim3 -L)`, the installation pauses:

```
Processing 'amirh/HTML-AutoCloseTag'Username for 'https://github.com':
Password for 'https://github.com':
```

It seems it is because of this missing repository [HTML-AutoCloseTag](https://github.com/amirh/HTML-AutoCloseTag) which have been deleted or made private.

Can this plugin **HTML-AutoCloseTag** be removed from the spf13-vim?

**Comment by alex-shamshurin** [comment]
We can use UnBundle to skip it athen install back somehow

**Comment by FazleArefin** [comment]
Yes, that's what I am doing. But people who are new to spf13 would have no clue.

**Comment by alex-shamshurin** [comment]
Here is not merged PR to fix this issue https://github.com/spf13/spf13-vim/pull/1004. BTW, I do not see any activity on any author's projects this year. We need somewhow rebase to new maintained fork

**Comment by rosatolen** [comment]
I believe there is a version on vim-scripts here: https://github.com/vim-scripts/HTML-AutoCloseTag. Do you need a PR for this issue? It looks like a one line change on 247 of the .vimrc.bundles.

**Comment by GottZ** [comment]
i just installed spf13 on a new machine and noticed this issue still exists a year after my last installation. wtf.

**Comment by FazleArefin** [comment]
> i just installed spf13 on a new machine and noticed this issue still exists a year after my last installation. wtf.

This `spf13-vim` git repo is no longer maintained **Latest commit 1ce5f23  on 14 Feb 2016** 

Have a look at Janus Vim distribution which I am now using  https://github.com/carlhuda/janus
