### ISSUE TITLE
how can i only override 'general' group bundles?

### ISSUE THREAD

**Issue by dfang** [spf13/spf13-vim#102]
to be specific , how can i disable or replace just one plugin  ?

**Comment by spf13** [comment]
You need to remove the section and then add them all but that one. Unfortunately there's not a better way right now. Just curious, which plugin don't you want? 

## 

Steve Francia
@spf13

**Comment by dfang** [comment]
i don't want ctrlp , i can't tweak it like "go to anything" like sublime text 2 , eg: locate app/controllers/application_controller.rb by "app con rb" .

and please help me ?  i've spent many hours , but ......

how to not change CWD when invoke :e ~/.vimrc.local . and click on file node

and i want CWD to be always fixed with current project root(i'm a rails developer , new to vim ) .

and ctrl+s to save current file does not work 

and colorscheme ir_black does not work , but when vim loaded :colorschem ir_black works.

.vimrc untouched

### Below is my .vimrc.local file

"my spf13 customization

colorscheme ir_black

"map F4 to Toggle NERDTree
map <F4> :NERDTreeToggle<CR>:NERDTreeMirror<CR>

"set NERDTree to open node with single click
let NERDTreeMouseMode=3

"let NERDTreeChDirMode=1

"ctrl+s to save current file in insert mode
imap <c-s> <Esc>:w<CR>

### Below is my .vimrc.bunlde.local

"my spf13 bundle customization

" don't load  php and python group
let g:spf13_bundle_groups=['general', 'programming', 'ruby', 'javascript', 'html', 'misc']

thanks!

**Comment by spf13** [comment]
Introduced UnBundle method which let's you remove just a single bundle.

**Comment by dfang** [comment]
@spf13 thanks
