### ISSUE TITLE
C syntax highlighting breaks under specific circumstances on macOS

### ISSUE THREAD

**Issue by mtn** [spf13/spf13-vim#1027]
OS: macOS Sierra v10.12.3
Vim: v8.0.311

For some reason, syntax highlighting seems to have stopped working for me for files titled "main.c" despite working normally for all other files. As far as I can tell, the problem has nothing to do with the files themselves because if I rename the file, syntax highlighting returns. It was working without issue previously.

I scanned previous issues and in accordance with #690 I tried `syn sync fromstart`, but I observed no change. I've also restarted terminal, vim, etc. Anything else that might be worth trying?

**Comment by mtn** [comment]
This was actually fixed by `set syntax=c`. Seems strange considering the name of the file was somehow impacting the language being recognized, but it's fixed now :star2:

**Comment by ploverpang** [comment]
@mtn `set syntax=c` can enable highlight, but some plugins like YouCompleteMe and tagbar still **can't** used. Do you know how to fix it?

**Comment by ploverpang** [comment]
@mtn delete files in ~/.vimview can solve highlight and plugin problem
