### ISSUE TITLE
gvim startup error on Windows install

### ISSUE THREAD

**Issue by alnjxn** [spf13/spf13-vim#103]
I am getting this error on launching gvim after installing on Windiws

E117: Unknown function: fugitive#statusline
E15: Invalid expression: fugitive#statusline()

used the .cmd script to install. everything appears to install fine.

**Comment by jphustman** [comment]
try to run <code>vim +BundleInstall! +BundleClean +q +q</code> from your command line

**Comment by alnjxn** [comment]
Worked perfectly. Much appreciated and excellent work. Thanks.
