### ISSUE TITLE
Gets real slow after 10 min and when opens a big files

### ISSUE THREAD

**Issue by Mofiqul** [spf13/spf13-vim#1036]
Hi my vim  gets real slow after like 10 mins when i type it takes more than a sec to show my input. And it is very slow while navigating on big file with 1000 lines.
Here is vimrc.local
```
 set t_Co=256
set laststatus=2
let base16colorspace=256
let g:onedark_termcolors=256
let g:airline_powerline_fonts = 1
colorscheme onedark
" Enable the list of buffers
let g:airline#extensions#tabline#enabled = 1
" Show just the filename
set re=1

let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline_theme='onedark'
let g:onedark_use_term_italics = 1
:set list
:set listchars=eol:¬,tab:>·,trail:.,extends:>,precedes:<,
"let g:LatexBox_loaded_matchparen=1
"let loaded_matchparen = 1
let g:indent_guides_enable_on_vim_startup = 0
"let g:indent_guides_auto_colors = 0

"autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=red   ctermbg=0
"autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=0
"let g:ctrlp_map = '<c-p>'
"
```

**Comment by cabrinha** [comment]
Same thing here. Whenever I have files over 100 lines, navigating and highlighting becomes very slow. What's the biggest bottleneck?

After browsing some more "slow" issues, I found: https://github.com/spf13/spf13-vim/pull/887

Disabling `set cursorline` sped navigation back up.

Additionally, keeping the cursorline on, but also adding:
```
set cursorline
set lazyredraw
set ttyfast
set ttyscroll=3
set synmaxcol=128
```

Sped things up as well.

**Comment by petroslamb** [comment]
Same here. I got `vim-gnome` installed on `ubuntu gnome 16.04` to have vim compiled with `lua` and everything. Since then `sfp13` has made it impossible to open SQL dumps or compare them with `vimdiff`.
