### ISSUE TITLE
Too many python plugins

### ISSUE THREAD

**Issue by cutelittleturtle** [spf13/spf13-vim#1066]
I am using pymode with spf13-vim on Ubuntu. Editing python file becomes very slow at the end of my file. My file is only 100 lines long.

I've already have some fixes but nothing improves.
```
let g:pymode_rope=0
let g:pymode_folding = 0
```

The problem goes away after disable pymode. 

However, I am just curious if this is a problem with pymode only, or because I have `pymode`, `pythoncomplete`, `python_match.vim` and `neocomplete` all installed and there is some conflict. My spf3 configuration is directly installed from the repository and nothing is changed. 

Also, is `neocomplete` and `pymode` both have autocomplete ability? 

Thanks.

DEBUG INFO:
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
  490   0.460037   0.004421  pymode#folding#expr()
  490   0.455616   0.082314  pymode#folding#foldcase()
  976   0.334820             <SNR>170_BlockStart()
    1   0.123462   0.000023  neosnippet#init#_initialize()
    1   0.117568   0.000335  <SNR>221_initialize_cache()
    2   0.111210   0.001403  neosnippet#commands#_make_cache()
    4   0.097762   0.000381  neosnippet#parser#_parse_snippets()
    4   0.085293   0.053412  <SNR>235_parse()
  488   0.038482             <SNR>170_BlockEnd()
    7   0.038172   0.000618  airline#check_mode()
    2   0.036936   0.004409  airline#highlighter#highlight()
    2   0.033398   0.000121  <SNR>217_complete_delay()
    2   0.033277   0.000485  <SNR>217_do_auto_complete()
    1   0.031207   0.000072  neocomplete#complete#_get_results()
    1   0.030995   0.000804  neocomplete#complete#_set_results_pos()
    1   0.028204   0.000152  pymode#indent#get_indent()
    2   0.028028             <SNR>220_SearchParensPair()
    7   0.027557   0.000409  neocomplete#helper#call_hook()
    3   0.026949   0.018594  <SNR>203_make_cache_current_buffer()
  122   0.026523   0.008157  airline#highlighter#exec()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
  976              0.334820  <SNR>170_BlockStart()
  490   0.455616   0.082314  pymode#folding#foldcase()
    4   0.085293   0.053412  <SNR>235_parse()
  488              0.038482  <SNR>170_BlockEnd()
    2              0.028028  <SNR>220_SearchParensPair()
    3   0.026949   0.018594  <SNR>203_make_cache_current_buffer()
  127   0.015946   0.015430  neosnippet#parser#_initialize_snippet()
  340              0.008774  <SNR>163_get_syn()
    4   0.008912   0.008694  <SNR>227_writefile()
  122   0.026523   0.008157  airline#highlighter#exec()
    4              0.007829  <SNR>214_uniq_by()
  170   0.018002   0.007809  airline#highlighter#get_highlight()
    4   0.011304   0.007167  <SNR>198__import()
  127   0.007730   0.007162  <SNR>235_parse_snippet_name()
    5   0.006219   0.006061  <SNR>176_GetNearbyTag()
  490   0.460037   0.004421  pymode#folding#expr()
    2   0.036936   0.004409  airline#highlighter#highlight()
  127   0.020069   0.004123  <SNR>235_set_snippet_dict()
   66              0.004082  <SNR>235_add_snippet_attribute()
    2              0.003479  neosnippet#variables#runtime_dir()
```

**Comment by ghost** [comment]
I have similar problem, and I installed youcompleteme, but nothing change, still slow.

**Comment by LitLeo** [comment]
This problem is caused by the Syntastic plugin. Because Syntastic is not asynchronous. Just disable Syntastic.

**Comment by ghost** [comment]
@LitLeo It didn't work, i add UnBundle 'scrooloose/syntastic' in .vimrc.bundles.local, and reinstall plugin

**Comment by ghost** [comment]
??? why closed

**Comment by ghost** [comment]
" remove "php haskell scala python" plugs
UnBundle 'spf13/PIV'
UnBundle 'arnaud-lb/vim-php-namespace'
UnBundle 'beyondwords/vim-twig'
UnBundle 'klen/python-mode'
UnBundle 'yssource/python.vim'
UnBundle 'python_match.vim'
UnBundle 'pythoncomplete'
UnBundle 'derekwyatt/vim-scala'
UnBundle 'derekwyatt/vim-sbt'
UnBundle 'xptemplate'
UnBundle 'travitch/hasksyn'
UnBundle 'dag/vim2hs'
UnBundle 'Twinside/vim-haskellConceal'
UnBundle 'Twinside/vim-haskellFold'
UnBundle 'lukerandall/haskellmode-vim'
UnBundle 'eagletmt/neco-ghc'
UnBundle 'eagletmt/ghcmod-vim'
UnBundle 'Shougo/vimproc.vim'
UnBundle 'adinapoli/cumino'
UnBundle 'bitc/vim-hdevtools'
