### ISSUE TITLE
Unreadable default color scheme in non-gui vim

### ISSUE THREAD

**Issue by jejansse** [spf13/spf13-vim#107]
Hey,

For some reason the default color scheme in command-line vim is quite unreadable on Mac OS X and Ubuntu: ![example](https://img.skitch.com/20120816-musi6wt7e2aepjrp2w5xtj24f7.jpg).
Is this the way it should look with the default color scheme or is there something wrong in my or spf13-vim's configuration? This happens with a vanilla install of spf13-vim on different machines, both Mac OS X as well as Ubuntu. When I run spf13-vim in screen, however, the colors look much nicer.

**Comment by papoanaya** [comment]
Yes, I had the same problem when I installed it in MacOSX.  I added the following in my .vimrc.local on my Mac. 

`colorscheme peaksea`

It works well.

**Comment by jejansse** [comment]
I managed to fix it. According to the instructions on https://github.com/altercation/vim-colors-solarized/ the `let g:solarized_termcolors=256` in `.vimrc` should come before the `colorscheme solarized` line. In the `.vimrc` of spf13-vim, however, it comes afterwards. I've moved that line before the colorscheme line and this does indeed work. I opened a pull request for the fix.
