### ISSUE TITLE
Tab to auto-complete with neocomplcache not working

### ISSUE THREAD

**Issue by jejansse** [spf13/spf13-vim#108]
Hey,

After a vanilla install of spf13-vim the tab-key does not seem to work with auto-complete. Even though it is set to behave the same as Ctrl-n, whenever I type tab to complete either nothing happens or a tab is inserted. The problem seems to be that snipmate is overriding the settings for tab, as can also be seen from `:map`, where tab is bound to a snipmate function. The strange thing is that even when I try to override the tab-completion in `.vimrc.local`, snipmate seems to be able to override it. When I override the tab behaviour in the vim command line after vim started up, I get the expected behaviour. I also am able to get the same behaviour when I remove snipmate.

Is there a way to make snipmate play nice with neocomplcache in spf13-vim? For example by letting snipmate use ctrl+k and disabling the snippets part of neocomplcache?

**Comment by bronzehedwick** [comment]
I have the same issue with tab complete.

**Comment by spf13** [comment]
I'm considering removing snipmate from the distro entirely and just going with neocomplcache. I'll do some more testing on this.  

Best,
Steve

http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by jejansse** [comment]
A temporary workaround while snipmate is still in the distro is to add the following in your `.vimrc.local`:

```
au BufEnter * inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "<TAB>"
au BufEnter * inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "<TAB>"
```

The second line is optional and only needed if you want shift-enter to go back in the completion list.

**Comment by jdewit** [comment]
I like neocomplcaches snippet completion much better than snipmate. 

With snipmate removed theres no more conflict when completing snippets. 

+1 for removing snipmate

**Comment by spf13** [comment]
This should be resolved now. You can no longer install snipmate alongside neocomplcache.

**Comment by kc-dot-io** [comment]
When I hit tab to complete it just goes to the next item in the dropdown. If I hit enter on one of the options it doesn't complete and drops to the next line. Any idea what I'm doing wrong?

**Comment by spf13** [comment]
It's in the readme under the neocomplcache section
https://github.com/spf13/spf13-vim#neocomplcache

<C-k> for completing snippets.

Does that answer your question?

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by huypn12** [comment]
Does spf-13 supports popup on <Tab> feature of neocomplcache?
I feel uncomfortable with auto popup, so I disabled it. 
I added those code into .vimrc.local but it doesn't work

<code>
let g:neocomplcache_disable_auto_complete = 1

inoremap <expr><TAB> pumvisible() ? "<C-n>" : <SID>check_back_space() ? "<TAB>" : "<C-x><C-u>"
        function! s:check_back_space()"{{{
        let col = col('.') - 1
        return !col || getline('.')[col - 1] =~ '\s'
        endfunction"}}

</code>
