### ISSUE TITLE
can't auto enable "relativenumber" when open a C file

### ISSUE THREAD

**Issue by allanlibra** [spf13/spf13-vim#1082]
I add a command 
` set relativenumber `
at the tail of .vimrc
it works, except in C file.
is some  plugin  may affect this ?
My environment is:
VIM 7.4, Ubuntu 16.04
I'm not very familiar with VIM, and I only changed .vimrc as above.
thanks for any help

**Comment by wsdjeg** [comment]
you can use an autocmd, of cause it should be surounded by augroup, for example:

```viml
augroup my_vimrc
  autocmd!
  autocmd FileType c setlocal relativenumber
augroup END
```

**Comment by allanlibra** [comment]
Finally I follow the README and add 
    
    set relativenumber
    colorscheme 0x7A69_dark
    
to **~/.vimrc.local**, and it works.
And also thanks for @wsdjeg 's answer, I learned new about vim.
