### ISSUE TITLE
rbtweaks and Windows Runtime errors

### ISSUE THREAD

**Issue by tjbell** [spf13/spf13-vim#11]
There is a setting in the c.vim plugin that does not work correctly on windows with the
current .vimrc windows runtime settings. Vimfiles is hard coded to vimfiles instead of .vim.
let s:plugin_dir       = $VIM.'\vimfiles\'
Also it is nice to set let s:C_TemplateOverwrittenMsg= 'yes' to 'no' on windows.

**Comment by spf13** [comment]
merged in, thanks.
