### ISSUE TITLE
Solarized Colorscheme

### ISSUE THREAD

**Issue by 9Y5** [spf13/spf13-vim#113]
Environment: Mac OS X Mountain Lion, iTerm 2

The Solarized scheme doesn't seem to render properly.
1. Out of the box, it should load colorscheme solarized right? But it doesn't.
2. When I do set up my own .vimrc.local, and add
   
   set background=dark
   colorscheme solarized

I do get a dark solarized colorscheme, however the highlighting line (where the cursor is) AND the numbers column on the left are dark grey/brown.

Any idea how to fix this?

**Comment by tmuka** [comment]
thanks, this fixed the same issue for me in a fresh ubuntu install. without your change the colors look great in gvim, but not so hot in terminal or xterm.

**Comment by jhenahan** [comment]
I have this issue, as well. Same system, using MacVim HEAD.

**Comment by techwraith** [comment]
I'm also having this issue, any ideas @spf13?

using: OSX Mountain Lion, Retina MBP, iTerm 2.

**Comment by spf13** [comment]
I'll try to figure it iut  

## 

Steve Francia
@spf13

**Comment by nugend** [comment]
I was having a problem with the solarized color scheme on PuTTY for Windows (with Solarized settings for PuTTY enabled) and had to make a few changes to get it looking right:

Added to vimrc.local:

```
let g:solarized_termtrans=0
let g:solarized_contrast="normal"
let g:solarized_visibility="normal"
```

Removed from .vimrc:

```
let g:solarized_termcolors=256
```

**Comment by tmuka** [comment]
Thanks, DannoHung, that is better for me in putty over ssh :)

**Comment by kew-l** [comment]
It seems to ruin ls/directory coloration though.

**Comment by nugend** [comment]
@kevinwaddle Someone wrote up a Solarized specific LS COLORS that I installed alongside the PuTTY settings: [sigurdga/ls-colors-solarized](https://github.com/sigurdga/ls-colors-solarized)

**Comment by a2ndrade** [comment]
I'm having the same issue, also using OSX Mountain Lion, Retina MBP and iTerm 2.

**Comment by orsenthil** [comment]
I faced the same problem on iTerm2 on Mac.

Remove - let g:solarized_termcolors=256   from .vimrc
and adding

let g:solarized_termtrans=0
let g:solarized_contrast="normal"
let g:solarized_visibility="normal"

gave a much better experience.

**Comment by barraponto** [comment]
Weird thing is that setting `let g:solarized_termcolors=16` in .vimrc.local is not enough. I had to comment the line from .vimrc :/

**Comment by barraponto** [comment]
BTW, issue is present in Archlinux/Konsole (Solarized Dark)

**Comment by mwestphal** [comment]
Work around for the gey number background color 
Open solarized.vim, search for "LineNr", remove the line.

**Comment by BenBergman** [comment]
Just started using spf13 and had the same problem. Had to remove the 256 line from vimrc. This affected me in gnome-terminal and PuTTY with solarized terminal themes installed. Perhaps there should be a config option in spf13 to disable the 256 line.

**Comment by jondlm** [comment]
Today I found that another 256 line cropped up that I had to remove from the `.vimrc` file.  By removing the line with `set t_Co=256            " Enable 256 colors to stop the CSApprox warning and make xterm vim shine` I was able to get the colors working correctly. This worked but I started getting the aforementioned warning. I solved that by removing the `godlygeek/csapprox` bundle by editing the `.vimrc.bundles` file and commenting it out. Hope that helps someone.

**Comment by bronzehedwick** [comment]
@9Y5, now that csapprox has been removed from the repo, is this issue still happening? If not, could you close? Thanks :)

**Comment by shadowthreed** [comment]
> I was having a problem with the solarized color scheme on PuTTY for Windows (with Solarized settings for PuTTY enabled) and had to make a few changes to get it looking right:
> 
> Added to vimrc.local:
> 
> ```
> let g:solarized_termtrans=0
> let g:solarized_contrast="normal"
> let g:solarized_visibility="normal"
> ```
> Removed from .vimrc:
> 
> ```
> let g:solarized_termcolors=256
> ```

This way make the solution better, but my vim's color also NOT solarized.
Anyway, so many thanks to you! 
(By the way, my os is linuxMint 18.3 sylvia and vim version is 7.4.1689)

**Comment by pkxpp** [comment]
> , so many thanks to you!

me too

**Comment by pkxpp** [comment]
> > I was having a problem with the solarized color scheme on PuTTY for Windows (with Solarized settings for PuTTY enabled) and had to make a few changes to get it looking right:
> > Added to vimrc.local:
> > ```
> > let g:solarized_termtrans=0
> > let g:solarized_contrast="normal"
> > let g:solarized_visibility="normal"
> > ```
> > 
> > 
> > Removed from .vimrc:
> > ```
> > let g:solarized_termcolors=256
> > ```
> 
> This way make the solution better, but my vim's color also NOT solarized.
> Anyway, so many thanks to you!
> (By the way, my os is linuxMint 18.3 sylvia and vim version is 7.4.1689)

me too~ (CentOS 7 + mRemoteNG)
