### ISSUE TITLE
Auto-unindention of else fails in ruby

### ISSUE THREAD

**Issue by cocreature** [spf13/spf13-vim#114]
When I write and if construction in ruby, vim doesn't unindent when I type in else, however elsif is working. It's also working well in python, I didn't try any other language. Would be great if you could fix this or tell me what I have to add to my config.
Edit: Indention after the else however is working, so it's two times idented, one time by the if block and one time by the else block, because it doesn't unindent.

**Comment by bronzehedwick** [comment]
@Javafant, this is an old issue. Are you still experiencing the problem? If not, please close :)
