### ISSUE TITLE
Disabling } trigger

### ISSUE THREAD

**Issue by jdewit** [spf13/spf13-vim#116]
I'm experiencing an annoying behavior when trying to insert a } in a line that already contains a }. The cursor jumps to the end of line where the original } is. 

Does anyone know which plugin is doing this and how I can remap it?

ex.

``` html
<a href="">{{ url }}</a>

and then trying this

<a href="}">{{ url }}</a>

causes this
<a href="">{{ url }<cursor>}</a>
```

Thanks

**Comment by jaywilliams** [comment]
+1

**Comment by jamestomasino** [comment]
That would be extremely helpful.

**Comment by spf13** [comment]
What language are you editing when this happens?  

Best,
Steve

## 

Steve Francia
@spf13 (http://twitter.com/spf13)

**Comment by jamestomasino** [comment]
I've noticed it in JavaScript and ActionScript.

**Comment by taxilian** [comment]
The plugin that causes this is "AutoClose".  The behavior can be really nice, when you get used to it, but _only_ if you know how to get around it. 

To add a } where you are, do a ctrl-v and then type } and it will work.

**Comment by taxilian** [comment]
(Alternately you can remove the AutoClose plugin from your configuration, of course)

**Comment by alseambusher** [comment]
open .vimrc.bundles and go to line
<code>Bundle 'AutoClose'</code>
and comment it off
<code>"Bundle 'AutoClose'</code>

**Comment by spf13** [comment]
I've always hated this feature of AutoClose. I think things should work like you expect them to and this clearly doesn't. 

I've swapped out the plugin for one that does. 

a2b1b34a15d3797b47c86e9d79407bee41833ed7

If you want the old way of doing things UnBundle the new one and Bundle the 'AutoClose' one.
