### ISSUE TITLE
Files not uploaded on save, when using MacVim as external editor for Transmit or Cyberduck.

### ISSUE THREAD

**Issue by eliasgs** [spf13/spf13-vim#123]
### Editing files remote via Transmit or Cyberduck broke

After installing spf13-vim, files where no longer correctly saved to remote server. Removing `set backup` from .vimrc seems to be fixing it.

**Comment by spf13** [comment]
Certainly not disabling that as the default as most people expect backups enabled. I would just add 

```
set nobackup 
```

to your .vimrc.local file.

**Comment by eliasgs** [comment]
Thats perhaps  a better solution, but I think people expect files to save correctly (also remotely) before they expect backups (and can't they still recover from .swp file?). Well anyway thanks for the suggestion - and of course for all the nice work:)

**Comment by marcelstoer** [comment]
Doesn't work for me with Cyberduck 4.2.1. When I edit a remote file with MacVim it is being stored in 

```
/private/var/folders/sg/<some-random-folders>/<remote-path>. 
```

Alongside the edited file there's a hidden Vim .swp file. In my .vimrc.local I have

```
set nobackup
```
