### ISSUE TITLE
Something in spf13-vim seems to be changing function calls

### ISSUE THREAD

**Issue by metcalfc** [spf13/spf13-vim#124]
I've added:

```
Bundle 'bronson/vim-trailing-whitespace'
```

To my `.vimrc.bundle.local` and I've added:

```
map <leader>w :FixWhitespace<CR>
```

To my `.vimrc.local` but I get errors that `Fixwhitespace` can't be found. I can't even type `FixWhitespace` into vim without the _W_ becoming lower case. Does this ring a bell for anyone? This works fine in a stock vimrc config.

**Comment by jphustman** [comment]
There is a"cmap W w" (stupid shift key fix) in the .vimrc, put "cunmap W" in your .vimrc.local.

**Comment by metcalfc** [comment]
That was it. Surprising side effect that any capital W gets killed.
