### ISSUE TITLE
100% cpu usage

### ISSUE THREAD

**Issue by myszek123** [spf13/spf13-vim#13]
On my fork this happens quite often. Every 5-10 min load jumps to 100% for 20-40 seconds (vim is unrespossive) and than back to normal for another 10 minuts or so.
Anyone experiences that issue? I'm on vim 7.2. 

Also I have couple of addtional plugins which might be a problem but i have no idea how to find the one that causes this?

**Comment by spf13** [comment]
I discovered that the vim-fuzzyfinder plugin was giving me trouble I removed it in commit 46f78ab7faac0652b062 

I don't have this issue (or really any issues) in the current head. Please compare with that.

Other than that I would isolate things by removing some plugins (using pathogen this is easy, just delete the folders in .vim/bundle/ until you find the culprit.

**Comment by myszek123** [comment]
thanks for your reply. I'm suspecting easytags at the moment, let you know as soon as know more.

**Comment by spf13** [comment]
Just an update on this. I've been working with the author of easytags on this. If tag files are larger than a meg or so (for my source tree mines 14M) the highlight tags function will cause this to happen. I'm disabling this plugin until we/he comes up with a better solution.

**Comment by myszek123** [comment]
Thanks for the reply!
Really good to hear there might be a solution on a horizon as I'm at 11M and growing. I'm not much of a help here unless testing is needed :)
