### ISSUE TITLE
Python documentation on top with autocomplete

### ISSUE THREAD

**Issue by volpino** [spf13/spf13-vim#130]
While writing statements that use standard library modules the autocompletion shows the pydoc of the function/module on the top of the screen.
This is quite annoying because, while you're writing, popups come out on the top of the screen and move the line you're writing. It would be better to make it coming out from the bottom.

screenshot: http://i.imgur.com/yEEdt.png

**Comment by JoveYu** [comment]
> set completeopt=menu,longest

will help you

**Comment by bronzehedwick** [comment]
@volpino, did the suggestion fix the issue? If so please close. Thanks!
