### ISSUE TITLE
UndoTree noremap not working

### ISSUE THREAD

**Issue by bronzehedwick** [spf13/spf13-vim#131]
Hi,

I'm using the latest version of MacVim on OS 10.6.8. After pulling the latest changes to spf13-vim, whenever I press <c-u> to page up, the UndoTree window opens, despite the noremap line in .vimrc. I disabled all my local configurations as well, and still got the behavior. 

Is there something obvious that I'm overlooking?

Thanks!

**Comment by spf13** [comment]
None of my keyboards have a page up key. I'll need to find one to try this out. It's not intended to overwrite the page up functionality (though there are more vim like ways of paging up).

**Comment by bronzehedwick** [comment]
My apologies, I misspoke; when I said "page up" I meant pressing control U to scroll the page up half way.

**Comment by bronzehedwick** [comment]
Oops, hit the close button by accident :X

**Comment by bronzehedwick** [comment]
I am no longer having this issue.
