### ISSUE TITLE
Terminal not working after using the install script

### ISSUE THREAD

**Issue by mauserrifle** [spf13/spf13-vim#133]
I'm running Debian Wheezy and installing thru:

```
curl http://j.mp/spf13-vim3 -L -o - | sh 
```

at the end I get:

```
installing plugins using Vundle
Vim: Warning: Input is not from a terminal
```

Can't use the terminal after this. Seems stuck. CTRL-c does not work either. After closing my x-terminal I can work with vim tho, so the install seems successful.

Hitting some keys trying to exit gives:

```
maurice@maurice-pc:~$ maurice@maurice-pc:~$ maurice@maurice-pc:~$ maurice@maurice-pc:~$ bash: sdsadsa: command not found
                                    maurice@maurice-pc:~$ bash: sa: command not found
     maurice@maurice-pc:~$ bash: sada:q: command not found
                                                          maurice@maurice-pc:~$ bash: : command not found
                         maurice@maurice-pc:~$ > >
```

**Comment by jhnwsk** [comment]
Hi,

I sumbitted a pull request fixing this issue for me.
If you like you can test it by creating creating an .sh script with the following code

``` vimscript
#!/usr/bin/env sh

endpath="$HOME/.spf13-vim-3"

warn() {
    echo "$1" >&2
}

die() {
    warn "$1"
    exit 1
}

echo "thanks for installing spf13-vim\n"

# Backup existing .vim stuff
echo "backing up current vim config\n"
today=`date +%Y%m%d`
for i in $HOME/.vim $HOME/.vimrc $HOME/.gvimrc; do [ -e $i ] && mv $i $i.$today; done


echo "cloning spf13-vim\n"
git clone --recursive -b vundle-terminal-input-fix http://github.com/jhnwsk/spf13-vim.git $endpath
mkdir -p $endpath/.vim/bundle
ln -s $endpath/.vimrc $HOME/.vimrc
ln -s $endpath/.vim $HOME/.vim

echo "Installing Vundle"
git clone http://github.com/gmarik/vundle.git $HOME/.vim/bundle/vundle

echo "installing plugins using Vundle"
vim -u $endpath/.vimrc_install - +BundleInstall! +BundleClean +qall
```

and running it thru some pipe of some sort like:
`cat the-script-file-you-created.sh | sh`

It worked for me.

cheers,
John

**Comment by mauserrifle** [comment]
Hi John,

Works on my machine too :)

Closing this issue!

**Comment by spf13** [comment]
Just yank it.

Steve Francia
spf13.com
@spf13

On Jun 12, 2013, at 11:56 AM, pcleon notifications@github.com wrote:

hi, when i use the spf13 for my vim, my mac can't use command + c for copy
, please help ^_^

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/issues/133#issuecomment-19335441
.
