### ISSUE TITLE
neocomplcache auto selects the last item in the list without pressing tab, newline, or <c-k>

### ISSUE THREAD

**Issue by tmuka** [spf13/spf13-vim#135]
I just setup a fresh install of ubuntu and used followed the docs to install spf13-vim the easy way with (curl | sh). 

To test this i create a new file using vim or "gvim style.css".  "i" for insert mode, then try to type "body".  After i type the b and o the autocomplete menu pops up, and the last item on the list "box-sizing" is selected, and inserted at the cursor.  hitting space after that happens triggers another autocomplete of a list of css attributes, and auto selects "text-align:" and inserts it at the cursor.

i verified that the default .vimrc contains let g:neocomplcache_enable_auto_select = 0, but changing that doesn't seem to matter.

The same thing also happens in .php files, and i even went so far as to setup spf13-vim on my dreamhost ssh and it has the same issue.

Am i the only one with this issue?  should i be git cloning a "stable" branch or tag or something?

Thanks for any advice, spf13-vim looks like an amazing setup, i'd love to get it working!

-Tony

**Comment by mauserrifle** [comment]
Hi Tony,

Same issue here. I think there has been a update within spf or a other project it uses I assume. I have a old install on a other machine that does not have this issue. Installing now always gives this problem which makes typing almost impossible.

Update:
Problem here is gone after re install this morning(23-09-2012).

**Comment by spf13** [comment]
I have this issue too. Must be an update in neocomplcache. I haven't changed the config.  

## 

Steve Francia
@spf13

**Comment by mauserrifle** [comment]
Currently the issue is gone again. Perhaps another update? 

Btw, I see you changed from git submodules to vundle with the 3.0 release. To be honest, I think vundle will be nice if it has a feature to specify a revision like with submodules. At the moment your distro will one day be stable, another day it might be broken. Can't make a 'stable' version this way.

**Comment by tmuka** [comment]
Thanks for the replies. I can confirm it seems mostly fixed now, at least i can type normally if i want!

it seems maybe there is more going on with neocomplcache.  in my example above, now when i type bo and hit tab, the autocomplete is the first menu item, "body", but instead "border" from halfway down the list. I assume maybe tab is matching a snippet instead of completing from the neocomplcache autocomplete menu.  I can use the arrow keys down then enter to select the first item "body".  Using ctrl+k to autocomplete results in "Warning: neocomplcache snippets source was splitted! You should install snippets_complete source from "https://g
ithub.com/Shougo/neocomplcache-snippets-complete""    i'm new, so i'm still trying to learn from .vimrc which keymappings go to which plugins!

so it seems things are in flux since vundles are bleeding edge from git. makes it a little confusing for new users like me, but i'm trying to rt*m!  thanks for bearing with me, and the great work on this!

mauserrifle, it looks like "allow specify revision/version?" is on the vundle git todo list, that should help!
