### ISSUE TITLE
Pressing tab insert spaces, does not auto-complete

### ISSUE THREAD

**Issue by nddery** [spf13/spf13-vim#136]
Hey, 

I am on Mac OSX 10.7.whatever that last version is. Whenever I press tab after the auto-complete menu has appear, it inserts spaces instead of moving to the next item in the menu or inserting it.

Any idea on how to fix this ?

Thanks!

**Comment by spf13** [comment]
I believe I have resolved this with a recent commit. Please reopen if you still experience this with the latest version.
