### ISSUE TITLE
Error detected while processing function <SNR>29_VimEnterHandler..

### ISSUE THREAD

**Issue by YounesCheikh** [spf13/spf13-vim#138]
Hi ,
why i get this error when i try to edit a file with mvim ? 

".vimrc" 541L, 19621C
Error detected while processing function <SNR>29_VimEnterHandler..<SNR>29_NERDTreeMirrorOrCreateAllTabs..<SNR>29_N
ERDTreeMirrorOrCreate..<SNR>26_initNerdTreeMirror..<SNR>26_echo..Pl#Statusline:
line   18:
E684: list index out of range: 0
Press ENTER or type command to continue

**Comment by taxilian** [comment]
Try deleting the contents of ~/.vimviews

This will delete the saved state per file, but sometimes weird issues like this stick around from previous versions because of the vimviews files
