### ISSUE TITLE
Error using zen coding plugin Sparkup

### ISSUE THREAD

**Issue by nieldm** [spf13/spf13-vim#139]
Hi im having an issue using the plugin sparkup 
https://github.com/rstacruz/sparkup.git

i write an example like

```
html > head > title
```

The press Ctrl+e at insert mode (Already try modifing the keystroke for something like Ctrl+z because of the NERDTree ) and it will make the html like this:

```
<html>
    <head>
        <title></title>
    </head>
</html>
```

But instead the result its like this:

```
<html>
    <head>
        <titu></titu>
    </head>
</html>
```

its replacing few letters with an "U" the same happends with the keystroke Ctrl+N

im trying to fix this because its a really useful plugin but cant find the solution
Thank You

**Comment by spf13** [comment]
that's one of the buggiest plugins I've ever used. I eventually just gave up on it. It would be nice if it worked better. Could conflict with other plugins in the distribution, but what good is a plugin you have to use alone.  

Sorry this isn't better news, but this used to be in the distribution until it created enough issues we eventually just took it out.  

Best,
Steve

## 

Steve Francia
@spf13 (http://twitter.com/spf13)

**Comment by nieldm** [comment]
Thanks for the quick answer, well its working well in normal mode, and another trick its in insert mode add 2 extra spaces after the last character and then use the keystroke.

**Comment by spf13** [comment]
I'm closing this now, but if anyone wants to take the initiative to get this working right I'd happily include it in the core distribution.
