### ISSUE TITLE
MacVim won't start :/

### ISSUE THREAD

**Issue by danjessen** [spf13/spf13-vim#14]
When i use your bundle, i just get this error when running mvim from terminal:
"Vim: Caught deadly signal SEGV"
"Vim: Finished"
And MacVim from dock/apps folder doesnt run at all.

**Comment by spf13** [comment]
That's odd. I'm also running MacVim as my primary and I know a good number of others doing the same without issues. 

What version of MacVim?

**Comment by danjessen** [comment]
I'm running 7.3 from google code. But I've solved the issue. It's an issue with ruby and vim, so I found out that it was command-t, that wasn't compiled correctly or at least compiled with the version I'm using on my system.

So I stole a snippet from the janus git repository (janus is a vim config kinda like yours) their rake / bootstrap file compiles command-t with the correct version on install.

https://github.com/carlhuda/janus/blob/master/Rakefile
