### ISSUE TITLE
Got error when updating to the latest version 

### ISSUE THREAD

**Issue by sliver** [spf13/spf13-vim#145]
Rerun the scrip and get error

$ curl http://j.mp/spf13-vim3 -L -o - | sh

 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147  100   147    0     0    326      0 --:--:-- --:--:-- --:--:--   650
100   807  100   807    0     0    432      0  0:00:01  0:00:01 --:--:--  1002
thanks for installing spf13-vim

backing up current vim config

cloning spf13-vim

fatal: destination path '/Users/sliver/.spf13-vim-3' already exists and is not an empty directory.
ln: /Users/sliver/.vimrc: File exists
ln: /Users/sliver/.vimrc.bundles: File exists
ln: /Users/sliver/.vim/.vim: File exists
Installing Vundle
fatal: destination path '/Users/sliver/.vim/bundle/vundle' already exists and is not an empty directory.
installing plugins using Vundle
Vim: Reading from stdin...

**Comment by spf13** [comment]
I don't believe these are actual errors. I've updated the script to not keep backing up symlinks. Did the Vundle part install correctly?

I should probably update it to not output errors when things are actually fine.   

Best,
Steve

## 

Steve Francia
@spf13 (http://twitter.com/spf13)

**Comment by spf13** [comment]
Nevermind, I was able to reproduce. Looking into this now.

**Comment by spf13** [comment]
I've fixed this in the latest commit 2a0cd044f954f1d061cfb114ca28f7668c254ed6

**Comment by sliver** [comment]
Now, it works like a charm. Thanks

**Comment by orsenthil** [comment]
@spf13 - Now this happens when you clone the git-repo and try to use bootstrap.sh. Using the curl way of installation does not have this problem.

**Comment by unbalancedparentheses** [comment]
@spf13 as @orsenthil said this issue is appearing when I clone the git-repo and I execute bootstrap.sh. With curl I don't have this issue.
