### ISSUE TITLE
set nowrap

### ISSUE THREAD

**Issue by netpoetica** [spf13/spf13-vim#149]
In your .vimrc file, you have "set nowrap" but the comments say to enable wrap. Shouldn't this be "set wrap" or change the comments? 

PS. I know the issue list isn't the place for praise, but great job on this project ppl the .vimrc is incredibly insightful into some things that I was missing out on. Thanks so much.

**Comment by ghost** [comment]
I think that comment is gone 

. @spf13 or @netpoetica can close this issue now.

**Comment by netpoetica** [comment]
@jrobeson Looks good, closing
