### ISSUE TITLE
Escaping spaces in InitializeDirectories() should have global flag

### ISSUE THREAD

**Issue by bentsai** [spf13/spf13-vim#15]
On line 415, the line is:

```
      let directory = substitute(directory, " ", "\\\\ ", "")
```

Only the first space gets escaped, so if `directory` has two spaces, the next line gets borked. I had this problem on Windows, where my home directory was under `C:\Documents and Settings\`. This can be fixed by passing in the global flag:

```
      let directory = substitute(directory, " ", "\\\\ ", "g")
```

**Comment by spf13** [comment]
Thanks. I'll add this in.
