### ISSUE TITLE
fatal: Not a git repository on install

### ISSUE THREAD

**Issue by nddery** [spf13/spf13-vim#150]
Hi,

I am on Mac OSX 10.7.x, I get this fatal error whenever I try to install from scratch.

->curl http://j.mp/spf13-vim3 -L -o - | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   986  100   986    0     0   1349      0 --:--:-- --:--:-- --:--:--  1349
Thanks for installing spf13-vim

backing up current vim config

ln: /Users/nicolas/.vimrc: File exists
ln: /Users/nicolas/.vimrc.bundles: File exists
updating spf13-vim

fatal: Not a git repository (or any of the parent directories): .git
installing plugins using Vundle
E282: Cannot read from "/Users/nicolas/.spf13-vim-3/.vimrc.bundles"Vim: Reading from stdin...

**Comment by spf13** [comment]
Hmm.. I must have broken this earlier today. I'll have a fix for it up soon.  

Best,
Steve

## 

Steve Francia
@spf13 (http://twitter.com/spf13)

**Comment by nddery** [comment]
Also, I don't know if this is related or not but since this, the structure for my .spf13-vim-3 directory looks like ".spf13-vim-3/.vim/.vim/.vim/.vim./vim......" indefinitely - I went through maybe 30 sub ".vim" directory and it was still going.

**Comment by spf13** [comment]
Yup. That's definitely what I broke today. Sorry, working on it now. Should have tested it more thoroughly.  

Best,
Steve

## 

Steve Francia
@spf13 (http://twitter.com/spf13)

**Comment by spf13** [comment]
I just committed a fix, can you test it now?

Best,
Steve

## 

Steve Francia
@spf13 (http://twitter.com/spf13)

**Comment by nddery** [comment]
Fixed! Thanks a lot for that fast turn around, and that awesome vim distro!

**Comment by spf13** [comment]
You are welcome.   

Best,
Steve

## 

Steve Francia
@spf13 (http://twitter.com/spf13)

**Comment by delpo** [comment]
Now I have the same problem:

MacBook-Pro-de-Angel:.spf13-vim-3 delpo$ curl http://j.mp/spf13-vim3 -L -o - | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147  100   147    0     0    447      0 --:--:-- --:--:-- --:--:--   864
100  1110  100  1110    0     0    779      0  0:00:01  0:00:01 --:--:--  2106
Thanks for installing spf13-vim

backing up current vim config

cloning spf13-vim

fatal: destination path '/Users/delpo/.spf13-vim-3' already exists and is not an empty directory.
setting up symlinks
ln: /Users/delpo/.vimrc: File exists
ln: /Users/delpo/.vimrc.bundles: File exists
update/install plugins using Vundle
E282: Cannot read from "/Users/delpo/.spf13-vim-3/.vimrc.bundles"Vim: Reading from stdin...

**Comment by guestpectacular** [comment]
Hi delpo, 

I was experiencing the same problem than you, just remove the directory spf13-vim-3 and start again:

rm -rf /Users/delpo/.spf13-vim-3 && curl http://j.mp/spf13-vim3 -L -o - | sh

Best,
Edgar.

**Comment by delpo** [comment]
Thanks a lot!

**Comment by AlexMost** [comment]
i faced the same issue... installation script opens vim and prompts : 

"-stdin-" 1 line, 1 character

help )

**Comment by happosade** [comment]
Tried everything above, still get this (on latest mac, clear install & MacVIM)

Installing Vundle
/dev/fd/63: line 52: git: command not found
update/install plugins using Vundle
E282: Cannot read from "/Users/happosade/.spf13-vim-3/.vimrc.bundles"

**Comment by spf13** [comment]
Your error is different from the above. You either don't have git installed
or its not in your path.

Steve Francia
spf13.com
@spf13

On Mar 4, 2013, at 2:04 AM, Ilari Oras notifications@github.com wrote:

Tried everything above, still get this (on latest mac, clear install &
MacVIM)

Installing Vundle
/dev/fd/63: line 52: git: command not found
update/install plugins using Vundle
E282: Cannot read from "/Users/happosade/.spf13-vim-3/.vimrc.bundles"

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/issues/150#issuecomment-14366565
.

**Comment by apokaliptis** [comment]
I'm having this issue on windows installing form Chocolatey.
`fatal: Not a git repository (or any of the parent directories): .git`
I have Git for Windows installed. Any ideas?
