### ISSUE TITLE
Cannot find word list "en.latin1.spl" or "en.ascii.spl"

### ISSUE THREAD

**Issue by jphustman** [spf13/spf13-vim#156]
In Windows, On vim (not gvim) startup (from command line (cmd and git bash)) I always get "Press ENTER or type command to continue" after a warning flashes up stating that "Warning: Cannot find word list "en.latin1.spl" or "en.ascii.spl""

It is looking in the .vim directory in .spf13-vim-3 and not in the "vimfiles" directory where spell/en.xxx.spl is.

**Comment by spf13** [comment]
This is very strange. Seems like an issue with the vim install (not spf13-vim). The way the system is designed to  work is that it adds ~/.spf13-vim/bundle/\* to the paths it checks, but doesn't replace the standard paths.

**Comment by jphustman** [comment]
Hmm...  I did a vim -D and it came up with this:

``` term
Entering Debug mode.  Type "cont" to continue.
C:\Users\jphustman\Programs\Git\share\vim\vimrc
line 3: set ai                          " set auto-indenting on for programming
>cont
Warning: Cannot find word list "en.latin1.spl" or "en.ascii.spl"
CSApprox skipped; terminal only has 16 colors, not 88/256
Try checking :help csapprox-terminal for workarounds
```

So maybe this is related to Issue #90
