### ISSUE TITLE
Snippet is already defined. (When loading Ruby files.)

### ISSUE THREAD

**Issue by stungeye** [spf13/spf13-vim#16]
When I load any .rb files I see a bunch of "Snippet \* is already defined" messages. Is this normal?

Here are the Snippets that are causing the problem:

log, mp, rep, shc, shns, samao, savf, sbt, shabtm, shi, shm, sho

I'm not using your entire vim setup, just your fork of snipmate and your snippets repo. I've installed your snipmate fork in my .vim/bundle/ folder (for pathogen) and the snippets are in .vim/bunlde/snipmate-snippets/snippets/.

**Comment by spf13** [comment]
Yes, I've noticed this. I'm looking into it. It only affects ruby, but of course, you're probably a Ruby programmer, so that would matter a lot to you. Other than those warning messages, it works, right?

**Comment by stungeye** [comment]
Yes, I am a Ruby programmer. The messages aren't horrible, just annoying.
Other than that, things are running smoothly.

**Comment by spf13** [comment]
This should be resolved in the latest release. Please confirm and reopen if the issue persists.

**Comment by woainvzu** [comment]
Hello stungeye,

Do you met that problem again? I have the same situation with you, it also happened against Ruby language.
How did you fix that? thanks!

**Comment by woainvzu** [comment]
Hello stungeye,

Do you met that problem again? I have the same situation with you, it also happened against Ruby language.
How did you fix that? thanks!

**Comment by stephpy** [comment]
You can mention somebody by using @ ;)
