### ISSUE TITLE
ctrlp nnoremap question, what combo is <D-t>?

### ISSUE THREAD

**Issue by tmuka** [spf13/spf13-vim#163]
I see in .vimrc the key mapping for ctrlp is set to 

nnoremap <silent> <D-t> :CtrlP<CR>
nnoremap <silent> <D-r> :CtrlPMRU<CR>

i've searched, but i can't figure out what key combination <D-t> is on my keyboard.  I ended up adding the following to my .vimrc.local so i can use ctrl+t to activate ctrlp.

nnoremap <silent> <C-t> :CtrlP<CR>
nnoremap <silent> <C-r> :CtrlPMRU<CR>

maybe you can school me on how i'm supposed to activate it by default?  thanks!

**Comment by spf13** [comment]
Ctrl+p (it's hidden in the name)  

## 

Steve Francia
@spf13

**Comment by tmuka** [comment]
facepalm! thanks!  out of curiousity, what is 
keymap    D-t ?
(looks like the code was stripped from my post above)

thanks!

**Comment by saladpanda** [comment]
Just in case someone stumbles over this, here is an excerpt from `:help key-notation` which should answer the (still unanswered) initial question:

```
notation        meaning             equivalent  decimal value(s)
-----------------------------------------------------------------------
...
<S-...>         shift-key                       shift <S-
<C-...>         control-key                     control ctrl <C-
<M-...>         alt-key or meta-key             meta alt <M-
<A-...>         same as <M-...>                 <A-
<D-...>         command-key (Macintosh only)    <D-
...
```
