### ISSUE TITLE
After installing on windows, I get "Unknown function: fugitive#statusline" 

### ISSUE THREAD

**Issue by prongs** [spf13/spf13-vim#167]
http://www.evernote.com/shard/s134/sh/c95d28f9-46d1-44c6-ae71-3914f8bbfe9f/6071fa67a5a2fb2bbcc6e20fe8abc488

I am behind an http proxy. I changed git:// to http:// on line 5 in the easy install file(https://github.com/spf13/spf13-vim/blob/3.0/spf13-vim-windows-install.cmd). so that git clone can work just by setting environ variable http_proxy=proxy_address. I run the file via cmd, it succeeds and after that opening gvim gives this error.

**Comment by jhnwsk** [comment]
Hi,

I had the same problem today. It seems that the .cmd installer script does not call 
`vim - +BundleInstall! +BundleClean +qall`. 

Just call this manually after installing and you'll have all the bundles. 
Worked for me on XP.

**Comment by prongs** [comment]
I now get a different error:
http://www.evernote.com/shard/s134/sh/151ce676-cf67-4270-9861-4bc8a1a40468/3f31b5aaebcd46b3ab3ef06f5dd1b7e2

Any ideas?

On Thu, Oct 11, 2012 at 3:51 PM, John notifications@github.com wrote:

> Hi,
> 
> I had the same problem today. It seems that the .cmd installer script does
> not call
> vim - +BundleInstall! +BundleClean +qall.
> 
> Just call this manually after installing and you'll have all the bundles.
> Worked for me on XP.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/spf13/spf13-vim/issues/167#issuecomment-9335119.

## 

Rajat Khandelwal
Undergraduate Student
IIT Delhi

**Comment by jhnwsk** [comment]
Seems like your bundles did not get installed at all. Did you see a vim window with bundles getting installed? If they fail they show an exclamation mark.

I am pretty certain Vundle uses https internally for downloading and installing bundles from github. If you can't clone using https this might fail.

You can also create a vimlog file for your installation process by running the installer with the -V9 option like:
`vim -V9vimlog.log - +BundleInstall! +BundleClean +qall`

This might give you some ideas.

**Comment by jhnwsk** [comment]
Sorry, I might have mislead you. You get these errors when running the command not opening vim right? 

What you see means that you do not have Vundle properly installed. Did the part
`git clone http://github.com/gmarik/vundle.git %HOME%/.vim/bundle/vundle`
execute correctly?

**Comment by prongs** [comment]
yes, I tried git clone manually and it succeeds. I have one question: after
doing this:
vim -V9vimlog.log - +BundleInstall! +BundleClean +qall
what am I looking for? where do I find the log?

On Thu, Oct 11, 2012 at 4:20 PM, John notifications@github.com wrote:

> Sorry, I might have mislead you. You get these errors when running the
> command not opening vim right?
> 
> What you see means that you do not have Vundle properly installed. Did the
> part
> git clone http://github.com/gmarik/vundle.git %HOME%/.vim/bundle/vundle
> execute correctly?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/spf13/spf13-vim/issues/167#issuecomment-9335781.

## 

Rajat Khandelwal
Undergraduate Student
IIT Delhi

**Comment by jhnwsk** [comment]
`-V[N][logfile]` is vim verbose mode. N is the log level and logfile is the path to the file where the output is saved so running `vim -V9vimlog.log - +BundleInstall! +BundleClean +qall` should create a file named "vimlog.log" in the directory where you ran the command.

**Comment by prongs** [comment]
Ok, i modified my .cmd file according to
thishttps://github.com/jhnwsk/spf13-vim/commit/05a6ba34f114c497eb691f9d4bdc0be2a9f4556f
and
now on the last command, vim opens and seems like it's
stuckhttp://www.evernote.com/shard/s134/sh/2fceca21-e5e0-466f-b715-fb0bc07ef8ff/37466650f05b837bd5293c6785f60292.
I suspect that might be due to because of the https thing.

On Thu, Oct 11, 2012 at 5:11 PM, John notifications@github.com wrote:

> -V[N][logfile] is vim verbose mode. N is the log level and logfile is the
> path to the file where the output is saved so running ```vim -V9vimlog.log
> - +BundleInstall! +BundleClean +qall" should create a file named
>   "vimlog.log" in the directory where you ran the command.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/spf13/spf13-vim/issues/167#issuecomment-9336918.

## 

Rajat Khandelwal
Undergraduate Student
IIT Delhi

**Comment by jhnwsk** [comment]
If you run `:h vundle` it says that you can use `:let g:vundle_default_git_proto="http"` to set the protocol vundle uses to http. So if you open up vim, type this in and after that run `:BundleInstall` from inside vim you should be able to get all the bundles via http and not https.

**Comment by prongs** [comment]
Ok. I set https_proxy env variable same as http_proxy and it finished. All
is well.

On Thu, Oct 11, 2012 at 5:17 PM, Rajat Khandelwal rajatgupta59@gmail.comwrote:

> Ok, i modified my .cmd file according to thishttps://github.com/jhnwsk/spf13-vim/commit/05a6ba34f114c497eb691f9d4bdc0be2a9f4556f and
> now on the last command, vim opens and seems like it's stuckhttp://www.evernote.com/shard/s134/sh/2fceca21-e5e0-466f-b715-fb0bc07ef8ff/37466650f05b837bd5293c6785f60292.
> I suspect that might be due to because of the https thing.
> 
> On Thu, Oct 11, 2012 at 5:11 PM, John notifications@github.com wrote:
> 
> > -V[N][logfile] is vim verbose mode. N is the log level and logfile is
> > the path to the file where the output is saved so running ```vim
> > -V9vimlog.log - +BundleInstall! +BundleClean +qall" should create a file
> > named "vimlog.log" in the directory where you ran the command.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/spf13/spf13-vim/issues/167#issuecomment-9336918.
> 
> ## 
> 
> Rajat Khandelwal
> Undergraduate Student
> IIT Delhi

## 

Rajat Khandelwal
Undergraduate Student
IIT Delhi

**Comment by ghost** [comment]
seems like all is fixed here?

@spf13 : you should be able to close this now?
