### ISSUE TITLE
How to remove Visual Tab Reminders (Gray Columns)

### ISSUE THREAD

**Issue by justaparth** [spf13/spf13-vim#169]
Hey all,

I can't figure out how to remove the visual tab reminders seen in the following picture http://imgur.com/TLtJs (on lines 19-20, 22-23, etc). They're the gray columns. I tried :set nolist, but it didn't get rid of them. Any thoughts on how I can get rid of these?

Thanks!

**Comment by ryanemmm** [comment]
Look at the "indent-guides" section in .vimrc

I'm not sure what exactly is going on in this block, but if you set:
g:indent_guides_enable_on_vim_startup = 0

Then :so .vimrc, the guides go away.

**Comment by jphustman** [comment]
You can toggle them on/off with `,ig`.

**Comment by orsenthil** [comment]
Helpful. I think, this should be documented. Searching this was difficult.

**Comment by justaparth** [comment]
Thank you! I changed this in my .vimrc.local but it had no effect (i did rm ~/.vimview/*). Changing it in my .vimrc worked, however.

**Comment by gravis** [comment]
Thanks for this issue, I was looking for this too :)

**Comment by tomibennett** [comment]
hi, and to have it with dots please ? :)
