### ISSUE TITLE
fugitive#statusline failing

### ISSUE THREAD

**Issue by ndbroadbent** [spf13/spf13-vim#17]
On a completely clean Ubuntu installation (never used a .vimrc before), I followed your instructions but got these errors:

E117: Unknown function: fugitive#statusline
E15: Invalid expression: fugitive#statusline()

To fix it I added ":so bundle/fugitive/plugin/fugitive.vim" to line 88, like this:

if has('statusline')
        :so bundle/fugitive/plugin/fugitive.vim
        set laststatus=2

Also, your 'solarized' color scheme isn't included anywhere.

**Comment by spf13** [comment]
Sorry for the delay, I thought I responded to this. 
Did you install the submodules, it sounds like they may be missing?
How did you install it? What commands did you run?

**Comment by ndbroadbent** [comment]
Hi again, sorry, I just ran the 'Easy Installation' command and it works fine.
I seemed to have problems when I cloned the repo and checkout out the submodules manually, but I probably missed a few steps. Sorry to bother you!!

**Comment by spf13** [comment]
NP, glad it's working well for you.

**Comment by mrthebob** [comment]
How does one install the submodules in order to get rid of this error?

**Comment by 11Kilobytes** [comment]
On my system it isn't working, Vundle isn't being loaded but it is installed correctly.
