### ISSUE TITLE
non-0 exit code on OSX

### ISSUE THREAD

**Issue by niko** [spf13/spf13-vim#170]
I get a non-0 exit code on OSX which causes mutt to barf and even worse makes git to refuse the commit message all together. It doesn't matter wether the edited file is saved or not.

Try

```
vi foo ; echo $?
```

to reproduce.

**Comment by spf13** [comment]
## Fixed and committed. Please update to latest.

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by niko** [comment]
That does the trick. Thanks for the fast fix.
