### ISSUE TITLE
hitting escape in autocomplete mode puts me in insert mode?

### ISSUE THREAD

**Issue by egradman** [spf13/spf13-vim#177]
If I'm typing and the autocomplete window pops up, and I hit escape I wind up in insert mode... not normal mode like I'd expect.

The author of neocomplcache assures me that it should work the way I expect (normal mode) and that the problem lies in my configuration.  But I've commented out almost all the neocomplcache configuration and I still have this problem.  Is there some other binding I've missed that might cause this problem?

**Comment by egradman** [comment]
Indeed, `inoremap <expr> <Esc>      pumvisible() ? "\<C-e>" : "\<Esc>"` was causing my problem.  What is the intended function of that mapping?

**Comment by tmuka** [comment]
thanks, egradman, this behavior was annoying me too.  commenting out that line in .vimrc fixed it.

**Comment by spf13** [comment]
I think the idea here is that <esc> when the popup is present closes the
popup but leaves you in insert mode. Hit it twice to leave (once to leave
the popup and once to get out of insert mode). I could be convinced it's
not the right behavior, but it makes sense to me.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by jcbwlkr** [comment]
It messes with me sometimes but I think the logic is that if you were
autocompleting every other word in a line it would be annoying to go back
in to insert mode every time.

The thing that really messes with me (which is probably unrelated) is that
I will go down to a word from the list until the line looks right and my
instinct is to hit <esc> to be done but that puts the text back to what I
had explicitly typed.

**Comment by tmuka** [comment]
yeah, steve, i can understand how that makes sense.  jacob, that's exactly the issue i run into, especially when editing css/scss files.  i typically make a word change (cw) then go back to normal mode after each change. (pragmatic vim style workflow)  i think i've figured out using the enter key to confirm the neocomplcache selection is the way to avoid using escape twice.  now i just have to retrain my fingers!

**Comment by nugend** [comment]
I find it extremely annoying. If you don't want to use the autocomplete suggestions, you just don't hit tab and/or enter to select any. I'd at least like a simple way to turn it off. Disabling the remap in my personal patch set anyway.

Actually, I'm pretty sure it didn't work this way until a few months ago. I found the autocomplete much more useful when this behavior didn't exist.

**Comment by frankier** [comment]
This is the most annoying this ever. It results in me almost always jabbing at escape like a lunatic to enter command mode.

**Comment by szevzol** [comment]
It annoys me too so I reset the mapping in my .vimrc.local:

inoremap &lt;expr&gt; &lt;Esc&gt; "<Esc>"

**Comment by foges** [comment]
Thanks szevzol. This fixed it for me.

**Comment by taxilian** [comment]
In case you care, my vote is also to remove this; this absolutely drives me crazy.  I _hate_ it. (but fortunately it's open source and I can turn it off in my fork)

**Comment by taxilian** [comment]
For others who find this thread and want to disable it locally, add this line to your .vimrc.local file:

```
iunmap <expr> <Esc>
```

**Comment by wsdjeg** [comment]
&```
noremap <expr> <cr> pumvisible() ? "<esc>a" : "<cr>"

```
```
