### ISSUE TITLE
UndoTreeToggle not working

### ISSUE THREAD

**Issue by msmart** [spf13/spf13-vim#178]
Hi, not matter what I try (eg. fresh install) I dont get UndotreeToggle to work when installing spf13. I am on OS X 10.8.2 with XCode installed.

When e.g. pressing ",u" I get the error E492: Not an editor command: UndotreeToggle. No Undotree command seems to be working.

scriptnames does show that the plugin is loaded.

What can I do to debug?

Regards
Michael

Just an update. I made a clean install on a second computer and had the same issue (OS X 10.8.1).

**Comment by sica07** [comment]
Same issue under linux too.

**Comment by bronzehedwick** [comment]
This is an old issue; @msmart, are you still having the problem? If not, could you close? Thanks!

**Comment by msmart** [comment]
Yes, it's fixed for me, thanks for reminding me.

**Comment by bronzehedwick** [comment]
Sweet :)
