### ISSUE TITLE
VimDebugger.vim: Unable to find VimDebugger.py

### ISSUE THREAD

**Issue by 01iv3r** [spf13/spf13-vim#18]
i get the following error when launching vim after installing spf13-vim on my CentOS server :

```
VimDebugger.vim: Unable to find VimDebugger.py. Place it in either your home vim directory or in the Vim runtime directory.
[O]K: 
Error detected while processing function DefPython:
line  549:
Traceback (most recent call last):
  File "<string>", line 546, in ?
  File "<string>", line 396, in __init__
NameError: global name 'VimDebugger' is not defined
Press ENTER or type command to continue
```

note: I have spf13-vim installed to `/usr/local/share/vim/spf13-vim`
and am using the following sylinks:

```
ln -s /usr/local/share/vim/spf13-vim/.vimrc /usr/local/share/vim/vimrc
ln -s /usr/local/share/vim/spf13-vim/.vim /usr/local/share/vim/vimfiles
```

so that spf13-vim accessible for all users running vim 7.3.189.

everything else I have tested is is working great so far (much better than Janus! :). 

I love having the leader key remapped to "," and default colors look fantastic under Visor on OS X :D
http://www.rawcanvas.com/_/_skitch/Terminal_%E2%80%94_ssh_%E2%80%94_bash_%E2%80%94_94%C3%9736-20110515-190150.jpg

**Comment by spf13** [comment]
It looks to me like it's trying to parse the python function as vimscript. Do you have python support in your vim?

The author of VimDebugger.vim should have wrapped this in a has('python').. If you don't have this problem on your mac, that would be my first guess.

**Comment by 01iv3r** [comment]
I recompiled vim with python and ruby on both my mac and server before installing spf13. both now echo now as 1. 

Note: I am still running Janus on my mac so I can test out both. So far spf13 seems far better.

I did not have ruby or python support on either my mac or server before (only in MacVim) and including these languages did fix a bunch of issues with Janus which did not mention this as a pre-requisite.

**Comment by 01iv3r** [comment]
Huh, if I instead create symlinks at ~/.vim & ~/.vimrc, I no longer get the VimDebugger.vim error, but instead get...

```
C/C++ template file '/usr/local/share/vim/vimfiles/c-support/templates/Templates' does not exist or 
is not readable
```

it looks like that path location is being cached. but even trashing ~/.viminfo,backup,swap,&views I get the same error. And it is far more desirable for me to use the vimfiles symlinks so that the same setup is accessible for all users. Any advice?

**Comment by spf13** [comment]
That's really odd, I haven't see that before. I'll ask taxilian who installed that plugin. 
Where is spf13-vim installed on your system?

Any idea why it would be referencing that location?

**Comment by 01iv3r** [comment]
/usr/local/share/vim/spf13-vim/

only idea is that I first ran spf13-vim with the following aliases...

/usr/local/share/vim/vimfiles
/usr/local/share/vim/vimrc 

with those I still get the debugger path error: `Unable to find VimDebugger.py. Place it in either your home vim directory or in the Vim runtime directory.`

and ideally I'd like to use symlinks at /usr/local/share/vim to avoid recreating them for every user.

most of this stuff is greek to me. apologies.

**Comment by spf13** [comment]
I've never tried to put it in a global place.. Not sure how it would respond, but I'd think it would 'just work'. Not sure what's happening for you. I'd need to play with it to figure it out.

**Comment by 01iv3r** [comment]
ok.. um.. could pm you some access credentials?

**Comment by spf13** [comment]
This has been fixed (plugin removed) in the latest version of spf13-vim. Please upgrade.
