### ISSUE TITLE
Modifying formatting options in .vimrc does not change C++ indentation

### ISSUE THREAD

**Issue by cihati** [spf13/spf13-vim#180]
I tried to change C++ tab indentation from 4 to 2, by modifying shiftwidth, tabstop, softtabstop to 2. Tabs still make 4 spaces instead of 2.

**Comment by jaywilliams** [comment]
Have you tried clearing the viewstate (~/.vimviews)?

**Comment by ghost** [comment]
closing this due to lack of information.
