### ISSUE TITLE
font size doesn´t change

### ISSUE THREAD

**Issue by novito** [spf13/spf13-vim#184]
Everything installed in a MAC, when opening vim the font size is a particular way, but when opening MacVim is bigger. Also with MacVim I see a transparency that I have to overwrite in .vimrc.local .

I have tried to set the font size by doing:

set guifont=Monaco:h14

In .vimrc.local

But it doesn't take any effect. Any thoughts of what can be happening? I have tried with vim without spf13 and I can accomplish that.

**Comment by bronzehedwick** [comment]
Both the transparency and the guifont are GUI only, meaning you have to put your configurations in .gvimrc.local

**Comment by novito** [comment]
Interesting...So, let me ask it in another way...How can I change the font in vim? Let's say I don't want to use MacVim...

**Comment by bronzehedwick** [comment]
Vim uses the terminal font, so you would have to change the font in your terminal.
