### ISSUE TITLE
set nofoldenable not working

### ISSUE THREAD

**Issue by ghost** [spf13/spf13-vim#185]
Trying to disable folding and it seems setting this does not work. Is there another option? Thanks

**Comment by sbennett18** [comment]
Have you tried to deleting the saved view for the file you're editing in ~/.vimviews?

**Comment by ghost** [comment]
@ianloverink if it's php related then you might also want to set this if clearing ~/.vimviews didn't work.

```
let g:DisableAutoPHPFolding = 1 " disable PIV's folding
```

**Comment by ghost** [comment]
i added this to the [FAQ](https://github.com/spf13/spf13-vim/wiki/faq).

I believe that would solve your problem so i am closing this issue.

**Comment by ghost** [comment]
Please comment if it doesnt. I will reopen promptly.

**Comment by Puneeth-n** [comment]
Doesn't seem to work with TeX files. :set nofoldenable doesn't seem to work on \textit{} and \textbf{} and Yes! I deleted from  ~/.vimviews
