### ISSUE TITLE
Avoid hiding NERDTree when opening a file

### ISSUE THREAD

**Issue by novito** [spf13/spf13-vim#186]
When NERDTree is open, before I installed spf13 I could open a file which would be splited vertically with the NERDTree. However, right now everytime I open a file the NERDTree disappears and therefore I need to <ctrl e> to have it back.  If this is the expected behavior, how can I change it to the NERDTree default one?

**Comment by jredville** [comment]
setting `let NERDTreeQuitOnOpen=0` in your `~/.vimrc.local` should handle this for you

**Comment by bronzehedwick** [comment]
@novito, this is a pretty old issue. did jredville's solution work for you? If so, please close :)

**Comment by ghost** [comment]
closing for lack of response. reopen if you can you can reproduce with latest spf13-vim

**Comment by vshvedov** [comment]
Even with `let NERDTreeQuitOnOpen=0` there's still a problem: first file open closes NERDTree. After it's enabled with Ctrl-E back, it works as expected.

**Comment by souhaiebtar** [comment]
NERDTreeQuitOnOpen=0 don't resolve the problem, any solution ?

**Comment by dagolinuxoid** [comment]
@vshvedov, @souhaiebtar
The working [solution](https://stackoverflow.com/a/61039352/4814774)
