### ISSUE TITLE
update to garbas' snipMate (possibly add Zen Css snippets)

### ISSUE THREAD

**Issue by 01iv3r** [spf13/spf13-vim#19]
msanders' snipMate seems to have been stale for quite some time. Looks like garbas is taking over the torch.
see: https://github.com/garbas/vim-snipmate

also, I noticed spf13-vim adds a few basic css snippets. Maybe consider upgrading to this:
https://github.com/tisho/css-snippets-snipmate/blob/master/css.snippets
Zen Coding css style snippets. They're a life saver for writing css as they are sooo intuitive.

**Comment by spf13** [comment]
Great Idea on both accounts. Will do.

**Comment by 01iv3r** [comment]
awesome. you rock :)

**Comment by 01iv3r** [comment]
note: garbas just updated to include those zen css snippets :)

**Comment by spf13** [comment]
Checkout the 3.0 branch I started today. Still experimenting, but
really like how it's coming together.

If you do git checkout, take care as its a pretty radical change from
master. Read the updated bootstrap ( which doesn't work as it's still
pointing to master) to see changes in the setup.

Steve Francia
VP, Engineering
OpenSky

@spf13

On May 17, 2011, at 8:28 PM, featherodd
reply@reply.github.com
wrote:

**Comment by 01iv3r** [comment]
ok, will do..

quick question, where is the updated bootstrap located? 
(https://github.com/spf13/spf13-vim/blob/3.0/bootstrap.sh)

**Comment by spf13** [comment]
Yup.

Steve Francia
VP, Engineering
OpenSky

@spf13

On May 18, 2011, at 2:14 AM, 01iv3r
reply@reply.github.com
wrote:

**Comment by 01iv3r** [comment]
confused, 3.0 bootstrap doesn't seem to show any changes to the setup.
