### ISSUE TITLE
E282: Cannot read from "/home/XXx/.spf13-vim-3/.vimrc.bundles"Vim: Reading from stdin... 

### ISSUE THREAD

**Issue by xubin649** [spf13/spf13-vim#190]
when I tried to install spf13-vim on my ubuntu with automatic installer, I got the following error. 
E282: Cannot read from "/home/XXx/.spf13-vim-3/.vimrc.bundles"Vim: Reading from stdin... 

I happened to both my labtop and desktop.  Please help! super thanks!!

**Comment by spf13** [comment]
What OS?  

## 

Steve Francia
@spf13

**Comment by xubin649** [comment]
Thank you for the quick reply. I'm running it on ubuntu 12.10

**Comment by jesuscakes** [comment]
I am having the same problem in Arch Linux. Fix it please please please.

**Comment by spiroski** [comment]
Same problem elementary OS (ubuntu 12.04 based).

**Comment by akamike** [comment]
Had the same problem on OS X 10.7.5, removing ~/.spf13-vim and running the install again worked for me.

**Comment by xubin649** [comment]
I installed it manually and it finally works.

**Comment by z342526265** [comment]
I have the same problem on ubuntu 12.10 , and removing ~/.spf13-vim-3 and running the install again worked for me too.

**Comment by vqng** [comment]
same here, removing ~/.spf13-vim-3 solved it.

**Comment by micheal-swiggs** [comment]
worked for me too.

**Comment by omerson** [comment]
I have no such file (~/.spf13-vim-3)

**Comment by spf13** [comment]
I believe this has been resolved with the latest installer. Please reopen with more information if it is still an issue.

**Comment by lmayorga1980** [comment]
Recently encountered this issue, and removing existing `.spf13` older worked for me as well.

**Comment by okayboy** [comment]
I have the same problem on Mac OS X 10.10.1 and removing .sp13-vim worked for me.

**Comment by Puneeth-n** [comment]
Had the same problem today on OS X 10.10 removing .spf13-vim worked for me

**Comment by lcytzk** [comment]
I have the same problem on Mac OS X 10.11.1 and removing .sp13-vim worked for me.

**Comment by zhidou** [comment]
I still have that problem on Mac os x 10.11.1. and I don't know how to deal with it. How to remove .sfp13-vim?? that means remove sfp13-vim.sh??

**Comment by gideon-maina** [comment]
I had the same problem on Mac OS X 10.11.5 El Capitan and removing (rm -rf .sp13-vim3) worked for me too.

**Comment by netcookies** [comment]
ye, `rm -rf .spf13-vim-3` worked fo me

**Comment by elangx** [comment]
rm -rf .spf13-vim-3 works for me too (macOS 10.12.4)

**Comment by yinsang** [comment]
`brew install vim --with-lua --with-override-system-vi`
`curl https://j.mp/spf13-vim3 -L > spf13-vim.sh && sh spf13-vim.sh`
