### ISSUE TITLE
unable to access default clipboards

### ISSUE THREAD

**Issue by orsenthil** [spf13/spf13-vim#191]
#153 and #155 makes changes to the clipboard support.  This is breaking the previous good behavior of system clipboard access. Previous I used to yank, copy and use " (default) or \* as the registers. Only this is not possible.  I can only use named registers if I have copy and paste. Unavailability of default registers is  a hindrance.

Mine is vim 7.3 on Mac OS X, with -xterm_clipboard and `set clipboard=unnamed`

:+1: for spf13-vim

**Comment by wolfgangpfnuer** [comment]
Did you recently switch your vim binary?

> If you see "+xterm_clipboard", you are good to go. If it's "-xterm_clipboard", you will need to look for a version of Vim that was compiled with clipboard support. I have found that the Vim that ships with Ubuntu has clipboard support (not vim-tiny, you need vim-gnome or vim-gtk), but the one with Redhat/CentOS does not.

http://vim.wikia.com/wiki/Accessing_the_system_clipboard

**Comment by jaywilliams** [comment]
I had the exact same issue. I even compiled vim from scratch with `--enable-clipboard=yes` and `--enable-xterm_clipboard=yes` to no avail. I ended up commenting out `set clipboard=unnamed` from my .vimrc file.

**Comment by spf13** [comment]
Does this fe6ea839a345c9a50d5656d64396d4ed665cbe69 resolve the issue here?

**Comment by jaywilliams** [comment]
Yes, that fixes the problem. I can now share the clipboard between terminal vim and MacVim. Thanks for you help.

**Comment by jrschumacher** [comment]
Is this still using the `" + y` command? I am having issues despite updating to the latest of spf13 (did notice a warning about vim not being compiled with python, is this a requirement?)

**Comment by jaywilliams** [comment]
Using MacVim & vim in iTerm it works with the native `y` command, without a need to define a buffer using the quote mark. Although, my version of vim _does_ have python support. (I compiled it using [homebrew](http://mxcl.github.com/homebrew/), which I highly recommend using.)

**Comment by jrschumacher** [comment]
Is it in your global clipboard?

**Comment by jaywilliams** [comment]
Yes, and it's quite handy when working with other programs.

**Comment by omares** [comment]
Same issue, cant copy paste into/from the global clipboard.

vim version gives me following output. Installed via brew on a Mac OS X 10.7.5. 

```
21:50:27 ~ ❯ vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Feb 26 2013 15:06:43)
MacOS X (unix) version
Included patches: 1-831
Compiled by ME!
Huge version without GUI.  Features included (+) or not (-):
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    
+farsi           +mouse_netterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX -no-cpp-precomp  -Os -w -pipe -march=native -Qunused-arguments -mmacosx-version-min=10.7 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: /usr/bin/clang   -L. -L/usr/local/opt/rbenv/versions/1.9.3-p392/lib  -L/usr/local/lib -o vim        -lm  -lncurses -liconv -framework Cocoa    -framework Python   -lruby-static -lobjc -L/usr/local/opt/rbenv/versions/1.9.3-p392/lib
```

Am i missing something out?

**Comment by omares** [comment]
It seems when installing vim via brew none of the buildin if conditions, regarding the clipboard setting, validate. So the clipboard variable is empty.

I solved the issue by adding the `set clipboard=unnamed` to my .vimrc.local

**Comment by wolfgangpfnuer** [comment]
@omares you had -xterm_clipboard.
maybe that was the problem? you should have +xterm_clipboard and +clipboard afaik.

**Comment by omares** [comment]
No its definitively a problem with the `set clipboard` code and evaluation. Checking the variable in vim with `set clipboard?` gives me `clipboard=`

After adding the variable setting to my .vimrc.local the same check gives me `clipboard=unnamed` and it copy pastes into the \* register by default.

**Comment by rafaponieman** [comment]
Advise:
If you're using Kubuntu, install the package vim-gtk and NOT vim. Vim installs vim-tiny that has no system clipboard support. On Ubuntu, install vim-gnome.

**Comment by micheal-swiggs** [comment]
@rafadev 
Thanks, installing vim-gnome fixed it for me.

**Comment by SivaCn-ZeOmega** [comment]
Could anyone share the spf13 configured for CentOS6.5, having pyton2.6

**Comment by Dariusz-Choinski** [comment]
One solution of problem with pasting a content from X clipboard is to find and comment in .vimrc this line:
"set mouse=a   ( but mouse will not be available in all vim modes)
You can paste a content from X clipboard by pressing p or P in Normal mode, or by right click in Insert mode.
If you still use the mouse a lot may would be better to change it to:
set mouse=n
Mouse will be available in vim Normal mode and you can move the cursor and paste a content from X clipboard by pressing p or P, or in Insert mode you can paste by right click  under present cursor position.

**Comment by JoErNanO** [comment]
@Dariusz-Choinski Thanks for that. I am used to Ctrl+Shift+C and Ctrl+Shift+V for copy/pasting in the shell and could not do that with out-of-the-box spf13 settings. Putting this here for future reference.

**Comment by hchiao** [comment]
@jaywilliams how do you reinstall spf13-vim with the flags `--enable-clipboard=yes` and `--enable-xterm_clipboard=yes?`  I am using the command `curl http://j.mp/spf13-vim3 -L -o - | sh` to install, how should I add the flags in that command?

**Comment by ghost** [comment]
spf-vim doesn't install vim for you. you have to make sure your installed vim has those.

**Comment by jaywilliams** [comment]
I used custom compile flags in Homebrew to compile my own version of Vim.

**Comment by EricYT** [comment]
How to fix the problem in centos that -clipboard?Thanks all.

**Comment by ghost** [comment]
you have to compile vim yourself @EricYT , or find someone elses package of someone who did that.

**Comment by EricYT** [comment]
@jrobeson I compiled it by myself and installed the vim-X11.But still not work!Now I'm ready to download the vim-gnome package if there is one for centos 7.

**Comment by zx1986** [comment]
How could I disable this feature?
When I `dd` in vim, I got things that delete in vim into my clipboard, 
I don't want that ...

**Comment by qinyuhang** [comment]
I can't do cmd+c in my Mac terminal vim too. When using mouse select text, vim enter visual mode, cmd+c is disabled. Esc will exit visual mode, but the text is no longer selected. PLZ help to copy text from vim to system clipboard so I can copy to a browser.

**Comment by charpty** [comment]
I can't do cmd+c in my Mac terminal vim too....

**Comment by wolfgangpfnuer** [comment]
If you got clipboard correctly configured (see above), you can copy with "y" (yank).
If you use iterm2, you can select text with alt and it's copied by iterm2 (even works on a server)

**Comment by manofmountain** [comment]
Below are my vim information, seems i have built it well with clipbard supported. However i still can't see '+' or '*' registers within it and can't copy or paster the content from/to system board, anyone have an idea on this? thanks so much in advance..

```
$ vim --version | grep clipboard
+clipboard         +jumplist          +persistent_undo   +vertsplit
+emacs_tags        +mouse_dec         -sun_workshop      +xterm_clipboard
```
Below are the registers information of vim.
```
~
 NORMAL  SPELL [EN] ››  1:                                                                   ‹‹ [unix] ‹ 100% ☰    0/1 ㏑ :  1 ‹
:reg
--- Registers ---
""   "set tags=/home/lshusen/master/tags^J"set tags+=/home/lshusen/mkl-dnn/tags^J"set tags+=/home/lshusen/github/nccl/tags^J
"0   "set tags=/home/lshusen/master/tags^J"set tags+=/home/lshusen/mkl-dnn/tags^J"set tags+=/home/lshusen/github/nccl/tags^J
"1           #echo "I_MPI_PIN_DOMAIN=$domain_str"^J
"2               echo "mask_str=$mask_str"^J
"3               for ((mask_index=${#masks[@]}-1; mask_index>=0; mask_index--))^J            do^J                mask_str+=`pri
"4                  ^J
"5   #               fi^J
"6   #               if [ ${masks[$mask_index]}  -eq 0 ]; then^J#                   mask_str+="00"^J#               else^J
"7                   echo "mask_str=$mask_str"^J
"8           export MLSL_SERVER_AFFINITY="${listep}"^J
"9       export MLSL_NUM_SERVERS=${numservers}^J
"-   #
"/   mouse
Press ENTER or type command to continue
```

**Comment by czf1009** [comment]
Even use vim with +clipboard can not fix my problem
Modify .vimrc, change set mouse=a to mouse=v  can fix it.
