### ISSUE TITLE
Setting indent to 2 doesn't behave as expected

### ISSUE THREAD

**Issue by elclanrs** [spf13/spf13-vim#193]
```
set shiftwidth=2
set tabstop=2
set softtabstop=2
```

I tried the above and some js still weirdly default to 4 spaces in some cases. It's not consistent... Are there any other values modifying this?

**Comment by kc-dot-io** [comment]
`rm ~/.vimswap/*` should do ya right.

**Comment by rogerbraun** [comment]
What is the reason for this behaviour?

**Comment by spf13** [comment]
It caches the state of the editor for the file you are editing, stores the
cache in .vimswap.

If you manually change any setting while editing this file, exit vim and
reopen vim it will retain that setting.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by cskeeters** [comment]
I'm still new to vim, but I think .vimrc sets shiftwidth with the old vi style "sw" variable in the indent_guides plugin section.  When I commented that out, I could change the setting in the Formatting section and have them take effect after restarting vim.

**Comment by schickling** [comment]
Same here. Still doesn't work for me.

**Comment by zzeroo** [comment]
Works for me `rm ~/.vimswap/*` does the trick

**Comment by webmaven** [comment]
Isn't working for me (and I set them in both `.vimrc.local` and `.gvimrc.local`, and `~/.vimswap/` is empty). Note, this is a JS file. Could vim-javascript be responsible?

**Comment by SamJoan** [comment]
Deleting the files did not work for me, I am working with ruby files. I will let you know if I find a solution.

I've added this to my ~/.vimrc.local file

<pre>
set smartindent
set shiftwidth=2
set expandtab
</pre>

However, after opening a ruby file, and doing `:set shiftwidth`, vim responds with:

<pre>
shiftwidth=4
</pre>

**Comment by orendon** [comment]
@droope @webmaven if `rm ~/.vimswap/*` didn't worked for you, then try clean your vimviews folder, it probably cached the files you we're editing before. Use `rm ~/.vimviews/*` that should pick up your new settings.

**Comment by spf13** [comment]
It's probably a ruby specific plugin that is setting it upon opening a ruby file which would happen after the .local file is read. That's a pretty common thing for language specific plugins to do.

**Comment by webmaven** [comment]
Not sure what changed  (`rm ~/.vimviews/*` didn't have any effect for at least a few days), but JS files eventually _did_ start picking up the 2-space indentation as intended.

**Comment by mightyiam** [comment]
@webmaven so I'm hopeful my JS files will, as well...

**Comment by zhiyelee** [comment]
`rm ~/.vimswap/*` works for me here.

**Comment by seeder** [comment]
for me , had to clear the `.vimviews`

can't believe this is still an issue

**Comment by kai101** [comment]
`rm -f ~/.vimviews/*` works for me.

2 tab indent for javascripts files with this in `~/.vimrc.local`
`autocmd Filetype javascript setlocal ts=2 sw=2 sts=2 expandtab`

**Comment by yrncollo** [comment]
I am having the same issue and `rm ~/.vimviews/*` and `rm ~/.vimswap/*` hasn't helped. Is there another way I can solve it?
