### ISSUE TITLE
Diff breaks in fugitive :Gstatus

### ISSUE THREAD

**Issue by Tylerc230** [spf13/spf13-vim#195]
I am unable to look at the diff of more than 1 file in fugitives status screen.
Steps to repro:
1. open vim in git repo with local modifications in multiple files
2. <leader>gs to open fugitive status
3. 'D' on individual files

observed:
The first time I type 'D', I see the diff of the file I'm diffing. If I try to 'D' on a different file, vim opens an edit buffer below the commit  window instead of the diff buffer. From there I am unable to diff any of the files. Basically I can only diff 1 file when I open a status window in fugitive (It is not 100% reproducible, probably more like 90%).

**Comment by Tylerc230** [comment]
The problem is 'set hidden' breaks fugitive diff. See: https://github.com/tpope/vim-fugitive/issues/91

**Comment by bronzehedwick** [comment]
@Tylerc230, were you able to `set nohidden` in your `.vimrc.local` to fix the issue?

**Comment by Tylerc230** [comment]
Hey sorry, just saw this. My solution was to comment out the `set hidden` line in the spf13 .vimrc file. This no longer seems to be an issue for me though. Perhaps it was fixed in fugitive?

**Comment by ghost** [comment]
i guess so as i haven't seen the issue in awhile either. closing!
