### ISSUE TITLE
vim: symbol lookup error: vim: undefined symbol: init_hashlib

### ISSUE THREAD

**Issue by RafalBabinicz** [spf13/spf13-vim#197]
Setup:
Installed in Ubuntu 12.10 with curl http://j.mp/spf13-vim3 -L -o - | sh  

After BundleInstallation: Done!vim: symbol lookup error: vim: undefined symbol: init_hashlib
Exec 'vim' in termianal: vim: symbol lookup error: vim: undefined symbol: init_hashlib
Exec 'gvim' - it works with GUI
Exec 'gvim -v', also works in terminal.

**Comment by hupili** [comment]
same problem on Ubuntu 12.04 + vim 7.3. Solved after [upgrading vim to 7.4](http://linuxg.net/how-to-install-vim-7-4-on-ubuntu-13-10-13-04-12-04-linux-mint-16-15-13-and-debian-sid/)

**Comment by spf13** [comment]
ubuntu's default vim is awful. You pretty much need to upgrade to the full vim installation anyway with Ubuntu.
