### ISSUE TITLE
: e $MYVIMRC corrupt .vimrc file on Windows

### ISSUE THREAD

**Issue by tinybyte** [spf13/spf13-vim#199]
I changed vimrc using : e $MYVIMRC, after saving, vim stripped off all the braces.
for example:
set statusline+=%{fugitive#statusline()} "  Git Hotness 

changed to 

set statusline+=%fugitive#statusline() "  Git Hotness

thus next startup will emit a list of errors.

I don't why, is there an configuration in spf13-vim striped off the braces?
when I open vimrc files, I see all the braces are changed to dot, why? 
I have already removed set spell, why when I edit my vimrc files, I still get spell checking?

**Comment by spf13** [comment]
Another plugin could be turning spell on. 

I've never heard of this issue stripping '{}' on windows or any other platform. Are you absolutely positive it was Vim doing it?
