### ISSUE TITLE
gvim start with warning(  invalid syntax: "Copyright strftime ... )

### ISSUE THREAD

**Issue by clar** [spf13/spf13-vim#200]
invalid syntax:  Copyright `strftime("%Y")` ${1:copyright holder}" is detected

Seems caused by some plugin, did anyone meet this issue ?

**Comment by clar** [comment]
Update： It is caused by "  Shougo/neosnippet "

( revert to an older version temporarily can solve it. )

**Comment by ajw** [comment]
I came across this too. Stupid question - how do you revert to an old version of the bundle ?

**Comment by clar** [comment]
It was introduced in  submit for "Refactored parse routine." (5952b6e51d), so to get an older version, 
                  cd ~/.vim/bundle/neosnippet
                   git reset 2aed

I will report one bug in neosnippet

**Comment by Shougo** [comment]
Hi, I'm author of neosnippet.
I checked the snippet. And the problem is found.
It is snippet syntax problem(not neosnippet).

**Comment by Shougo** [comment]
The error was already reported.
https://github.com/honza/snipmate-snippets/issues/150

**Comment by clar** [comment]
Thanks Shougo and jab416171.

As this fix has not been pushed into snipmate-snippets's master, if you want to do patch locally, do following:
cd ~/.vim/bundle/snipmate-snippets
git am –abort  
curl https://github.com/honza/snipmate-snippets/pull/150.patch | git am

**Comment by spf13** [comment]
I see that it has now been merged into snipmate-snippets master.
