### ISSUE TITLE
vimrc throwing errors

### ISSUE THREAD

**Issue by scopium** [spf13/spf13-vim#201]
hello there. i just download ur vimrc file and followed ur instructions on linux. however everytime i want to open a file i get this message 

Cannot execute shell rootuser

Error detected while processing /home/rootuser/.vimrc:
line   21:
E484: Can't open file /tmp/v2DwaDY/0
line   51:
E117: Unknown function: vundle#rc

is there anything i'm missing. ?

**Comment by zuhao** [comment]
Same problem here. Error at line 21.

**Comment by cotton-more** [comment]
Have you installed vundle?

First of all download https://github.com/gmarik/vundle to your ~/.vim/bundle/vundle

Then in command line run: vim +BundleInstall +qall

**Comment by zuhao** [comment]
I found a workaround. Go to line 21 of your .vimrc, and depending on your OS, comment out L21.

So for me (using Fedora Linux), my .vimrc is only left with `set clipboard=unnamedplus` around line 21.

**Comment by orsenthil** [comment]
It could solve the issue for me. clipboard works fine for ,e.
