### ISSUE TITLE
vim-nerdtree-tabs don't work

### ISSUE THREAD

**Issue by JoveYu** [spf13/spf13-vim#202]
in my vim vim-nerdtree-tabs don't work now ,it is a reay nice plugin

**Comment by johntyree** [comment]
You really need to add some more info about what's going on if you want some help with this. "It doesn't work" could mean anything.

**Comment by JoveYu** [comment]
when i use spf13 edit python file in archlinux64  ,vim will automatically exit sometimes ,i don't know why?

and when i open a file in vim-nerdtree-tabs ,why it always autoclose?i remember it will always open as a window!

**Comment by johntyree** [comment]
Do you mean vim crashes? Or does it exit cleanly as if you had used `:q` ?

Is this ONLY with spf13?  Try  `vim -u /dev/null somefile.py` and compare?

Next try disabling the python group in `.vimrc.bundles`, maybe?

Do these things work normally when you install them yourself and not using spf13?

**Comment by JoveYu** [comment]
yes it is ,but i use other colorscheme like desert it work well,i don't if it is colorscheme probrem!

**Comment by JoveYu** [comment]
oh no ,today i use desert colorscheme ,it also break down,i don't why and what i should do !

**Comment by JoveYu** [comment]
i use 

> vim -V9vimlog

it show

> CSApprox: Exiting - high fg color found for gitcommitBranch

**Comment by johntyree** [comment]
CSApprox is for adapting gvim color schemes to work in a terminal.

I don't know why that would be a problem, but maybe your terminal is upset about strange color values?

What terminal are you using? What is the value of `echo $TERM`?

**Comment by JoveYu** [comment]
it is xterm

**Comment by JoveYu** [comment]
when i use "colorscheme desert" ,it show 

> CSApprox: Exiting - high fg color found for EasyMotionTargetDefault

so i commented  "Bundle 'Lokaltog/vim-easymotion'" ,and show no error  and CSApprox work well
