### ISSUE TITLE
how to realize correct indent in fortran 

### ISSUE THREAD

**Issue by gimac** [spf13/spf13-vim#204]
I try to edit .f90 code with auto-indent. For example,
The following are what I want:

program helloworld
      print *, "Hello World!"
endprogram

However, I got 

program helloworld
           print *, "Hello World!"
   endprogram

The same thing happens on "module, function and subroutine". What's more, the indent is totally not working for "do-loop".
Anyone can help to realize attractive "indent" in fortran just like in C and C++ with spf13-vim?  Many thanks.

I think the problem is when I type in an "enter" to finish the 1st line, there are 6 space in the 2nd line, one tab + two wired spaces.

**Comment by spf13** [comment]
Formatting was lost here, but it seems that you are expecting a tab and not seeing one (or seeing one and not expecting to). This isn't a spf13-vim issue, but a consequence of not having a proper indent file for fortran. If you find one that works well for you (or write your own) I would be happy to include it.
