### ISSUE TITLE
ChrisYip/Better-CSS-Syntax-for-Vim interfering with vim-haml syntax

### ISSUE THREAD

**Issue by jamestomasino** [spf13/spf13-vim#206]
Having both of these plugins installed throws a number of errors when opening scss files:

```
E409: Unknown group name: cssValue.*,cssColor,cssURL,sassDefault,cssImportant,cssError,cssStringQ,cssStringQQ,cssFunction,cssUnicodeEscape,cssRenderProp
E475: Invalid argument: cssValue.*,cssColor,cssURL,sassDefault,cssImportant,cssError,cssStringQ,cssStringQQ,cssFunction,cssUnicodeEscape,cssRenderProp
E400: No cluster specified
E475: Invalid argument: sassCssAttributes contains=css.*Attr,scssComment,cssValue.*,cssColor,cssURL,sassDefault, cssImportant,cssError,cssStringQ,cssStringQQ,cssFunction,cssUnicodeEscape,cssRenderProp
```

The incompatibility is listed as a known issue on Better-CSS-Syntax-for-Vim's [README](https://github.com/ChrisYip/Better-CSS-Syntax-for-Vim#known-issue). 

A number of [similar problems](https://github.com/wavded/vim-stylus/issues/15#issuecomment-5537469) have been resolved by switching to the [vim-css3-syntax](https://github.com/hail2u/vim-css3-syntax) plugin instead. It does not appear to have the same conflicts.

**Comment by spf13** [comment]
James, can you create a pull request with this change?

**Comment by jamestomasino** [comment]
Pull request [here](https://github.com/spf13/spf13-vim/pull/207). Thanks, Steve.
