### ISSUE TITLE
Loading ir_black on OSX Doesn't Work Properly

### ISSUE THREAD

**Issue by flowerornament** [spf13/spf13-vim#214]
I'm on a fresh Mountain Lion machine and just installed spf13. At the top of my .vimrc.local is 'colorscheme ir_black'.

When I open vim, ir_black is used prior to having been converted by CSApprox:

![ir_black-pre](http://f.cl.ly/items/0q0q01091J3f2C0I3L0g/Screen%20Shot%202012-11-13%20at%203.07.02%20PM.png)

Then, when I run ':colorscheme ir_black' after launching vim, the CSApprox-converted version is used:

![ir_black-correct](http://f.cl.ly/items/1L2X3w2G333v1o0p0M24/Screen%20Shot%202012-11-13%20at%203.07.22%20PM.png)

This seems to be in accordance with the CSApprox documentation as I read it, but is it possible to set the colorscheme in .vimrc.local without resorting to something like this:

```
if has("gui_running")
  colorscheme ir_black
else
  colorscheme ir_black
  au VimEnter * CSApproxSnapshot! ir_black
endif
```

?

**Comment by flowerornament** [comment]
When I add `:colorscheme ir_black<CR>` or `:color ir_black<CR>` to .vimrc.local, I get this error:

`E185: Cannot find color scheme ir_black<CR>`

**Comment by rbgarga** [comment]
I had the same issue on fedora 17.

**Comment by flowerornament** [comment]
I'm running vim in Terminal.app on Mountain Lion. It looks like vim is looking at the `cterm` color values rather than the `gui` values on the initial load.

I tried doing `set t_Co=256` before setting the colorscheme and a whole host of other things (changing the term and $TERM variables) to no avail.

Oddly, when I do `:echo term` I get `gnome-terminal`.

**Comment by bronzehedwick** [comment]
Huh. I'm running iTerm2 on Snow Leopard and get `gnome-terminal` when i do `:echo term` as well, but do not have the `cterm` for `gui` colors issue.

**Comment by flowerornament** [comment]
I think the problem is that CSApprox isn't loaded when you set the colorscheme in `.vimrc.local`.

Here's one solution, which adds considerably to vim startup time since a new CSApprox of ir_black is created each time:

```
if has("gui_running")
  colorscheme ir_black
else
  colorscheme ir_black
  au VimEnter * CSApproxSnapshot! ir_black
endif
```

Unfortunately the following does not seem to work, even though you might think it would:

```
if has("gui_running")
  colorscheme ir_black
else
  colorscheme ir_black
  au VimEnter * colorscheme ir_black
endif
```

**Comment by flowerornament** [comment]
I decided to take matters into my own hands and made a bundle containing the CSApprox-converted ir_black file.
1. Add `Bundle 'msutherl/vim-colors-ir_black-256'` to your `~/.vimrc.bundles.local` file to install.
2. Add `colorscheme ir_black-256` to your `~/.vimrc`.

Or even better:

```
if has("gui_running")
  colorscheme ir_black
else
  colorscheme ir_black-256
endif
```

**Comment by jamestomasino** [comment]
@msutherl that solution is working fabulously for me. No matter how hard I banged my head against CSApprox and ir_black, it just wasn't working right for me. Your 256 color scheme has fixed everything right up.

**Comment by flowerornament** [comment]
I've been slowly fixing bugs in ir_black-256. Feel free to open a pull request if you find any issues. Note that everything is repeated 3 times (CSApprox is very careful).

**Comment by CoconutTheSlayer** [comment]
Had the same problem on Kubuntu 12.10 @msutherl help works perfectly for me.

**Comment by bronzehedwick** [comment]
@msutherl, since csapprox has been removed from the base installation, and you've created a workaround, is it safe to close this issue?

**Comment by flowerornament** [comment]
@bronzehedwick, just updated + tested and everything seems to work well on my machine.

**Comment by bronzehedwick** [comment]
Cool, thanks!
