### ISSUE TITLE
Trying to add a new plugin error

### ISSUE THREAD

**Issue by dawilliams** [spf13/spf13-vim#217]
Hello,

I've created a ~/.vimrc.bundles.local that reads as follows:

Bundle 'vim-scripts/Windows-PowerShell-Syntax-Plugin'

However when I run gvim I get the following error.  Am I doing something wrong?  Also I've noticed that only gvim is on my windows 7 path.

Error detected while processing C:\Users\me.vimrc.bundles.local:
line 1:
E492: Not a editor command: ypB

Thank you,

David

**Comment by jphustman** [comment]
Not sure if it makes a difference, but "vim-scripts/" is not necessary with vundle, try 

`Bundle 'Windows-PowerShell-Syntax-Plugin'`

**Comment by spf13** [comment]
David, 
This is an odd message indeed. Can you run Vim with debug and see if you can determine more?

Does it work without the 'vim-scripts/' part of the string, it shouldn't make a difference, but that error message has me stumped. It doesn't seem to have anything to do with that line.
