### ISSUE TITLE
Go Code syntax highlighting?

### ISSUE THREAD

**Issue by CodeMonkeyKevin** [spf13/spf13-vim#225]
I can't get gocode syntax highlighting to work.

I added "Bundle 'nsf/gocode', {'rtp': 'vim/'}" to .vimrc.bundles.local and ran :BundleInstall and still nothing.

Is there anything else I need to add/change?

**Comment by CodeMonkeyKevin** [comment]
Never mind fixed it added the line "Bundle 'jnwhiteh/vim-golang'" for the syntax highlighting.

**Comment by spf13** [comment]
If are happy with that plugin and want to issue a pull request I'd gladly
merge it. I've been looking for a good plugin for golang.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by CodeMonkeyKevin** [comment]
Will do, going to play around with for few days and make sure its working as intended.

**Comment by spf13** [comment]
Was this plugin worth adding?

**Comment by chriskaukis** [comment]
@spf13 

Did you ever find a good Golang (Go) plugin? I'm currently trying out fatih/vim-go (https://github.com/fatih/vim-go) and jnwhiteh/vim-golang (https://github.com/jnwhiteh/vim-golang). However, I can't seem to get tabs to work. That is, no matter what I do it seems to always use spaces for my Go code. Any suggestions how to fix this?

Of the 2 plugins above, I think I like vim-go better at the moment since it's got everything all setup, but the mappings don't work. For example, <leader>t for testing, etc.

**Comment by pyanfield** [comment]
Just like @chriskaukis said, Do you know which Golang plugin is better? I tried to add fatih/vim-go, but the syntax highlighting does not work.

@chriskaukis Does the syntax highlighting work for you? How did you do that?

**Comment by chriskaukis** [comment]
The syntax highlighting works, but it doesn't seem to trigger the correct usage of tabs. It sticks to using spaces instead when ever I open a go file. Otherwise, it seems to work decent. If I could get it to trigger tabs instead of spaces for go files and not rely on gofmt to fix it for me I would be pleased.

**Comment by spf13** [comment]
I’ve been using 'fatih/vim-go’ and it’s been working well for me. 

It’s already referenced in the distribution. 

go fmt will change things to spaces anyway. That’s the go standard. “Correct” is subjective. In go, spaces are “correct”. 

Best,
Steve

-- 
Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by chriskaukis** [comment]
gofmt I thought changed to tabs not spaces?

**Comment by bscott** [comment]
I've been unable to get vim-go or syntax highlighting under spf13

In my ~/.vimrc.bundle.local, I have the following:

```
Bundle 'jnwhiteh/vim-golang'
Bundle 'fatih/vim-go'
```

**Comment by pyanfield** [comment]
@bscott I don't think you need to add `Bundle 'fatih/vim-go'` in `.vimrc.bundle.local` file, you can check `.vimrc.bundles` file https://github.com/spf13/spf13-vim/blob/3.0/.vimrc.bundles#L258 , it has been included,what you need to do is just put it in https://github.com/spf13/spf13-vim/blob/3.0/.vimrc.bundles#L94.
That's what I think, but I have the same highlighting problem you can check my issue here https://github.com/spf13/spf13-vim/issues/608

**Comment by bketelsen** [comment]
for what it's worth, I never could get vim-go working with spf13 either.

**Comment by spf13** [comment]
Here are my exact steps I took.. First I deleted everything so I had a clean install.

```
sh <(curl https://j.mp/spf13-vim3 -L)
echo "let g:spf13_bundle_groups=['general', 'neocomplete', 'programming', 'ruby', 'python', 'go', 'javascript', 'html', 'misc', 'writing' ]" >> ~/.vimrc.before.local 
vim +BundleInstall! +qall
```

After performing the above open up macvim and edit a go file. 
For me it did syntax hilighting fine. Autocomplete worked well and go import ran on save. 

I did this on a mac machine. 

of course those are the bundle groups I use. You would want to adjust them for your usage... just make sure go is in there.

**Comment by bketelsen** [comment]
worked perfectly.  The thing you did that I didn't was the +qall.  I don't know what that does, but apparently it makes a difference.  Thanks for the help!

**Comment by spf13** [comment]
That’s just :quitall ..

I’m sure that didn’t make a difference, but glad it worked.
 
Best,
Steve

-- 
Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by bketelsen** [comment]
For future readers: the settings above a few comments work perfectly.  Thanks @spf13

**Comment by pyanfield** [comment]
it works.
Thanks @spf13

**Comment by chriskaukis** [comment]
I ran the above exactly, but got one error:

```
Installing github.com/golang/lint/golint
Error installing github.com/golang/lint/golint: 
```

Nothing more, no error actually shown. Next line just says to Press ENTER to continue.

I ran

```
go get github.com/golang/lint/golint
```

Without any errors.

**Comment by spf13** [comment]
Please file a ticket with the upstream go-vim package.

On Thursday, May 22, 2014, Christopher notifications@github.com wrote:

> I ran the above exactly, but got one error:
> 
> Installing github.com/golang/lint/golint
> Error installing github.com/golang/lint/golint:
> 
> Nothing more, no error actually shown. Next line just says to Press ENTER
> to continue.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/spf13/spf13-vim/issues/225#issuecomment-43965798
> .

## 

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by luan-cestari** [comment]
Hi guys! I also tried to enable go syntax and autocomplete but it isnt working. I tried twice to wipe all vim/spf13-vim configurations and make it from scratch (using https://github.com/spf13/spf13-vim/issues/225#issuecomment-43826297 ) but it isnt working for me (and no error messages installing or opening the files. Thank you guys in advance

**Comment by spf13** [comment]
is it properly highlighting the file? Is it running go fmt (or go import) on save? 

What do you expect to happen that isn't?

**Comment by luan-cestari** [comment]
It isn't highlighting and autocompleting (Sorry for not specifying in the very beginning). I'm using Fedora 20 x64 with vim-enhanced-7.4.179-1.fc20.x86_64 . Let me know if there is other useful information to we discover the root cause of this problem, I pasted the log with -V9 here https://gist.github.com/luan-cestari/56f4f5d418b679ab2e8e . Thank you very much for the help =)

**Comment by jefferai** [comment]
Also having the same troubles. I added "go" to the list of bundles and ran `vim +BundleInstall! +qall`. When it was done opened up a Go file. No syntax highlighting. It does other strange things too - it makes a line between many of my imports and one of the others, and when I try to add a new import and save it eats that line up.

**Comment by spf13** [comment]
That's the go import tool working as designed.  You probably just need to
clear out your vim views directory to get the highlighting to work.

On Friday, August 29, 2014, Jeff Mitchell notifications@github.com wrote:

> Also having the same troubles. I added "go" to the list of bundles and ran vim
> +BundleInstall! +qall. When it was done opened up a Go file. No syntax
> highlighting. It does other strange things too - it makes a line between
> many of my imports and one of the others, and when I try to add a new
> import and save it eats that line up.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spf13/spf13-vim/issues/225#issuecomment-53890411.

## 

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by jefferai** [comment]
@spf13 I assume by that you mean that it detected that the package wasn't used in the source yet and so ate it. Maybe it's by design, but it was unexpected as in the past (not with spf13-vim) it'd rearranged the imports alphabetically but not removed unused ones.

I will check on the views and see if I can make that work.

**Comment by luan-cestari** [comment]
Sorry, I forgot to try the last thing you mention. cleaning the views (rm -rf  ~/.vimviews/ ) and updating the plugins (vim +BundleInstall! +qall) solved the problem. Thank you very much for the help. (Sorry commenting in this closed issues, just wanted to someone that get a similar issue could try these things that can help)

**Comment by cars10w** [comment]
Yes, after applying spf13's recipe the deleting of ~/.vimviews was crucial. After that it worked like a charm. Thanks!

**Comment by leifmadsen** [comment]
Thanks all! Followed a couple of the other issues with Go syntax highlighting not working. The removal of the `.vimviews/` contents before running the BundleInstall is what resulting in happy fun times for me.

**Comment by cyberwave** [comment]
谢谢大家！Go语法突出显示不能正常工作，跟随其他几个问题。.vimviews/运行BundleInstall之前删除的内容是什么导致我快乐的乐趣时间。
--
that's work well, thanks

**Comment by cyberwave** [comment]
> @leifmadsen 
-----
thanks a lot , that's works well
