### ISSUE TITLE
Error while installing: E282: Cannot read from "$BASE_DIR/.vimrc.bundles"Vim: Reading from stdin

### ISSUE THREAD

**Issue by prongs** [spf13/spf13-vim#227]
This error comes on windows. see the screenshot [here](http://www.evernote.com/shard/s134/sh/b4ab9afd-d92e-4478-8ad9-eb9bdf64993b/ea53a843198951405c26ecba61e606b3). The git steps complete fine but the last step gives the error. Also, I think you need to change `$BASE_DIR` to `%BASE_DIR%`, that's how environment variables are read in windows. And I tried changing that, I still get an error(see screenshot [here](http://www.evernote.com/shard/s134/sh/7701f7bf-4bce-451d-a770-bdfff9c60960/5cc7994ef7aff50203eddb845aeb20b1)). There's no .`vimrc.bundles` in the directory 'C:\users\rajat.spf13-vim-3`. There's only a`.vim`directory there and the directory tree further is`.vim->bundle->vundle->a bunch of stuff`. See screenshot [here](http://www.evernote.com/shard/s134/sh/3daf963c-c48e-4d9a-b0af-e1d1ea60a034/8c1dc81a1048b9b2087794599bbb7382).

**Comment by spf13** [comment]
screenshots are very helpful? Is this XP or Windows 7?

**Comment by spf13** [comment]
Nevermind, I fixed it.  010d213d82e081f6261219265e7374efe07ec96a

**Comment by jhnwsk** [comment]
Yeap, sorry. My fault.
