### ISSUE TITLE
pressing tab with on windows writes <Plug>SuperTabForward to the buffer window

### ISSUE THREAD

**Issue by aalvarado** [spf13/spf13-vim#23]
On windows with gvim whenever on insert mode and pressing tab it writes <Plug>SuperTabForward

Any idea how I can fix this? 

Thanks :)

version 7.3 
ms-windows 32 bit gui version 
windows 7

**Comment by spf13** [comment]
It looks like it's not loading that plugin (SuperTab) properly. Did you update all the submodules?

**Comment by lzwaan** [comment]
for me it was working fine till now.
i did a fresh install but tab completion doesn't work, i get: omni completion ... Pattern not found
tried to update/sync but still it fails, doesn't matter if it is a python or html file????

btw i'm working on osx...just in case...

kind regards,

Lars

**Comment by aalvarado** [comment]
hmm I did update the submodels, I'm wondering if it has to do with something else, If i remove the 2 lines marked as super tab, I'm able to make it autocomplete. it crashes gvim after a few tabs, but i think it has to do more with ruby than the vim extension.

**Comment by spf13** [comment]
odd. It just seems like supertab isn't installed or working properly. I'll see if I can find anything. Just to be clear. It works fine on OSX, but not on Windows?

**Comment by aalvarado** [comment]
Hello Steve, I was finally able to get to a point of no erros :D. 

I was using vim 73, I think that's a big problem with command-t which i think it was the one causing the issues. 

I wasnt using the windows config folders, I did this: 

```
mklink .vimrc spf13-vim\.vimrc
mklink _vimrc spf13-vim\.vimrc
mklink /D .vim spf13-vim\.vim
mklink /D vimfiles spf13-vim\.vim
```

it seems to work. the only issue I had was on the transparency setting, which is a macvim only option, but everything else seems to be working except the snippets :< .

Thanks for the help
