### ISSUE TITLE
No such mapping Error with a.vim.

### ISSUE THREAD

**Issue by zhaolong** [spf13/spf13-vim#231]
a.vim works fine.
But i got a error "No such mapping" after excuting ":A".
Any idea?

**Comment by johntyree** [comment]
Should there be one? Can you post a link to some info or something? I'm not familiar with that plugin.

**Comment by zhaolong** [comment]
A.vim: Alternate Files quickly (.c --> .h etc).
http://www.vim.org/scripts/script.php?script_id=31

**Comment by bronzehedwick** [comment]
@zhaolong, is the issue still happening? I think this issue was created before Vundle was the plugin manager, and maybe that made a difference?

**Comment by ghost** [comment]
closing for lack of response. reopen if you can you can reproduce with latest spf13-vim
