### ISSUE TITLE
line number

### ISSUE THREAD

**Issue by husless** [spf13/spf13-vim#237]
Hi, everyone, how can I set in my .vimrc.local to make my vim show the real line number of a file , rather than the default, the current line(where the cursor is in) is always 0.
Also, i found that even i wrote 'set nonu' in my .vimrc.local, it would show the line number as well.

**Comment by XCMer** [comment]
Uninstall the "numbers" bundle to disable this feature. Then, you'll have real line numbers throughout as usual.

**Comment by husless** [comment]
thanks!!
