### ISSUE TITLE
autocomplete via <tab> doesn't work anymore after updating

### ISSUE THREAD

**Issue by lzwaan** [spf13/spf13-vim#24]
It was already a couple months ago since i updated my vimrc files.
So yesterday i tried on both the iMac and macbook, but now the autocompletion via 
snipmate on different filetypes doesn't work anymore.
I get a message:      -- Omni completion (^0^N^P) Pattern not found

I removed all the files and did a fresh install -> same issue

Can you please help me out, as always used your setup...

Kind regards,

lars

**Comment by spf13** [comment]
What file type are you editing when you are trying this? We recently resolved a snipmate issue (they added a dependency I wasn't aware of). Does this issue exist in the latest version?

**Comment by lzwaan** [comment]
i tried with html en python.
today removed all files and did a complete new install again via :
curl https://raw.github.com/spf13/spf13-vim/master/bootstrap.sh -o - | sh

but the problem is still there ( i'm working with osx)

**Comment by pvncad** [comment]
I am also facing same issue:  fresh installation with ViM 7.2 fileype C

I was editing C source file and tried pressing tab after typing in "main" in insert mode.  Then, I got the message in status line as " Omni completion (^O^N^P) Pattern not found"

**Comment by pvncad** [comment]
This is due to presence of extra snippets directory in the path to snippet files ./.vim/bundle/snipmate-snippets/**snippets**/snippets/c/for.snippet

Removed it and it worked like charm.

**Comment by fredrike** [comment]
Fix:
`git rm -r .vim/bundle/snipmate-snippets
git submodule add -f git://github.com/spf13/snipmate-snippets.git .vim/bundle/snipmate-snippets`

**Comment by sbucek** [comment]
THANK YOU fredrike!!!

**Comment by undassa** [comment]
same issue

**Comment by spf13** [comment]
this has been resolved in the latest branch.
