### ISSUE TITLE
vundle error in processing 

### ISSUE THREAD

**Issue by lactose** [spf13/spf13-vim#246]
on installing in OS X mountain lion (10.8.2) using zsh/oh-my-zsh shell

i get an error installing all of the vundle bundles. see here:
http://i.imgur.com/xx8yt.png

when i run the install on my ubuntu environment everything works perfectly.

any suggestions?

**Comment by spf13** [comment]
Could be a network error. Could be an issue with curl or wget which vundle
uses to pull it down.

It could be a filesystem access error.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by lactose** [comment]
unrelated then

**Comment by FuDesign2008** [comment]
I met this error too, for ~/.gitconfig had configs: 

 [push]  
     default = simple   

set default = matching is OK 
my git version is 1.8.0.2

**Comment by nostalgiaz** [comment]
@FuDesign2008 thanks!
