### ISSUE TITLE
Django templates double {{ }}

### ISSUE THREAD

**Issue by ivanrvpereira** [spf13/spf13-vim#248]
Can please someone please help me to remove the new line that autoclose plugin puts on second bracket?
This is really annoying behavior if you develop with Django or Jinja templating language.

Thanks

**Comment by spf13** [comment]
I've recently fixed this (last week). Please make sure your spf13-vim is
completely up to date. The new behavior is ideal for jinja.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by ivanrvpereira** [comment]
I updated and it's fixed. 
Many thanks.

**Comment by rafaponieman** [comment]
I've just rerun the installer and it is not fixed (curl http://j.mp/spf13-vim3 -L -o - | sh).

Any ideas? thanks!

**Comment by spf13** [comment]
Clear your cache (.vimviews)

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by rafaponieman** [comment]
I've deleted the .vimviews in my home (it was actually empty), with Vim closed, then opened it again and the issue is still there... I've tried using setfiletype html and setfiletype htmldjango

**Comment by spf13** [comment]
Can you manually confirm that you have the right bundles installed. Please
compare with the current list on github.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by bronzehedwick** [comment]
@rafadev, are you still having this issue?

**Comment by rafaponieman** [comment]
Hi @bronzehedwick ! At the time, I disabled autocompletion all the way, and haven't enabled it since. I've got my VIM running, its a bit outdated and I have no time to update it to the latest version so I wouldn't know...

**Comment by ghost** [comment]
reopen when you investigate again in the future.
