### ISSUE TITLE
XP errors opening py file

### ISSUE THREAD

**Issue by mrainess** [spf13/spf13-vim#249]
I did a fresh install; removing all dot and underscore vim and spf13 configuration files before starting. Using vim V 7.3.46. There were no errors during the install.

When I open a python file--using either vim or gvim--I get the following errors:

Error detected while processing function pymode#Option:
line    8:
E121: Undefined variable: g:pymode_syntax
E121: Undefined variable: g:pymode_options
E121: Undefined variable: g:pymode_doc
E121: Undefined variable: g:pymode_lint
E121: Undefined variable: g:pymode_rope
E121: Undefined variable: g:pymode_run
E121: Undefined variable: g:pymode_breakpoint
E121: Undefined variable: g:pymode_folding
Error detected while processing C:\Documents and Settings\Mark.vim\bundle\python-mode\after\ftplugin\python.vim:
line    2:
E121: Undefined variable: g:pymode_rope
E15: Invalid expression: g:pymode && g:pymode_rope && g:pymode_rope_vim_completion
Error detected while processing C:\Documents and Settings\Mark.vim\bundle\python-mode\after\indent\python.vim:
line    1:
E121: Undefined variable: g:pymode_indent
E15: Invalid expression: pymode#Default('b:pymode_indent', 1) || !g:pymode_indent
Error detected while processing function pymode#Option:
line    8:
E121: Undefined variable: g:pymode_syntax

**Comment by ghost** [comment]
@mrainess can you still reproduce this on a newer spf13-vim ?

**Comment by ghost** [comment]
closing for lack of information
