### ISSUE TITLE
Working directory keeps changing to current file

### ISSUE THREAD

**Issue by chrisnicola** [spf13/spf13-vim#251]
This behaviour makes using things like vimgrep quite difficult. Generally I expect the working directly to remain the root of the project where I opened VIm from or I set it myself with `cd`. Does anyone know why this is being done and if it can be switched off?

**Comment by chrisnicola** [comment]
Answered my own questions searching the `.vimrc`:

```
   let g:spf13_no_autochdir = 1
```

**Comment by chrisnicola** [comment]
OK this is no longer working. I've followed the directions and have that line in my .vimrc.bundles.local (btw that's an odd place to put settings I would have assumed .vimrc.local) and it is still changing directories.

**Comment by chrisnicola** [comment]
I've completely deleted the lines responsible for this behaviour from .vimrc but it's still happening so it must be a plugin. Strangely I don't appear to see anything in the :autocmd that would explain this. It's really annoying as I often use vimgrep and expect my working folder to be the root of my project.

**Comment by spf13** [comment]
Did you clear your views?

Steve Francia
spf13.com
@spf13

On Jun 12, 2013, at 6:23 PM, Chris Nicola notifications@github.com wrote:

I've completely deleted the lines responsible for this behaviour from
.vimrc but it's still happening so it must be a plugin. Strangely I don't
appear to see anything in the :autocmd that would explain this. It's really
annoying as I often use vimgrep and expect my working folder to be the root
of my project.

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/issues/251#issuecomment-19359743
.

**Comment by chrisnicola** [comment]
Clear my views? Sorry I don't know what that means and Google isn't helping either.

**Comment by spf13** [comment]
Vim caches state in "views". Look at $HOME/.vimviews

Steve Francia
spf13.com
@spf13

On Jun 12, 2013, at 6:37 PM, Chris Nicola notifications@github.com wrote:

Clear my views? Sorry I don't know what that means and Google isn't helping
either.

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/issues/251#issuecomment-19360322
.

**Comment by chrisnicola** [comment]
Ok so acting on a hunch I added `let g:spf13_no_views =1` to .vimrc.bundles.local and that seems to have fixed it. I'm not sure what code it's acting on is this an SPF13 specific plugin that is managing views. I don't see any code for it in the .vimrc other than that setting.

**Comment by rainkinz** [comment]
Had the same issue. Didn't work in ~/.vimrc.local, but does work in ~/.vimrc.bundles.local

**Comment by sbennett18** [comment]
I think the recommended place to put that command is in the `.vimrc.before.local`.  The `.vimrc.before` lists all the spf13 specific configuration options.

**Comment by rainkinz** [comment]
@sbennett18 thanks. That did the trick.

**Comment by bronzehedwick** [comment]
@chrisnicola, can this issue be closed?

**Comment by chrisnicola** [comment]
Yes. Thanks!
