### ISSUE TITLE
which is the best way to  disable a plugin?

### ISSUE THREAD

**Issue by scil** [spf13/spf13-vim#263]
i want to use delimitMate, not AutoClose,

which is the best way to disable AutoClose

**Comment by cotton-more** [comment]
I simply put "let g:override_spf13_bundles = 1" in .vimrc.bundle.local and then in the same file use only bundles that I need.

Also I think it's possible to use UnBundle in your .vimrc.local. In other words, put plugins you need in .vimrc.bundle.local and UnBundle all you do not want in .vimrc.local

**Comment by jamestomasino** [comment]
There is a much more direct method for disabling plugins that is now a part of spf13-vim. Here's a link to the full instructions: https://github.com/spf13/spf13-vim#removing-disabling-an-included-plugin

**Comment by jackywu** [comment]
@vansanblch Why 'override_spf13_bundles' did not appear in spf13-vim source code after searching ?
