### ISSUE TITLE
vim-powerline has been broken

### ISSUE THREAD

**Issue by pdehlke** [spf13/spf13-vim#267]
Lokaltog has decided to force people to stop using the vim-powerline plugin; it is now completely useless. See the glory of the latest revision:

https://github.com/Lokaltog/vim-powerline/blob/new-plugin/plugin/powerline.vim

Needless to say, this leaves new spf13 installs as of January 2 2013 broken.

_sigh_

**Comment by invernizzi** [comment]
## Solution

Install the new powerline dependencies

```
pip install https://github.com/Lokaltog/powerline/tarball/develop
wget https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf
wget https://github.com/Lokaltog/powerline/raw/develop/font/10-powerline-symbols.conf
mv PowerlineSymbols.otf ~/.fonts/
fc-cache -vf ~/.fonts
mkdir -p ~/.config/fontconfig/conf.d/
mv  10-powerline-symbols.conf ~/.config/fontconfig/conf.d/
```

Configure spf13

```
cat >> ~/.vimrc.local << EOF 
UnBundle 'Lokaltog/vim-powerline'                                               
 python from powerline.ext.vim import source_plugin; source_plugin()  
EOF

cat >> ~/.vimrc.bundles.local << EOF
Bundle 'Lokaltog/powerline'
EOF
```

run vim, and execute

```
:BundleClean!
:BundleInstall
```

**Comment by parrotbsd** [comment]
Appreciate the fix. That error message was driving me batty ;)

**Comment by Lokaltog** [comment]
Sorry about the mess, I didn't realize that other projects depended on the develop branch of vim-powerline. It has been marked as deprecated for some time now and it's recommended that users of vim-powerline migrate to the new project. Note that the old project is still available, but you have to explicitly checkout the develop branch as this is no longer the default branch.

**Comment by spf13** [comment]
I think I have a semi creative solution for this. I'm just going to create
a fork of the project from the dev branch and move the bundle to that.

I applaud his intent of moving to a single powerline to use across shell,
vim and other locations, it doesn't fit at all with our goals here of no
needless dependencies.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by Lokaltog** [comment]
That's too bad, but I can understand it if you don't want to have Python as a dependency.

**Comment by spf13** [comment]
I don't. However it's quite easy to use the python one if you decided to by
just unbundling this one and installing that separately.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by pdehlke** [comment]
It would be nice if vundle could be persuaded to check out a specific branch, but this issue: https://github.com/gmarik/vundle/issues/35 seems to have died on the vine, and I have been unable to persuade it to act the way it is alleged to act. 

You are in a twisty maze...

**Comment by kc-dot-io** [comment]
@spf13 can you point me in the direction of your "semi creative solution". This error is driving me nuts. I tried the solution above but pip failed to install the first command so I gave up.

**Comment by pdehlke** [comment]
You can use pdehlke/vim-powerline, which is a fork of the last working version of Lokaltog/vim-powerline, and will remain unchanged as long as github is around :)

**Comment by kc-dot-io** [comment]
Wonderful. Just what I was looking for @pdehlke thanks greatly.

**Comment by spf13** [comment]
That was part of my creative solution (which I haven't gotten to yet). Care
to make a pull request with this shift?

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by Lokaltog** [comment]
I don't understand the issue here. I switched the default branch back to develop a while ago, and I don't intend to try that again after the response I got. vim-powerline will remain as it is and I promise not to touch the repo again, so it should be perfectly fine to use it if you want to.

**Comment by kc-dot-io** [comment]
@Lokaltog Sorry, I didn't mean to stir up a bee's nest. The issue for me was that when I install spf13 on one of my computers it would throw an annoying error.

Here is the issue I opened with the vim-gitgutter guys: https://github.com/airblade/vim-gitgutter/issues/69 - It references another issue where the guy upgraded powerline to the newest version as there was some sort of conflict with your current HEAD. I was unable to accomplish the upgrade of powerline and my research lead me here. 

The solution I eventually came up with was to create my own fork: https://github.com/slajax/spf13-vim based on taxilian's fork which includes vim-powerline by default. 

I added the vim-gitgutter Bundle to the end of the "General" section and then everything was able to install properly. Possibly order matters? I have no idea to be honest. But it works. Hope that clarifies what might be happening to guys like me who are just trying to get everything working right.

If someone else comes across this issue and wants a quick fix, try my fork, noted above.

**Comment by kc-dot-io** [comment]
@spf13 - I will do some testing to see if I can get this working with the main bundles (rather then my bundles.fork) using the same strategy. I'll send  PR if successful.

**Comment by spf13** [comment]
Thanks Kyle. Appreciate the efforts.

An ideal solution would check for +python then for powerline and fall back
to installing vim-powerline if both conditions aren't met.

Steve Francia
spf13.com
@spf13

On Mar 28, 2013, at 11:49 AM, Kyle Campbell notifications@github.com
wrote:

@spf13 https://github.com/spf13 - I will do some testing to see if I can
get this working with the main bundles (rather then my bundles.fork) using
the same strategy. I'll send PR if successful.

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/issues/267#issuecomment-15596068
.

**Comment by bronzehedwick** [comment]
I think this issue has been resolved, no?

**Comment by pdehlke** [comment]
Indeed it has. Should have closed it ages ago.

**Comment by bronzehedwick** [comment]
Sweet, thanks.
