### ISSUE TITLE
auth error

### ISSUE THREAD

**Issue by FightingMan** [spf13/spf13-vim#270]
jason@FtMan ~/var/spf13-vim $ sh bootstrap.sh 
Thanks for installing spf13-vim
backing up current vim config
cloning spf13-vim
Cloning into '/home/jason/.spf13-vim-3'...
error: Recv failure: Connection reset by peer while accessing http://github.com/spf13/spf13-vim.git/info/refs
fatal: HTTP request failed
setting up symlinks
Installing Vundle
Cloning into '/home/jason/.vim/bundle/vundle'...
error: Recv failure: Connection reset by peer while accessing http://github.com/gmarik/vundle.git/info/refs
fatal: HTTP request failed
update/install plugins using Vundle
E282: Cannot read from "/home/jason/.spf13-vim-3/.vimrc.bundles"
Press ENTER or type command to continue

the same with:    curl http://j.mp/spf13-vim3 -L > spf13-vim.sh && sh spf13-vim.sh
Access to the webpage was denied
You are not authorized to access the webpage at https://github.com/gmarik/vundle.git/info/refs. You may need to sign in.

**Comment by spf13** [comment]
It works fine for me right now. Not sure if github had issues yesterday.
Let me know if it's still an issue.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by FightingMan** [comment]
I will test it when i go home, by the way how to copy context out in vim 
? insert is shift+insert and copy out? thx for your reply.

**Comment by spf13** [comment]
just use the regular y (yank) and x (remove). It will copy that value to
the system clipboard.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by FightingMan** [comment]
it doesn't, it won't copy that value to system clipboard. i'm your vim config loyal fans :)

**Comment by destinelin** [comment]
hello, spf13
I have recieved a same bug while runing 'bootstrap.sh'. Why?

**Comment by destinelin** [comment]
I have found a bug in 'bootstrap.sh',
In line 33, "https://github.com/spf13/spf13-vim.git" insteading of "http://github.com/spf13/spf13-vim.git"
