### ISSUE TITLE
Error with Cygwin

### ISSUE THREAD

**Issue by ltribolet** [spf13/spf13-vim#271]
Hi,

I tried to install it with Cygwin. I have an install of Cygwin with curl, vim and git. So far the line 

```
curl http://j.mp/spf13-vim3 -L -o - | sh
```

works great. The script gets correctly the files and everything.

But when I open a file with vim I've got the following errors :

``` bash
  $ vi test
  Error detected while processing /home/user/.vimrc :
  line   17 :
  E492: Command unknown: ^M
  line   19 :
  E492: Command unknown: ^M
  line   23 :
  E492: Command unknown: ^M
  line   27 :
  E15: Invalid expression : has('win32') || has('win64')^M
  line  669 :
  E171: :endif missing
  Press ENTER or type command to continue
```

Any ideas about that? I know that you're not saying you're not supporting Cygwin but if in any case you have a solution it would be awesome :)

Thanks,

Luc

**Comment by spf13** [comment]
Looks like an issue with a line ending character. Can you edit that script
to remove those characters and see if that fixes it?

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by ltribolet** [comment]
So I did it and I've got different errors :

``` bash
$ vim
Error detected while processing /home/user/.vimrc :
line    37 :
E117: Command unknown : vundle#rc
Error detected while processing /home/user/.vimrc.bundles :
line    36 :
E117: Command unknown : vundle#rc
line    43 :
E492: Command unknown:         Bundle 'gmarik/vundle'
line    44 :
E492: Command unknown:         Bundle 'MarcWeber/vim-addon-mw-utils'
line    45 :
E492: Command unknown:         Bundle 'tomtom/tlib_vim'
line    77 :
E492: Command unknown:         Bundle 'scrooloose/nerdtree'
Press ENTER or type command to continue
```

Any ideas?

To be clear I tried to remove it all and restart fresh, it still does that.

Thanks :)

**Comment by ltribolet** [comment]
Ok so I've found why it was doing that. It wasn't getting the repo for the bundles. I replaced the lines that were pointing to the repo by changing http protocol to git protocol. Apparently With Cygwin there is no libraries for git-http. Or I didn't find it.

But when it execute the recursive script in this git project to fetch all the bundles it fails everytime. Like this :

```
Error processing 'hail2u/vim-css3-syntax'
```

Do you have any ideas from where it could come from ?

Thanks :)

**Comment by spf13** [comment]
Vundle also uses http to install the bundles.
It doesn't look like it would be too difficult to patch. The two relevant
lines are:

https://github.com/gmarik/vundle/blob/master/autoload/vundle/scripts.vim#L53
https://github.com/gmarik/vundle/blob/master/autoload/vundle/scripts.vim#L156

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by ltribolet** [comment]
The thing is those links aren't necessarly git links.

Apparently I have the git-remote-http.exe but it doesn't work for some reasons.

So I did a workaround I fetch all datas from an ubuntu machine and then copy paste all files. It's kind of working now I have one or two plugins that aren't working. But it seems ok.

Thanks for your help anyway :)

I know this not really a solution.

**Comment by huxiao** [comment]
Maybe your cygwin is missing the package : libsasl2: The Cyrus SASL API implementation, resulting in failed to "git https://".

**Comment by ltribolet** [comment]
Yes it was missing but even with that the script that installing bundles is failing.
