### ISSUE TITLE
Neosnippet underlying code being exposed

### ISSUE THREAD

**Issue by tolusonaike** [spf13/spf13-vim#273]
I am not sure if this is a bug or normal behavior so i want to confirm

![Screen Shot 2013-01-25 at 12 14 36 PM](https://f.cloud.github.com/assets/253270/98276/fa1ac06e-671b-11e2-8f82-7d0a6044bf22.png)

It seems the underlying snippet code is being exposed.
![Screen Shot 2013-01-25 at 12 14 58 PM](https://f.cloud.github.com/assets/253270/98277/fa300988-671b-11e2-868e-1287e371b58f.png)

 If i place my cursor on the closing brace, it changes:
![Screen Shot 2013-01-25 at 12 25 56 PM](https://f.cloud.github.com/assets/253270/98301/d18150e0-671c-11e2-88b2-55584389eac2.png)

And when i put my cursor back to the foreach line, it exposes the code again.

**Comment by kernicPanel** [comment]
I have the same issue.

**Comment by bronzehedwick** [comment]
I do as well.

**Comment by tolusonaike** [comment]
I dont know if anybody else gets that weird ghosting as seen in image 2. Looks like a screen refresh problem too.

**Comment by bronzehedwick** [comment]
@tolusonaike, has this issue been resolved? I for one no longer experience it.

**Comment by tolusonaike** [comment]
Not sure, i use phpstorm now :-)

closing it anyway.
