### ISSUE TITLE
Unable to disable code folding

### ISSUE THREAD

**Issue by tolusonaike** [spf13/spf13-vim#274]
I am running the 3.0 release of spf13-vim

i have been unable to completely disable or initially disable code folding.

I added "set nofoldenable" in my vimrc.local file and deleted my vimviews folder but still no luck

**Comment by ghost** [comment]
I'm having a similar issue. I use :set foldlevel=100 when I open macvim and that works for a while before it automatically folds everything back again and sets the foldlevel to 0.

**Comment by spf13** [comment]
Must be a plugin overriding it. What filetype are you editing?

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by tolusonaike** [comment]
a .php file

**Comment by ghost** [comment]
I was viewing the .vimrc that comes with spf13, did the cmd :set foldlevel=100 and started scrolling. Few seconds later everything collapsed back and the foldlevel was set back to 0.

**Comment by pkmishra** [comment]
I am also facing the same issue.

**Comment by yapz** [comment]
Here is what worked for me:

I put the following in my .vimrc.local

```
set nofoldenable                " disable code folding
let g:DisableAutoPHPFolding = 1 " disable PIV's folding
```

and then deleted .vimviews directory in order to clear cache.

**Comment by trojjer** [comment]
Thanks for the tip yapz! Having to work around spf13 a lot now; wondering if I should stop fighting it and start from scratch again. Just removed Ctrl+P too. I tried Unite but it was still sluggish for me even with the vim-proc async plugin. For all that people bemoan its use of Ruby, I want my Command-T plugin back! Can't get it to work just yet with my custom Vim build though, unfortunately. A topic for another discussion...

**Comment by arindam89** [comment]
@yapz solution worked me. Thanks a lot :)

**Comment by ghost** [comment]
@tolusonaike 

is your problem solved now? if so, please close the issue.

**Comment by tolusonaike** [comment]
I solved the problem alright...i installed phpstorm :-)

**Comment by yangshiliang** [comment]
@yapz solution also worked for me. Thank you very much!
