### ISSUE TITLE
Selectively load vim-preview on the specific filetypes

### ISSUE THREAD

**Issue by barraponto** [spf13/spf13-vim#276]
Benchmarking spf13 led me to notice vim-preview is always loaded. This depends on https://github.com/greyblake/vim-preview/issues/31.

**Comment by bronzehedwick** [comment]
@barraponto, https://github.com/greyblake/vim-preview/issues/31 has been closed. Does that close this issue as well?

**Comment by ghost** [comment]
closing for lack of response. reopen if you can you can reproduce with latest spf13-vim
