### ISSUE TITLE
Automatic Installer does not currently work

### ISSUE THREAD

**Issue by txsl** [spf13/spf13-vim#282]
When I run

curl http://j.mp/spf13-vim3 -L > spf13-vim.sh && sh spf13-vim.sh

I get the error 

error: The requested URL returned error: 403 while accessing http://github.com/gmarik/vundle.git/info/refs

Trying to access that page from my browser, github does give me a 403. Weird seeing as the repo is public, and I can clone the entire repo. Not entirely sure where the problem is, but it is stopping me from installing spf-13 via the installation script :(

**Comment by spf13** [comment]
Can you try this again?

**Comment by crucialfelix** [comment]
I get the same thing. I have tried multiple times to install on one particular server.

I can't clone it manually either:

```
➜  bundle  git clone https://github.com/gmarik/vundle.git
Initialized empty Git repository in /home/crucial/.spf13-vim-3/.vim/bundle/vundle/.git/
error: The requested URL returned error: 403 while accessing https://github.com/gmarik/vundle.git/info/refs

fatal: HTTP request failed
```

**Comment by spf13** [comment]
This has cropped up a few times recently and always seems to resolve
itself. I think it's a github issue, but would be happy to address it if
not.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by gokulamurthy** [comment]
hey just update the resource_type from "https" to "git" in github clone url. i.e git://github.com/gmarik/vundle.git.

It works for me and hope it should work for you too!

Good luck

Gokul

**Comment by txsl** [comment]
I think it was a problem with git on my server. It worked elsewhere so I highly suspect that was the problem. Sorry for any hassle.

**Comment by crucialfelix** [comment]
the problem appears to still be in the installer script:

```
git clone --recursive -b $branch http://github.com/spf13/spf13-vim.git $endpath
```

these http links do not work on all systems.  

github runs https so its a redirect to the https URL. 

and in any case git:// would be a better method to use.
