### ISSUE TITLE
System register does not work

### ISSUE THREAD

**Issue by autra** [spf13/spf13-vim#283]
Hi

"+y does not work for me. It does not copy under system clipboard.
Neither do "*y or simpli y (as it is configured in the conf)
They are not even listed when I type :reg

Thank you, this is an amazing work apart from that!

**Comment by spf13** [comment]
Did you try just 'y'?

Steve Francia
spf13.com
@spf13

On Feb 1, 2013, at 10:06 AM, Augustin Trancart notifications@github.com
wrote:

Hi

"+y does not work for me. It does not copy under system clipboard.
Neither do "*y or simpli y (as it is configured in the conf)
They are not even listed when I type :reg

Thank you, this is an amazing work apart from that!

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/issues/283.

**Comment by spf13** [comment]
Also what environment are you running under?

Steve Francia
spf13.com
@spf13

On Feb 1, 2013, at 12:41 PM, Steve Francia steve.francia@gmail.com wrote:

Did you try just 'y'?

Steve Francia
spf13.com
@spf13

On Feb 1, 2013, at 10:06 AM, Augustin Trancart notifications@github.com
wrote:

Hi

"+y does not work for me. It does not copy under system clipboard.
Neither do "*y or simpli y (as it is configured in the conf)
They are not even listed when I type :reg

Thank you, this is an amazing work apart from that!

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/issues/283.

**Comment by autra** [comment]
Yes I tried y. 
I'm running Ubuntu 12.10.

**Comment by spf13** [comment]
Is this gvim, or console vim?

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

On Fri, Feb 1, 2013 at 12:54 PM, Augustin Trancart <notifications@github.com

**Comment by autra** [comment]
It is console vim version.

Here is the output of vim --version : 
    ~ » vim --version  
    VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Oct 26 2012 16:45:16)
    Included patches: 1-547
    Modified by pkg-vim-maintainers@lists.alioth.debian.org
    Compiled by buildd@
    Huge version without GUI.  Features included (+) or not (-):
    +arabic +autocmd -balloon_eval -browse ++builtin_terms +byte_offset +cindent 
    -clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
    +conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs 
    -dnd -ebcdic +emacs_tags +eval +ex_extra +extra_search +farsi +file_in_path 
    +find_in_path +float +folding -footer +fork() +gettext -hangul_input +iconv 
    +insert_expand +jumplist +keymap +langmap +libcall +linebreak +lispindent 
    +listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape 
    +mouse_dec +mouse_gpm -mouse_jsbterm +mouse_netterm -mouse_sysmouse 
    +mouse_xterm +mouse_urxvt +multi_byte +multi_lang -mzscheme +netbeans_intg 
    +path_extra -perl +persistent_undo +postscript +printer +profile +python 
    -python3 +quickfix +reltime +rightleft -ruby +scrollbind +signs +smartindent 
    -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary 
    +tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
     -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo 
    +vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
     -xterm_clipboard -xterm_save 
       system vimrc file: "$VIM/vimrc"
         user vimrc file: "$HOME/.vimrc"
          user exrc file: "$HOME/.exrc"
      fall-back for $VIM: "/usr/share/vim"
    Compilation: gcc-4.6 -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fstack-protector --param=ssp-buffer-size=4     -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  
    Linking: gcc-4.6   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim       -lm -ltinfo -lnsl  -lselinux      -lacl -lattr -lgpm -ldl     -L/usr/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic     -Wl,-O1 -Wl,-Bsymbolic-functions

**Comment by spf13** [comment]
Your build is missing support for it.

-xterm_clipboard

Steve Francia
spf13.com
@spf13

On Feb 4, 2013, at 9:03 AM, Augustin Trancart notifications@github.com
wrote:

It is console vim, version.

Here is the output of vim --version :
~ » vim --version

VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Oct 26 2012 16:45:16)
Included patches: 1-547
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version without GUI. Features included (+) or not (-):
+arabic +autocmd -balloon_eval -browse ++builtin_terms +byte_offset
+cindent
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info
+comments
+conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff
+digraphs
-dnd -ebcdic +emacs_tags +eval +ex_extra +extra_search +farsi +file_in_path
+find_in_path +float +folding -footer +fork() +gettext -hangul_input +iconv
+insert_expand +jumplist +keymap +langmap +libcall +linebreak +lispindent
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape
+mouse_dec +mouse_gpm -mouse_jsbterm +mouse_netterm -mouse_sysmouse
+mouse_xterm +mouse_urxvt +multi_byte +multi_lang -mzscheme +netbeans_intg
+path_extra -perl +persistent_undo +postscript +printer +profile +python
-python3 +quickfix +reltime +rightleft -ruby +scrollbind +signs
+smartindent
-sniff +startuptime +statusline -sun_workshop +syntax +tag_binary
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects
+title
-toolbar +user_commands +vertsplit +virtualedit +visual +visualextra
+viminfo
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim
-xsmp
-xterm_clipboard -xterm_save
system vimrc file: "$VIM/vimrc"
user vimrc file: "$HOME/.vimrc"
user exrc file: "$HOME/.exrc"
fall-back for $VIM: "/usr/share/vim"
Compilation: gcc-4.6 -c -I. -Iproto -DHAVE_CONFIG_H -g -O2
-fstack-protector --param=ssp-buffer-size=4 -Wformat
-Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1

Linking: gcc-4.6 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o
vim -lm -ltinfo -lnsl -lselinux -lacl -lattr -lgpm -ldl
-L/usr/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker
-export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/issues/283#issuecomment-13078076.

**Comment by autra** [comment]
Cool, thanks a lot, it is working now.

And I learnt that Ubuntu doesn't come with the full version of vim by default. You have to install vim (the default is vim-tiny), but this is not enough and I also had to install vim-gtk.

**Comment by davidheijkamp** [comment]
For those running Fedora / Red Hat kind of distro's install vim-X11. See also http://vim.wikia.com/wiki/Accessing_the_system_clipboard
