### ISSUE TITLE
Disable transparency?

### ISSUE THREAD

**Issue by panosru** [spf13/spf13-vim#284]
Hello, this is really cool vimrc! How could I disable transparency? I use iTerm on OSX and I already have set transparency in iterm window so when I run vim it is hard to see light colors :/

**Comment by bronzehedwick** [comment]
If you set transparency in iTerm, that sets it globally for your terminal; vim can't effect that. You would have to disable transparency across the board in iTerm to effectively disable transparency in vim.

**Comment by panosru** [comment]
@bronzehedwick you missunderstood me, what I say is that when I run vim the whole environment is too light, as a result for instance I can't see comments in code.

This is my [normal iterm window](http://o7.no/Wmvqy1) this is [when I run vim](http://o7.no/WTByPC) and I have a bright window behind iterm and this is [when I run vim](http://o7.no/Wmwfad) and have dark window behind iterm

**Comment by bronzehedwick** [comment]
That's just the colorscheme; the comments are in gray, which are harder to see when the window is transparent.

**Comment by panosru** [comment]
I have the feel that when I run vim the background befome even more transparent though...

**Comment by bronzehedwick** [comment]
That's not possible.

**Comment by panosru** [comment]
Well, indeed is not possible, but what I notice is that vim sets #373737 background color, all I need is to set that to #000, I guess if I change 'set background dark' to 'set background #000000' it could work?

**Comment by bronzehedwick** [comment]
The vim background property doesn't actually set a color, but sets the general guidelines for the colors; there are two options, dark and light, so depending on your colorscheme you change the background property to dark or light. spf-13 sets background to dark by default. This link http://stackoverflow.com/questions/1117526/specifying-the-vim-background-colour explains in a little more detail.

**Comment by panosru** [comment]
Thanks for the link! 

From what I see spf-13 load it's color scheme from here: `.vim/bundle/vim-colors-solarized/colors/solarized.vim` since it is a bundle I think it is better to not override that file directly but instead I should make my changes inside `.vimrc` file right?

In order to change vim background color could you guide me on where in `" Vim UI {` section I should make my modification? 

Thanks a lot in advance!

**Comment by bronzehedwick** [comment]
You make your changes in `.vimrc.local`. The spf-13 documentation details all of this https://github.com/spf13/spf13-vim#customization

**Comment by panosru** [comment]
Ok I added the `ir_black` as the documentation proposed and I think I prefer that colorscheme :)

Thanks!

**Comment by bronzehedwick** [comment]
No problem, that's my colorscheme of choice as well :)

**Comment by panosru** [comment]
:)

**Comment by dlukes** [comment]
> I have the feel that when I run vim the background befome even more transparent though...

It's not more transparent (that's indeed impossible), but since it's lighter than the background when Vim is not running AND transparent at the same time, the contrast becomes too low for comfortable reading.

Another option which I just found out about (after playing around with the solution proposed in this thread) is to just disable the transparency of the terminal whenever a background color is set. In iTerm2, check *Keep background colors opaque* on the *Window* tab of your profile preferences.

This makes Vim sessions non-transparent, which some people (including me) might find preferable, and transparency resumes when you get back to the command prompt :)

**Comment by KrishKayc** [comment]
> > I have the feel that when I run vim the background befome even more transparent though...
> 
> It's not more transparent (that's indeed impossible), but since it's lighter than the background when Vim is not running AND transparent at the same time, the contrast becomes too low for comfortable reading.
> 
> Another option which I just found out about (after playing around with the solution proposed in this thread) is to just disable the transparency of the terminal whenever a background color is set. In iTerm2, check _Keep background colors opaque_ on the _Window_ tab of your profile preferences.
> 
> This makes Vim sessions non-transparent, which some people (including me) might find preferable, and transparency resumes when you get back to the command prompt :)

keep background colors opque worked for me !! Thanks..
