### ISSUE TITLE
Unable to deactivate relative line numbers

### ISSUE THREAD

**Issue by Taluu** [spf13/spf13-vim#288]
Hi,

I tried multiple ways to deactivate the relative line numbers. Last one I tried was : `set norelativenumber`. I also tried to set relativenumber to `0`, but nothing changed.

It works on my .vimrc.local .vimrc files, but on the other files (including my *.php files), it is still the same thing : I have the relative line numbers. I also tried to uninstall the `myusuf3/numbers.vim` bundle, but to no avail...

I really think this should not be enabled per default, or easily removable (specially for vim noobs like me)...

Thanks.

**Comment by spf13** [comment]
I'll work on making this easier.

Steve Francia
spf13.com
@spf13

On Feb 6, 2013, at 10:37 AM, "Baptiste Clavié" notifications@github.com
wrote:

Hi,

I tried multiple ways to deactivate the relative line numbers. Last one I
tried was : set norelativenumber. I also tried to set relativenumber to 0,
but nothing changed.

It works on my .vim files, but on my .php files, it is still the same thing
: I have the relative line numbers. I also tried to uninstall the
myusuf3/numbers.vim bundle, but to no avail...

I really think this should not be enabled per default, or easily removable
(specially for vim noobs like me)...

Thanks.

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/issues/288.

**Comment by RobertinoValue** [comment]
Someone (Jeff Kreeftmeijer) mapped Ctrl+n to switch between absolute and relative numbers with a function named NumberToggle. And also to automatically switch to absolute line numbers whenever Vim loses focus. : [Relative line numbers in Vim for super-fast movement](http://jeffkreeftmeijer.com/2012/relative-line-numbers-in-vim-for-super-fast-movement/)
He turned it into a plugin : https://github.com/jeffkreeftmeijer/vim-numbertoggle
Maybe this helps the OP to hang on to both absolute and relative.

**Comment by jamestomasino** [comment]
I believe numbers.vim [just had an update](https://github.com/myusuf3/numbers.vim/pull/26) where they added some global enable/disable functionality. This may help solve your issue.

**Comment by Taluu** [comment]
I left with my own .vimrc, greatly inspired by @spf13's one, but heh, that's still a really good news. So yeah, this should solve the issue :)

(Closing it then)
