### ISSUE TITLE
Installation error: E282: Cannot read from .spf13-vim-3/.vimrc.bundles"

### ISSUE THREAD

**Issue by klinquist** [spf13/spf13-vim#291]
Ubuntu 12.10,

Running:
curl -k http://j.mp/spf13-vim3 -L > spf13-vim.sh && sh spf13-vim.sh

Error E282: Cannot read from "/home/xxx/.spf13-vim-3/.vimrc.bundles"

**Comment by klinquist** [comment]
Nevermind - git was not installed :)

**Comment by tacit7** [comment]
Do you want food

From my Android phone on T-Mobile. The first nationwide 4G network.

-------- Original message --------
