### ISSUE TITLE
Gray lines

### ISSUE THREAD

**Issue by Staudi** [spf13/spf13-vim#295]
![Screen Shot 2013-02-10 at 5 56 30 AM](https://f.cloud.github.com/assets/713654/142925/6be5f74e-733e-11e2-83b0-c9aaa0dcb895.png)

Any idea why I'm getting these gray lines every fifth space ? Thanks.

**Comment by jcbwlkr** [comment]
Do you mean the vertical gray bar connecting your <aside> tags? I believe this is from the plugin 'nathanaelkane/vim-indent-guides' You could unbundle it in your vimrc.local if you don't want them.

**Comment by Staudi** [comment]
Yep solved its vim-indent-guides, you can toggle them with `<leader>ig` Thanks!

**Comment by jcbwlkr** [comment]
Great! I'm glad it worked for you. I didn't realize that behavior could be toggled. I think I might bundle it back in on my own system.
