### ISSUE TITLE
With # - *- coding: utf8 -*- at the top, file is not interpreted as Python

### ISSUE THREAD

**Issue by phacops** [spf13/spf13-vim#297]
I have # - _\- coding: utf8 -_\- on the first line of my Python script and it seems SPF13 doesn't set what's need to have completion and color syntax for it.

I'm using the latest revision and  my file's extension is .py.

Edit:
It seems deleting the file view cache in ~/.vimviews did the trick.

Edit 2:
Actually, after a while, it comes back to not being interpreted as a Python file.

**Comment by bronzehedwick** [comment]
I am not able to replicate this issue. @phacops, is it still happening for you?

**Comment by ghost** [comment]
closing for lack of response. reopen if you can you can reproduce with latest spf13-vim
