### ISSUE TITLE
Problem with autochdir

### ISSUE THREAD

**Issue by davisein** [spf13/spf13-vim#302]
In https://github.com/spf13/spf13-vim/blob/3.0/.vimrc#L85 it specifies that adding 
`let g:spf13_no_autochdir = 1`
to my .vimrc.bundles.local will avoid vim to change directory but it is not working...

Am I doing something wrong? Can somebody check if it is working?

**Comment by spf13** [comment]
You can't put it in your .vimrc.local because that file is read after the
if statement. You could put it in your .vimrc.local.bundles file which is
read earlier.. that's not super clean, but it will work well.

I'm thinking of a better way of doing this sort of thing in the future.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by davisein** [comment]
I 've already put that line in `.vimrc.bundles.local` with no effect.

You mention .vimrc.local.bundles. Is it different or a typo?

Is there anything I can do to diagnose what's the problem? The code in .vimrc seems clear and I cannot figure why it's not working...

**Comment by spf13** [comment]
it was a typo.

Try clearing your swap files.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by davisein** [comment]
I assume that you mean erasing all .vimswap/\* files. I did it and didn't work :(

**Comment by nublic** [comment]
Ok, I found in an old post in your blog that you mention other files to clean and I clean them. I am not sure which one did the trick but I erased: `.viminfo, .vimview/* .vim/view/* .vimswap/* .vim/sessions/*.`

I guess the `.vim/sessions/*` wasn't needed but I only had there an old session.

Now this is working fine. You can close the bug (I can't).

I hope this is helpful for other people who doesn't know how to clean vim's caches. Too much to learn ;)

**Comment by chebert** [comment]
I was having the problem of InitializeDirectories() changing my pwd in vim. I commented out the line
exec "set " . settingname . "=" . directory
(currently line 623)

and it stopped changing the directory.

**Comment by chebert** [comment]
^ Which I find changes the undo directory and the backup directory to the directory of the file -__-

**Comment by davisein** [comment]
For me it worked removing this files
`.viminfo, .vimview/* .vim/view/* .vimswap/*`

After adding `let g:spf13_no_autochdir = 1` to `.vimrc.bundles.local`. You need to restart vim.

**Comment by chebert** [comment]
Wonderful that worked. Thanks for the tip!

**Comment by jazmit** [comment]
Great, this has been annoying me since I switched to spf13!!

**Comment by bchretien** [comment]
:+1:

**Comment by anasiati** [comment]
This solution still works as of today (04/21/15). 

Created `~/.vim.bundles.local` and added `let g:spf13_no_autochdir = 1`. 
Then blew away `~/.vimswap` and `~/.vimviews` and restartd vim.

**Comment by horahh** [comment]
this worked! thanks

**Comment by HouCoder** [comment]
Thanks for your comment, but the correct configuration file name is **~/.vimrc.bundles.local** NOT **~/.vim.bundles.local**.

@anasiati
