### ISSUE TITLE
Vim saving configurations for opened files?

### ISSUE THREAD

**Issue by vqng** [spf13/spf13-vim#304]
Hmm, I don't know how to describe this problem but my Vim opens .vimrc.local with no color:

![Screenshot from 2013-02-23 18:58:46](https://f.cloud.github.com/assets/2427629/187947/ff7e630a-7da8-11e2-8dfc-fc35b286cbc8.png)

It worked right after I installed spf13, then I tried saving/loading a vim session and eventually ran into the above problem. I tried to close vim and re-open that vimrc.local file, and the issue still persists.
The strange thing is Vim displays other files with proper syntax highlighting.

**Comment by spf13** [comment]
Delete your swap file.

Steve Francia
spf13.com
@spf13

On Feb 23, 2013, at 6:08 AM, Navie Huynh notifications@github.com wrote:

Hmm, I don't know how to describe this problem but my Vim opens
.vimrc.local with no color:

[image: Screenshot from 2013-02-23
18:58:46]https://f.cloud.github.com/assets/2427629/187947/ff7e630a-7da8-11e2-8dfc-fc35b286cbc8.png

It worked right after I installed spf13, then I tried saving/loading a vim
session and eventually ran into the above problem. I tried to close vim and
re-open that vimrc.local file, and the issue still persists.
The strange thing is Vim displays other files with proper syntax
highlighting.

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/issues/304.

**Comment by vqng** [comment]
I deleted all files under ~/.vimswap but it doesn't help

**Comment by vqng** [comment]
I even tried starting with -n option. This behavior is strange and I thought it was a desired feature in spf13. 

For e.g.: if I type ":set nospell" when vimrc.local is opened and quit vim, there is no spell check in vimrc.local the next time I open Vim but in other files, spell errors are still highlighted.

I am not sure if this is related to spf13. Let me try to seek for helps from other vim users.

**Comment by spf13** [comment]
This is all part courtesy of vim views . Clear out the views directory.

Steve Francia
spf13.com
@spf13

On Feb 25, 2013, at 12:13 AM, Navie Huynh notifications@github.com wrote:

I even tried starting with -n option. This behavior is strange and I
thought it was a desired feature in spf13.

For e.g.: if I type ":set nospell" when vimrc.local is opened and quit vim,
there is no spell check in vimrc.local the next time I open Vim but in
other files, spell errors are still highlighted.

I am not sure if this is related to spf13. Let me try to seek for helps
from other vim users.

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/issues/304#issuecomment-14026156.

**Comment by vqng** [comment]
Thanks. I deleted all files in vimview and vimbackup and it worked.
