### ISSUE TITLE
nospell in local conf

### ISSUE THREAD

**Issue by omares** [spf13/spf13-vim#305]
Setting `set nospell` in  my `.vimrc.local` has no effect on the spelling correction. It seems the `.vimrc` file is loaded after the local one?

**Comment by jcbwlkr** [comment]
vimrc calls `set spell` around line 96 and the `.vimrc.local` is sourced in around like 650. It could be a problem with the saved views for specific files. Delete everything under `~/.vimviews/` and see if that makes a difference.

**Comment by omares** [comment]
`21:02:25 ~ ❯ rm -rf ~/.vimviews/*` - No change :(

**Comment by omares** [comment]
DUH, you should not use the .vimrc file as example to test your changes.
It seems the used commands in the file overwrite the ones you specify.

**Comment by jcbwlkr** [comment]
ah, yes. There is a vim modeline at the top of that file which specifies file specific settings

`" vim: set sw=4 ts=4 sts=4 et tw=78 foldmarker={,} foldlevel=0 foldmethod=marker spell:`

**Comment by wdjwxh** [comment]
Thank you! jacobwalker0814..

**Comment by jcbwlkr** [comment]
Glad to help wdjwxh :)

**Comment by ghost** [comment]
seems like it was all figured out. I'm closing it. If you still have problems, then please open up another issue.
