### ISSUE TITLE
BufExplorer?

### ISSUE THREAD

**Issue by nedludd** [spf13/spf13-vim#306]
The .vimrc includes lines calling "BufExplorer" but it does not seem to be installed.  

```
" Buffer explorer {
     nmap <leader>b :BufExplorer<CR>
" }
```

(lines 392-394)

I had to install the bundle 'corntrace/bufexplorer' to get it.

**Comment by johntyree** [comment]
Not sure why it's there, but I personally vote to keep it out. It was having serious issues and I had to remove it from my setup. It was constantly having trouble numbering buffers correctly, causing bizarre errors that would ruin whatever you were trying to do. Especially when switching between buffers.

**Comment by spf13** [comment]
It's there because I missed taking it out. My experience echo's John's.
It's a lot of trouble that I could never seem to sort out.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by bronzehedwick** [comment]
@nedludd, looks like this has been removed. Is this issue safe to close?

**Comment by nedludd** [comment]
Yup, no worries

**Comment by bronzehedwick** [comment]
Cool, would you mind closing it? :)

**Comment by ghost** [comment]
@bronzehedwick : if it seems that we're waiting for info add the "needinfo" label. Although this seems closable now as BufExplorer code does seem to be gone from the codebase
