### ISSUE TITLE
snipmate error on launch

### ISSUE THREAD

**Issue by gmoulin** [spf13/spf13-vim#31]
Error detected while processing ~/.vim/bundle/snipmate.vim/plugin/snipMate.vim: 
line   31: 
E117: Unknown function: funcref#Function 
E116: Invalid arguments for function get(s:snipMate, 'get_snippets', funcref#Function("snipMate#GetSnippets")) 
E15: Invalid expression: get(s:snipMate, 'get_snippets', funcref#Function("snipMate#GetSnippets"))

vim 7.3 on ubuntu 11.04
i have this plugins :

checksyntax_vim
commant-t
delimitMate
FindFile
nerdtree
PIV
snipmate-snippets
snipmate.vim
supertab
vim-files
vim-fugitive
vim-git
vim-markdown

**Comment by spf13** [comment]
This has been resolved in the latest branch.
