### ISSUE TITLE
% matching bracket issue

### ISSUE THREAD

**Issue by ethanjonn** [spf13/spf13-vim#311]
% only works once. It finds the closing braces and it stops working. Press again and nothing happens. It works for every file for one time only.

spf13-vim latest version. no edits no local config. OS X 10.8.2 . Tried in both MacVim and console vim and found same bug

**Comment by bronzehedwick** [comment]
+1

**Comment by barraponto** [comment]
Works fine in Archlinux's (g)Vim  7.3.798-1.

**Comment by ethanjonn** [comment]
i just noticed that it works fine for html tags. i can jump from and back between html opening and closing tags.

**Comment by spf13** [comment]
We had a fix go in recently (a couple weeks ago) related to this.. perhaps
you just need to update?

Just re-run the install script to update to the latest.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by ethanjonn** [comment]
Thanks Steve. Thats solves the issue :)
