### ISSUE TITLE
Infinite loop due to gitgutter

### ISSUE THREAD

**Issue by mathieuroche** [spf13/spf13-vim#315]
Hi,

On Windows Seven 64 bits, I have a problem due to gitgutter.
Gvim is blinking because there is infinite loop:

Exécution de Autocommandes FocusGained pour "_"
Appuyez sur ENTRÉE ou tapez une commande pour continuer
autocommande :call Center()
Appuyez sur ENTRÉE ou tapez une commande pour continuer
Exécution de Autocommandes FocusGained pour "_"
Appuyez sur ENTRÉE ou tapez une commande pour continuer
autocommande call GitGutter()
Appuyez sur ENTRÉE ou tapez une commande pour continuer
Appel du shell pour exécuter : "cd "C:\Users\ME" && git rev-parse > /dev/nul
l 2>&1 >C:\Users\ME\AppData\Local\Temp\VIo8A9F.tmp 2>&1"
Appuyez sur ENTRÉE ou tapez une commande pour continuer
Exécution de Autocommandes FocusGained pour "_"
Appuyez sur ENTRÉE ou tapez une commande pour continuer
autocommande :call Center()
Appuyez sur ENTRÉE ou tapez une commande pour continuer
Exécution de Autocommandes FocusGained pour "_"
Appuyez sur ENTRÉE ou tapez une commande pour continuer
autocommande call GitGutter()
Appuyez sur ENTRÉE ou tapez une commande pour continuer
Appel du shell pour exécuter : "cd "C:\Users\ME" && git rev-parse > /dev/nul
l 2>&1 >C:\Users\ME\AppData\Local\Temp\VIoAAAE.tmp 2>&1"  
...

Any ideas ?

Currently, I added "let g:gitgutter_enabled = 0" in my .vimrc.local.

Thanks.

Here some informations about my vim:
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Oct 27 2010 17:51:38)
Version console MS-Windows 32 bits
Rustines incluses : 1-46
CompilÚ par Bram@KIBAALE
Grosse version sans interface graphique.
  FonctionnalitÚs incluses (+) ou non (-) :
+arabic +autocmd -balloon_eval -browse ++builtin_terms +byte_offset +cindent
+clientserver +clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments
+conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs
-dnd -ebcdic +emacs_tags +eval +ex_extra +extra_search +farsi +file_in_path
+find_in_path +float +folding -footer +gettext/dyn -hangul_input +iconv/dyn
+insert_expand +jumplist +keymap +langmap +libcall +linebreak +lispindent
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape
+multi_byte +multi_lang -mzscheme -netbeans_intg -osfiletype +path_extra -perl
+persistent_undo -postscript +printer -profile -python -python3 +quickfix
+reltime +rightleft -ruby +scrollbind +signs +smartindent -sniff +startuptime
+statusline -sun_workshop +syntax +tag_binary +tag_old_static -tag_any_white
-tcl -tgetent -termresponse +textobjects +title -toolbar +user_commands
+vertsplit +virtualedit +visual +visualextra +viminfo +vreplace +wildignore
+wildmenu +windows +writebackup -xfontset -xim -xterm_save -xpm_w32
         fichier vimrc systÞme : "$VIM\vimrc"
     fichier vimrc utilisateur : "$HOME_vimrc"
 2me fichier vimrc utilisateur : "$VIM_vimrc"
      fichier exrc utilisateur : "$HOME_exrc"
  2me fichier exrc utilisateur : "$VIM_exrc"
Compilation : cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32   -DFEAT_CSC
OPE       -DWINVER=0x0400 -D_WIN32_WINNT=0x0400  /Fo.\ObjC/ /Ox /GL -DNDEBUG  /Z
l /MT -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_BIG /Fd.\ObjC/ /Zi
+dition de liens : link /RELEASE /nologo /subsystem:console /LTCG:STATUS oldname
s.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uu
id.lib /machine:i386 /nodefaultlib  libcmt.lib   user32.lib             /PDB:vim
.pdb -debug

**Comment by spf13** [comment]
I've tested it on mac and it works well for me. Maybe git-gutter doesn't support windows. Perhaps it's a known bug in git-gutter? I'd check with them on this one as it doesn't seem to be a spf13-vim specific issue.

**Comment by mathieuroche** [comment]
Ok. Thank for your feeback. I'm new to spf13. 
I have no issue on my Debian.
I have not seen any issue on the git-gutter github.

**Comment by ghost** [comment]
@mathieuroche : is this still a problem for you with new versions of spf13-vim? If not, please close the issue

**Comment by mathieuroche** [comment]
I'll check asap. Currently, I'm on Debian ;)

2014-06-22 10:52 GMT+02:00 Johnny Robeson notifications@github.com:

**Comment by bronzehedwick** [comment]
@mathieuroche, were you able to check?

**Comment by mathieuroche** [comment]
It's seems to be ok now. Sorry for the delay.
Maybe https://github.com/spf13/spf13-vim/pull/489 has solved the issue.
Thanks.
