### ISSUE TITLE
:color need to reset two times for recover to normal

### ISSUE THREAD

**Issue by micfan** [spf13/spf13-vim#316]
Excuse me, when I installed it on xubuntu or xLinuxMint, I have to type :color blue first, then type :color solarized to make the current line's color of inputing recover to normail, did someone has the same problem? I used Guake terminal with Vim. Thanks.

**Comment by jcromero** [comment]
Yes, I have the same problem in my debian systems.

**Comment by bronzehedwick** [comment]
@micfan, is this still an issue for you?

**Comment by ghost** [comment]
i wonder if it is fixed now that csapprox has been removed. marking as needinfo label

**Comment by ghost** [comment]
closing for lack of response
