### ISSUE TITLE
how to paste in the vim?

### ISSUE THREAD

**Issue by lixiphp** [spf13/spf13-vim#319]
Hello All, I am new to use the spf13-vim editor.

Before I use mouse right click to paste the copy code to VI, but when I install spf13-vim to the server, I can't use the mouse right click to paste at SSH dialog.

Please told me how to paste the code. is there a tutorial of spf13-vim?

![vim_right_click_to_visual](https://f.cloud.github.com/assets/465228/266603/4e5afb78-8e16-11e2-81bc-08b86e768e2a.jpg)

**Comment by Crawleyprint** [comment]
Have you tried `:set paste`? It enters in paste mode where you can use (usually) middle click or ctrl/cmd-v to insert text from clipboard. After that, you must invoke `:set nopaste` in order to switch back to normal mode and continue working. 

On the other hand, are you sure that your ssh client (putty) allows copy/paste? This one is just a guess, as I've never used PuTTY before.

**Comment by lixiphp** [comment]
Thanks your quickly response. I solve the problem from this link: http://www.webhostingtalk.com/showthread.php?t=102976

Before:
Using puTTY I always just do this:
copy - highlight the text
paste - right click

Now:
control-insert = copy
shift-insert = paste

**Comment by decebal** [comment]
You only need to press P. I don't think this counts as a mouse support bug,
but it should work too, only when you are in edit mode.

2013/3/16 lixi notifications@github.com

> Hello All, I am new to use the spf13-vim editor.
> 
> Before I use mouse right click to paste the copy code to VI, but when I
> install spf13-vim to the server, I can't use the mouse right click to paste
> at SSH dialog.
> 
> Please told me how to paste the code. is there a tutorial of spf13-vim?
> 
> [image: vim_right_click_to_visual]https://f.cloud.github.com/assets/465228/266603/4e5afb78-8e16-11e2-81bc-08b86e768e2a.jpg
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/spf13/spf13-vim/issues/319
> .

_Decebal Dobrica_\* *_PHP WebDeveloper (E-commerce Product Engineer)_

## 

http://about.me/decebal4art

decebal1988@gmail.com | decebal_1988@gmx.com
[image: Facebook] http://www.facebook.com/decebal4art [image:
Twitter]http://www.twitter.com/decebal4art [image:
LinkedIn] http://ro.linkedin.com/pub/decebal-dobrica/1a/393/856
Contact me: [image: Skype] decebal.dobrica [image: Y! Messenger] decebal1988
 Create your free signature:
http://r1.wisestamp.com/r/landing?promo=33&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_33
CLICK
HERE!http://r1.wisestamp.com/r/landing?promo=33&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_33
