### ISSUE TITLE
Can't enter Q in search 

### ISSUE THREAD

**Issue by s4uliu5** [spf13/spf13-vim#32]
Hi,

while in search mode (/) entered capital letter "Q" automatically changes to lowercase "q".

I'm using (g)Vim version 7.2.330 with spf13-vim-641c91f on Ubuntu 10.10.

**Comment by has2k1** [comment]
You may want to comment out this section in the .vimrc.

``` vim
    " Stupid shift key fixes
    "cmap W w
    "cmap WQ wq
    "cmap wQ wq
    "cmap Q q
    "cmap Tabe tabe
```

or unmap them if you are using ~/vimrc.local.

**Comment by s4uliu5** [comment]
Thanks! It worked :)
