### ISSUE TITLE
any change in .vimrc or .vimrc.local doesn't work

### ISSUE THREAD

**Issue by ghost** [spf13/spf13-vim#329]
At first I want to change colorscheme using  "echo colorscheme ir_black  >> ~/.vimrc.local",
it doesn't work then I change it in .vimrc,doesn't work neither.

I try to run "source .vimrc", I got this error
"vimrc:1: command not found:  Modeline and Notes {\n
.vimrc:3: command not found: \n
.vimrc:694: unmatched 
"
I don't know how to solve this,anyone can help?

OH,except line 124 the color part, I didn't change anything else.

**Comment by spf13** [comment]
The error comes from bad characters in your .vimrc file. Please edit it and
remove them. Looks like some things were commented out and no longer are.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by ghost** [comment]
I commit this issue.
thx for reply.
I remove all of them and reinstall it,then source .vimrc still got that error.
I add "autocmd! bufwritepost .vimrc source ~/.vimrc" in .vimrc.local and it works.

**Comment by bronzehedwick** [comment]
@johntyree, looks like the original commenter both had the issue fixed, and deleted his github account. I think it's probably safe to close this.
