### ISSUE TITLE
how to make nerdtree-tabs work in spf13?

### ISSUE THREAD

**Issue by ghost** [spf13/spf13-vim#330]
I prefer to have a file list on the left all the time like normal IDEs,so I tried to make nerdtree work since I open a file,I found nerdtree-tabs.
I add some lines by its README,but there some odd errors like
" function <SNR>50_VimEnterHandler..<SNR>50_NERDTreeOpenAllTabs..<SNR>50_NERDTreeMirrorOrCreate..217..218..nerdtree#echo..Pl#Statusline"

I don't know how to make this work,what should I do?

**Comment by Gaelan** [comment]
spf13-vim comes with NERDTreeTabs. You shouldn't have to install it yourself.

**Comment by bronzehedwick** [comment]
@johntyree, looks like another issue that can be closed, due to the original poster deleting their github account.

**Comment by ghost** [comment]
thanks. closing.
