### ISSUE TITLE
"honza/snipmate-snippets" ask for username/passwod when updating with bundle

### ISSUE THREAD

**Issue by ghost** [spf13/spf13-vim#331]
It seems it git clone this project via https:// url not git.

**Comment by benvds** [comment]
It's also deprecate and became:
Bundle 'honza/vim-snippets'

for now:
UnBundle 'honza/snipmate-snippets' in your .vimrc.local

**Comment by spf13** [comment]
Wanna give me a pull request to the new location?

**Comment by jcbwlkr** [comment]
Has this already been resolved?

**Comment by benvds** [comment]
Yes, in:
https://github.com/spf13/spf13-vim/pull/333
and
https://github.com/spf13/spf13-vim/pull/335

**Comment by ghost** [comment]
@spf13 : you can close this now it seems
