### ISSUE TITLE
Add in new Color Schemes

### ISSUE THREAD

**Issue by allenwyma** [spf13/spf13-vim#334]
Is there a way to add in color schemes that aren't bundled with spf13? There's a railscast.vim color scheme included, but it has an error and I found some other variations online that I'd like to try in the mean time.

How do I add in new color schemes not included in spf13?

**Comment by ghost** [comment]
may be you can put your color-name.vim into 
.spf13-vim-3/.vim/bundle/vim-colorschemes/colors .spf13-vim-3 should be 
your directory,and add colorscheme color-name in .vimrc.local

在 2013年04月6，上午 5:01，Allen Wyma notifications@github.com 
写道：

**Comment by allenwyma** [comment]
OKay, that worked out for me, what I did was just use a symlink. I dont' want to pollute this respository. There's gotta be another way to add in custom colors instead of this.

**Comment by spf13** [comment]
Make a bundle. Put it on github. Add to your local bundles file.

If you think everyone would benefit from it, put in bundles and make a pull
request.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by bronzehedwick** [comment]
@HangingClowns, is the issue resolved? If so please close this issue :)

**Comment by ghost** [comment]
marking as needinfo for now. we'll check back in a bit.

**Comment by allenwyma** [comment]
I haven't tried. I moved on from spf13. Maybe others can use this as a reference. Thanks.
