### ISSUE TITLE
Cursor position is being recalled after closing and opening a file

### ISSUE THREAD

**Issue by chrisnicola** [spf13/spf13-vim#341]
Seems that the last file mark is being returned to upon load. This isn't a big deal but I don't know how to turn it off and it's really annoying when I'm writing git commit messages as it goes to wherever my last message ended instead of being at the start.

**Comment by jcbwlkr** [comment]
I've noticed that as well. I love that feature for everything except commit
messages >.<

On Thu, Apr 11, 2013 at 5:08 PM, Chris Nicola notifications@github.comwrote:

> Seems that the last file mark is being returned to upon load. This isn't a
> big deal but I don't know how to turn it off and it's really annoying when
> I'm writing git commit messages as it goes to wherever my last message
> ended instead of being at the start.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/spf13/spf13-vim/issues/341
> .

## 

Jacob Walker
Tortugas Consulting LLC
316-461-1127

**Comment by jaywilliams** [comment]
Same here.

**Comment by spf13** [comment]
The feature is on purpose, by taking advantage of vim's view functionality.
It may be possible to disable for git commit messages. I use fugitive for
this so I don't really experience what you are talking about.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by chrisnicola** [comment]
Git from the command line is pretty dependent on VIm, it would be nice to have a fix for this. It's minor, but still annoying. Is there a way to disable this feature entirely?

**Comment by keelerm84** [comment]
Not quite sure why Github is showing 3 commits referencing this issue here when the actual pull request only has one, but I believe this should address the issue.  My apologies for the clutter.

**Comment by bronzehedwick** [comment]
@chrisnicola, is this issue resolved?

**Comment by chrisnicola** [comment]
Seems to be for me. Thanks.
