### ISSUE TITLE
splash while editing something in folding place

### ISSUE THREAD

**Issue by ghost** [spf13/spf13-vim#346]
I try to add "set nospell" to the vim UI part,when I input 'se',there is a completion list for me,and there is splash.and these code will be folded again,I need to go back to normal mode and use 'zo' again.
This happens randomly,why?

**Comment by bronzehedwick** [comment]
@johntyree, this can probably be closed, since the user has deleted their github account.

**Comment by ghost** [comment]
@bronzehedwick : ping me, since he doesn't seem to be around.

**Comment by bronzehedwick** [comment]
OK, will do. Thanks.
