### ISSUE TITLE
Missing characters

### ISSUE THREAD

**Issue by CodisRedding** [spf13/spf13-vim#347]
Missing characters when I start vim 
![vim-missing-chars](http://i.imgur.com/0PYL66l.png)

**Comment by kew-l** [comment]
It looks like this is related to the new python based powerline. This started for me as well after that package change. I am using a powerline patched font and it worked fine in vim-powerline that was used before.

**Comment by flowerornament** [comment]
Turns out you need to use a patched font: https://github.com/Lokaltog/powerline-fonts or patch your own.

**Comment by mgoffin** [comment]
I'm using the patched fonts (Droid Sans Mono for Powerline specifically) and my powerline looks like this after updating to the latest 3.0:

Â NORMALÂ î°Â î Â masterÂ î°Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â unixÂ î²Â 100%Â î²Â î¡Â Â Â 1:1Â Â %Â î²Â î¡Â Â Â 1Â

**Comment by bronzehedwick** [comment]
I am using the power line patched inconsolata font, which works, but only if I set it during my vim session. For some reason it's not reading it from vimrc. 

Also when I start up vim I get a laundry list of power line related errors. I'll see if I can copy them. 
—

**Comment by bronzehedwick** [comment]
This is the error I get on startup.

```
Error detected while processing function Powerline:
line    3:
2013-04-22 09:48:49,316:ERROR:vim:modified_indicator:Exception while computing segment: modified_indicator()                 keywords must be strings
Press ENTER or type command to continue
Error detected while processing function Powerline:
line    3:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function Powerline:
line    3:
  File "/Users/cdeluca/.spf13-vim-3/.vim/bundle/powerline/powerline/theme.py", line 89, in get_segments
Press ENTER or type command to continue
Error detected while processing function Powerline:
line    3:
    contents = segment['contents_func'](pl=self.pl, segment_info=segment_info, **segment['args'])
Press ENTER or type command to continue
Error detected while processing function Powerline:
line    3:
TypeError: modified_indicator() keywords must be strings
Press ENTER or type command to continue
Error detected while processing function Powerline:
line    3:
2013-04-22 09:48:55,325:ERROR:vim:line_percent:Exception while computing segment: line_percent() keywords must be strings
Press ENTER or type command to continue
Error detected while processing function Powerline:
line    3:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function Powerline:
line    3:
  File "/Users/cdeluca/.spf13-vim-3/.vim/bundle/powerline/powerline/theme.py", line 89, in get_segments
Press ENTER or type command to continue
Error detected while processing function Powerline:
line    3:
    contents = segment['contents_func'](pl=self.pl, segment_info=segment_info, **segment['args'])
Press ENTER or type command to continue
Error detected while processing function Powerline:
line    3:
TypeError: line_percent() keywords must be strings
Press ENTER or type command to continue
```

**Comment by mgoffin** [comment]
As a temporary fix for me, I did the following:
- copied https://github.com/ashwin/vim-powerline into ~/.vim/bundle

Since I'm already using a patched font, and I have these two settings in my .vimrc.local already:

`let g:Powerline_symbols = 'fancy'`
`set t_Co=256`

it cleared up the problem.

**Comment by bronzehedwick** [comment]
I believe this problem has been fixed. @fourq, is that correct?

**Comment by CodisRedding** [comment]
@bronzehedwick I've since moved to a brand new machine and haven't had this issue. I couldn't say that whether or not it was an issue still after updates on that machine. Close it?

**Comment by flowerornament** [comment]
I, for one, no longer need to use a patched font.

**Comment by bronzehedwick** [comment]
@fourq, thanks!
