### ISSUE TITLE
GitGutter Errors while processing gitgutter.vim  on Ubuntu 12.04

### ISSUE THREAD

**Issue by loque1** [spf13/spf13-vim#348]
Error detected while processing .spf13-vim-3/.vim/bundle/vim-gitgutter/plugin/gitgutter.vim:
line  436:
E174: Command already exists: add ! to replace itNo protocol specified
No protocol specified

**Comment by wmayner** [comment]
+1 for this.

GitGutter doesn't seem mature enough yet to include in a great distribution like this one. In addition to this problem, I found that after installing it, tabs took about a second to load. Removing GitGutter fixed the problem entirely.

**Comment by spf13** [comment]
I believe they have resolved this on their end. Please reopen if issue persists.
