### ISSUE TITLE
Error while opening file

### ISSUE THREAD

**Issue by qiuwei** [spf13/spf13-vim#351]
Got error:

```
Error detected while processing VimEnter Auto command for "*&"
E117: Unknown function: Pl#Statusline
```

**Comment by bronzehedwick** [comment]
+1
—

**Comment by johntyree** [comment]
I also get this error, but only the first time a particular file is opened. Also this error doesn't actually seem to cause any problems.

If I open a file and get this error then close Vim and reopen the file, it does not produce the error.

Curiously, the `autoload/` directory doesn't even exist and grepping my entire `~/.vim` directory for `Pl#` turned up nothing. I have no idea where this is coming from.

**Comment by cotton-more** [comment]
I came across with that error after I removed Powerline-plugin.

```
E117: Unknown function: Pl#Statusline
E15: Invalid expression: Pl#Statusline(0,0)
```

**Comment by johntyree** [comment]
@vansanblch Yes, that is indeed the error I get. Do you get it _every_ time you open a file, or just the first time?

**Comment by qiuwei** [comment]
@vansanblch  I just get it at the first time.

**Comment by johntyree** [comment]
@qiuwei same here. Odd indeed. Maybe related to vim-views or something? What else is persistent?

**Comment by qiuwei** [comment]
@johntyree  I guess it's related to the update of powerline to vim-powerline.
Check out the latest commits, someone already provided a patch which makes it possible to revert to earlier version.

**Comment by johntyree** [comment]
Yes indeed that's true. I'm not terribly upset about the new version,
though. It's actually pretty rare that I open a file that I've never opened
before apparently.

2013/5/2 Wei Qiu notifications@github.com

**Comment by cotton-more** [comment]
@johntyree I think this problem have something to do with restore_view plugin. I used to use Powerline and then remove it. Now, when I try to open file that I already opened with Powerline installed I get that message. If I create new file everything works fine. So, I think the problem is in restore_view.

**Comment by armw4** [comment]
Experiencing the same issue when opening files via NERDTree. Happens the first time then goes away. Really annoying.

**Comment by mnichols** [comment]
When upgrading you might need to delete the .vimviews and/or .vimswap directories. Wiping these out fixed this for me:
ie
`rm -rf ~/.vimviews`

**Comment by hackhowtofaq** [comment]
@mnichols 

Thanx! That fixed the problem.
