### ISSUE TITLE
Some words are highlighted?

### ISSUE THREAD

**Issue by trantorLiu** [spf13/spf13-vim#354]
I am using `color molokai`. I don't know why some (key)words are highlighted. The highlight color is the background color of **solarized**. Here's the screenshot:

![screenshot](http://www.csie.ntu.edu.tw/~b98902109/Screenshot-44.png)

**Comment by bronzehedwick** [comment]
I'm pretty sure that's spelling errors being highlighted. Try setting set nospell to test. 
—

**Comment by trantorLiu** [comment]
You are right. Thank you so much.
For people looking for the answer, you can also take a look on issue #305.
