### ISSUE TITLE
UnBundle function improvement?

### ISSUE THREAD

**Issue by warpcode** [spf13/spf13-vim#357]
Hi, the one thing I've found fairly annoying lately is that I need to manually run bundle clean to remove bundles i've set with UnBundle(). Everytime I update my config using the bootstrap.sh, it always pulls down the bundles I don't want and then I have to manually run bundle clean again.

What I propose is that we move the unbundle function into the vimrc.bundles file. Then, using an array in the vimrc.bundles.local (or .fork) we can set which bundles to unload. This array would then be iterated through at the end of the vimrc.bundles.

This would not only stop the need to run bundle clean after each update but it also won't even git clone the bundle in the first place thereby saving some install time as well.

**Comment by teasp00n** [comment]
You don't need to run bootstrap.h to update the configuration. You can just pull the latest changes from the repo using `cd ~/.spf13-vim-3` and `git pull` followed by `vim +BundleInstall! +BundleClean`

**Comment by warpcode** [comment]
Posted this over a year ago (stopped using spf13 at the time due to so many issues) and since then the unbundle command is now in the bundles file which solves the problem I had in this issue.
