### ISSUE TITLE
Yanking(yy) and pasting(p) not work as expected

### ISSUE THREAD

**Issue by trantorLiu** [spf13/spf13-vim#359]
I use `yy` and `p` to copy-pasting a line. They work well withing a same file (that is, the line will be add to the next line of the current cursor position). However, if I `yy` on file1, **<c-w><left>** to file2, then `p`, the line copied will be pasted right after to the current cursor position.

**Comment by MattWoelk** [comment]
This is an ongoing problem as of today (13 June, 2013; fresh update) for the following setup:
- both gvim and vim in a terminal on Linux Mint 13

This issue is a problem for two files opened as a split view, as tabs, or in the same buffer.

**Comment by MattWoelk** [comment]
This is no longer a problem on my machines as of August 30th, 2013.

**Comment by barraponto** [comment]
I am also affected :poop:

**Comment by johntyree** [comment]
Those affected, what is the output of `:verb omap y` and `:verb xmap y`?

**Comment by barraponto** [comment]
No mapping found (for both commands).

**Comment by bronzehedwick** [comment]
I had this problem on OS X, but was able to fix by adding this line to my `.tmux.conf`.

```
set-option -g default-command "reattach-to-user-namespace -l zsh"
```

Change `zsh` to your shell.

**Comment by 9Y5** [comment]
#560 worked for me. It's to do with the `clipboard` variable.

But instead of commenting out lines in the `.vimrc` file, I added

```
set clipboard=
```

to the `~/.vimrc.local` file.

**Comment by barraponto** [comment]
The above fix worked for me.

**Comment by spf13** [comment]
spf13-vim tries to do the best it can to set the clipboard to the right settings. See the following link for all the potential issues with clipboards.
http://vim.wikia.com/wiki/Accessing_the_system_clipboard

There are too many factors outside of Vim for us to properly guess right on all accounts.

**Comment by ghost** [comment]
added this to the FAQ
