### ISSUE TITLE
Ins/Del/PgUp/PgDown/Home/End keybindings are broken

### ISSUE THREAD

**Issue by jherazob** [spf13/spf13-vim#36]
If you press PageUp or PageDown, instead of going up or down a page it changes the case of the character under the cursor.

I checked the vimrc just in case it was voluntarily disabled, but couldn't find any signs of that. If this is expected or intentional it would be good to tell the user and give a way to revert to the default if possible.

Edit: It's not just PageUp and Down, it's all of that block of keys, updated issue title to clarify

**Comment by spf13** [comment]
Often this is due to terminal settings. What terminal are you using?

Also sometimes it's due to a bad vim install. Are you using Ubuntu? They cripple their version of vim.

**Comment by jherazob** [comment]
Yes, i'm using Ubuntu, and just figured out that most of the keyboard problems happen with the terminal version of Vim, with GVim working more or less fine.

If the version in Debian is not crippled (do you know? i have no idea) i could install that one instead, the packages should be compatible. Either that or get the Ubuntu vim source package, uncripple it (what do they do to my vim?) and generate new packages that'd work fine. Will look at this in the weekend and if i do find a fix or workaround i'll post it.

**Comment by correl** [comment]
I was having this problem in Ubuntu when running vim in the terminal as well, I got around it by putting `set term=$TERM` into my .vimrc.local ($TERM == xterm)

**Comment by jherazob** [comment]
Yes, That seems to work well, thanks! :)
It'd be a good idea to add something about this somewhere on the main .vimrc, as i bet i'm not the only one with Ubuntu, but this workaround seems to do the trick

**Comment by ggsonic** [comment]
thank you so much ! works for me.
