### ISSUE TITLE
DIsable auto popup autocomplete

### ISSUE THREAD

**Issue by naps62** [spf13/spf13-vim#360]
I find the default behaviour for autocomplete to be rather anoying in this distribution. I usually move around text using the arrow keys while in Insert mode. This makes the completion list popup a lot while i don't want it. Due to this, vertical navigation is hard, since when the popup appears, i can no longer move up/down until i close it.

Is there a setting for this that i missed? How can i turn of this behavious and make the popup only appear using a keyboard shortcut? I tried searching through the `.vimrc` file couldn't find out how to do it.

**Comment by spf13** [comment]
It's the auto pop up feature of neocomplcache. You can just disable that by
setting g:neocomplcache_disable_auto_complete

More details available in the docs...
https://github.com/Shougo/neocomplcache/blob/master/doc/neocomplcache.txt

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by naps62** [comment]
ok that did it. my bad for missing it. thanks
