### ISSUE TITLE
Status Line Layout Is Broken

### ISSUE THREAD

**Issue by armw4** [spf13/spf13-vim#368]
My status line doesn't clearly display the way it used to. Is this due to a high resolution? OS is Mountain Lion with Thunderbolt Display.

![screen shot 2013-05-20 at 10 32 53 pm](https://f.cloud.github.com/assets/246377/539632/0f658050-c1bf-11e2-9d61-3c3a2708ec2d.png)

**Comment by armw4** [comment]
Not sure if MacVim is the culprit, or the actual script itself.

**Comment by pfitz** [comment]
Had this too - fixed it with using special patched fonts for the terminal. You can find them here https://github.com/Lokaltog/powerline-fonts

**Comment by armw4** [comment]
@pfitz That does ring a bell. Let me try that out. Thanks a million.

**Comment by armw4** [comment]
@pfitz Man...thanks a lot! That did it :+1: 

You can see the broken one just below the one containing the patched font...

![screen shot 2013-05-21 at 10 40 12 pm](https://f.cloud.github.com/assets/246377/546246/0028b952-c289-11e2-8712-3ef939dd862d.png)
