### ISSUE TITLE
UnBundle: 'Not an editor command: UnBundle'

### ISSUE THREAD

**Issue by LkeMitchll** [spf13/spf13-vim#369]
I'm trying to disable a bundle with the 'UnBundle' syntax provided by spf-13.

But when I start vim I get the following error:

``` Shell
Error detected while processing /Users/luke/.vimrc.local:
line   22:
E492: Not an editor command: UnBundle 'Shougo/neocomplcache-snippets-complete'
Press ENTER or type command to continue
```

I followed the commands correctly and the line 'UnBundle 'Shougo/neocomplcache-snippets-complete' as you can see is in .vimrc.local. So I'm not sure if it's user error or an issue.

The reason i'm disabling 'neocomplcache-snippets-complete' is because it's now deprecated and alerts every time I start vim.

I'm running:

Mac OS 10.8.3
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled May 21 2013 10:49:19)
MacOS X (unix) version
Included patches: 1-976
[installed via Homebrew]

**Comment by spf13** [comment]
Need to put it in .vimrc.bundles.local

Steve Francia
spf13.com
@spf13

On May 22, 2013, at 4:49 AM, LkeMitchll notifications@github.com wrote:

I'm trying to disable a bundle with the 'UnBundle' syntax provided by
spf-13.

But when I start vim I get the following error:

Error detected while processing /Users/luke/.vimrc.local:
line   22:
E492: Not an editor command: UnBundle 'Shougo/neocomplcache-snippets-complete'
Press ENTER or type command to continue

I followed the commands correctly and the line 'UnBundle
'Shougo/neocomplcache-snippets-complete' as you can see is in .vimrc.local.
So I'm not sure if it's user error or an issue.

The reason i'm disabling 'neocomplcache-snippets-complete' is because it's
now deprecated and alerts every time I start vim.

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/issues/369
.

**Comment by LkeMitchll** [comment]
@spf13 Sorry, I still have the issue after putting the line into `.vimrc.bundles.local`

``` Shell
Error detected while processing /Users/luke/.vimrc.bundles.local:
line    5:
E492: Not an editor command: UnBundle 'Shougo/neocomplcache-snippets-complete'
E492: Not an editor command: UnBundle 'Shougo/neocomplcache-snippets-complete'
This is old version of neocomplcache-snippets-complete.
This is no longer maintained.
You should use neosnippet plugin instead of it.
https://github.com/Shougo/neosnippet
Press ENTER or type command to continue
```

I've tried running `:BundleClean!` and it doesn't seem to work.

P.S I've created a pull request to correct the documentation #371

**Comment by spf13** [comment]
I'm sorry. I responded from memory from my phone and was totally wrong this.. it needs to be in .vimrc.local. 

Can you paste your .vimrc.local?

Also can you upgrade to the latest spf13-vim to make sure the function exists?

**Comment by LkeMitchll** [comment]
@spf13 Ok, sorry about the confusion.

Here's my `~/.vimrc.local`

```
"Theme"
color Tomorrow-Night-Bright

"Guifont"
:set guifont=Source\ Code\ Pro:h14

"Syntax"
au BufRead,BufNewFile *.pde,*.ino set filetype=arduino

"Disable spelling highlights"
set nospell

"Zen Coding"
let g:user_zen_expandabbr_key = '<c-a>' 
let g:use_zen_complete_tag = 1

"Easy split navigation"
" Use ctrl-[hjkl] to select the active split!
nmap <silent> <c-k> :wincmd k<CR>
nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-l> :wincmd l<CR>

"Line Numbers - relative/absolute switch"
function! NumberToggle()
  if(&relativenumber == 1)
    set number
  else
    set relativenumber
  endif
endfunc

nnoremap <C-l> :call NumberToggle()<cr>

"Debundles"
UnBundle 'Shougo/neocomplcache-snippets-complete'
```

Yes, I update a few times just to check I wasn't out-of-date.

**Comment by LkeMitchll** [comment]
@spf13 This message still persists after manually commenting out the problem package from .vimrc the command `UnBundle` is still not recognised. For now manual uninstall (without using `UnBundle`) is my only option.

Why is `Shougo/neocomplcache-snippets-complete` still being used? even the developer has stated that the bundle is no longer maintained or required. (https://github.com/Shougo/neocomplcache-snippets-complete)

**Comment by spf13** [comment]
I definitely don't think you have the latest files.

https://github.com/spf13/spf13-vim/blob/3.0/.vimrc.bundles#L132

As you can see in that link, it was updated months ago to the newer repository.

**Comment by LkeMitchll** [comment]
Thanks, bizarrely I could only get this to work with a full manual reinstallation, the update script wouldn't work. I'm sure it's something i've messed up on my system.

Thanks for the help!
