### ISSUE TITLE
Vim: Error reading input, exiting...

### ISSUE THREAD

**Issue by jherazob** [spf13/spf13-vim#37]
When double-clicking a text file in Ubuntu (both 10.10 and 11.04), it tries to run vim and fails. When looking at .xsession-errors, there's that message. The documentation of that error (from http://vimdoc.sourceforge.net/htmldoc/message.html ) says:

> "This occurs when Vim cannot read typed characters while input is required. Vim got stuck, the only thing it can do is exit.  This can happen when both stdin and stderr are redirected and executing a script that doesn't exit Vim."

Looking for the mime type files, i see that the command line used to open the file is "gvim -f filename". It works on a terminal, but fails on the GUI.

**Comment by punknroll** [comment]
Same error here using ubuntu 11.04. Any hints on this?

**Comment by punknroll** [comment]
i found out that there is a problem with the ~/.vimrc file...but can't figure it out yet.

**Comment by punknroll** [comment]
in ~/.vimrc comment out

   " if !has('win32') && !has('win64')
   "     set term=$TERM       " Make arrow and other keys work
   " endif

Then gvim starts. I have to figure out why this setting was used but it works for me at the moment.

**Comment by jherazob** [comment]
Nope, doesn't work here. Commented out every reference to win32 or win64 and nothing happened. It's also curious that it has that term command there, i had to add it manually to vimrc.local because the arrow and other keys _weren't_ working, so it probably isn't even working (otherwise i wouldn't have had to add it)

**Comment by punknroll** [comment]
does gvim start, when you completly remove ~/.vimrc?

**Comment by jherazob** [comment]
Yep, it does.

**Comment by punknroll** [comment]
Well i tried to narrow the error in my ~/.vimrc using
if 0

endif 
around half the code of the file so you know in which half the error resides and so on...

**Comment by spf13** [comment]
Is this still happening? A lot has changed for the 3.0 branch (now default branch).

**Comment by jherazob** [comment]
Yes, still happening. Awesome changes in the new version by the way, but it still shows that error, which means it can't be called from the GUI or be used as default editor on X, at least on Ubuntu :(

**Comment by spf13** [comment]
Can anyone confirm this is an issue still. If yes, then reopen.
