### ISSUE TITLE
Segfault on vim open

### ISSUE THREAD

**Issue by rehelmin** [spf13/spf13-vim#372]
I immediately get a segfault whenever I try to open a file in vim. 

OS: Fedora 17 3.8.12-100.fc17.x86_64
VIM: 2:7.3.682-1.fc17
latest git commit id: 46d23621ed373bb8e876ad916a9ffcafb99f7b38

I will try to pinpoint the plugin that is causing the issues, but this could take a while. Does anyone have any idea how I could pinpoint the problem a little quicker? I'm proficient using gdb. I just don't know where to start looking.

**Comment by spf13** [comment]
What if You open it without a file? Does file type matter?

Steve Francia
spf13.com
@spf13

On May 22, 2013, at 7:01 PM, rehelmin notifications@github.com wrote:

I immediately get a segfault whenever I try to open a file in vim.

OS: Fedora 17 3.8.12-100.fc17.x86_64
VIM: 2:7.3.682-1.fc17
git commit id: 46d2362https://github.com/spf13/spf13-vim/commit/46d23621ed373bb8e876ad916a9ffcafb99f7b38

I will try to pinpoint the plugin that is causing the issues, but this
could take a while. Does anyone have any idea how I could pinpoint the
problem a little quicker? I'm proficient using gdb. I just don't know where
to start looking.

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/issues/372
.

**Comment by rehelmin** [comment]
It doesn't matter if I pass vim a file or not, I get the same behavior.

**Comment by spf13** [comment]
Can you try gvim?

Steve Francia
spf13.com
@spf13

On May 22, 2013, at 7:37 PM, rehelmin notifications@github.com wrote:

It doesn't matter if I pass vim a file or not, I get the same behavior.

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/issues/372#issuecomment-18315094
.

**Comment by rehelmin** [comment]
Same behavior. I tried looking at a GDB backtrace to find out where it was segfaulting, but it was unhelpful to the untrained eye.

**Comment by rehelmin** [comment]
After updating VIM it looks like everything is working now.
