### ISSUE TITLE
potential old powerline issue

### ISSUE THREAD

**Issue by gzmask** [spf13/spf13-vim#373]
When I customize my bundles to exclude python, spf13 turns powserline into an elder version. I got couple unknown function: powerline... errors when vim starting up.

**Comment by fly2xj** [comment]
powerline goes wrong when i updated spf13 under OS X

**Comment by phcostabh** [comment]
Same here!

**Comment by chrisnicola** [comment]
I'm not sure the new Powerline works very well with Vundle. I have it installed using PIP and have had to remove it from `.vimrc.bundles` because of these problems.

**Comment by jordanthornquest** [comment]
The new Powerline runs on Python, so excluding it will cause it to revert the old VimScript version.

**Comment by teasp00n** [comment]
Empty out your .vimviews directory. If you aren't bundling it anymore then you'll get errors when the cached buffer state is loaded.

**Comment by kalupa** [comment]
Is it possible that this is related?

https://powerline.readthedocs.org/en/latest/installation/osx.html#installation-osx

**Comment by spf13** [comment]
We've switched to airline instead which doesn't depend on python at all and provides most of the same functionality.
