### ISSUE TITLE
can't use command + c for copy in  mac

### ISSUE THREAD

**Issue by pcleon** [spf13/spf13-vim#378]
hi, when i use the spf13 for my vim
my mac can't use command + c for copy any more , please help ^_^

**Comment by pcleon** [comment]
hi, i just tried to find the reason why , then i found when use  touch pad to select the words , it automatically change into visual mode , in this mode i can't use cmd+c for copying , how can i set vim not auto change into visual mode when i use the pad to select words

**Comment by sbennett18** [comment]
Try pressing the shift key while selecting the text to copy.

**Comment by pcleon** [comment]
thanks for your answer, but it's not work #_#, when i press the shif key, then it not allow me to choice any word .  although i try to use  shift+cmd+c , but not work too

**Comment by spf13** [comment]
are you using macvim or console vim?

**Comment by msmart** [comment]
Try pressing the left alt key while selecting.

I've added 

```
vmap <C-x> :!pbcopy<CR>  
vmap <C-c> :w !pbcopy<CR><CR> 
```

to my vimrc.local to cut and copy to my OS X clipboard in terminal mode.

**Comment by bronzehedwick** [comment]
@pcleon, is this issue resolved?

**Comment by pcleon** [comment]
it's resolved with your advise ,thanks a lot ! ^_^~

------------------ 原始邮件 ------------------
发件人: "Chris DeLuca"notifications@github.com; 
发送时间: 2014年8月18日(星期一) 晚上10:04
收件人: "spf13/spf13-vim"spf13-vim@noreply.github.com; 
抄送: "死兔子"wpctszz@qq.com; 
主题: Re: [spf13-vim] can't use command + c for copy in  mac (#378)

@pcleon, is this issue resolved?

**Comment by bronzehedwick** [comment]
Cool, would you mind closing this issue?
