### ISSUE TITLE
Fugitive mysterious appended line

### ISSUE THREAD

**Issue by jordanthornquest** [spf13/spf13-vim#395]
Did a fresh install of spf13-vim, and using Fugitive commands causes this line to appear in MacVim, however briefly. 

``` shell
git --git-dir=/Users/user/prg/git-directory/.git --no-pager add .
```

This is also being appended to my Git commit messages, too.

My install of MacVim is through Homebrew, as is Git.

**Comment by spf13** [comment]
Can you make sure you are running the latest everything and confirm this is still pending. I can't reproduce it. If it is, can you add more information and reopen.
