### ISSUE TITLE
Errors opening vim

### ISSUE THREAD

**Issue by alexandersvozil** [spf13/spf13-vim#397]
I really love your work on this project and I recommended it to everyone who loves vim but now I ran into a problem as I installed it on Ubuntu 13.04:

"Error detected while processing function airline#update_statusline..<SNR>121_app
ly_window_overrides..<SNR>121_apply_window_overrides..<SNR>121_apply_window_over
rides..<SNR>..." The "<SNR>121_apply_window_over
rides..<SNR>" Part is repeated 50 times ~ and then it opens normally. Something like function depth exceeded limit is written in the end.

**Comment by jcbwlkr** [comment]
I had some problems in my own fork when I installed airline. I deleted everything under `~/.vimviews` and it stopped giving me problems. That may or may not help you with your issue.

**Comment by spf13** [comment]
Similarly I found clearing vimviews was needed and resolved things.

**Comment by alexandersvozil** [comment]
![screenshot from 2013-07-10 01 53 37](https://f.cloud.github.com/assets/2186148/771913/32595aea-e8f3-11e2-8abd-5e6f2bc0a4c1.png)

I tried this but it still produces the same error :(. Thanks on replying anyway.

**Comment by spf13** [comment]
Can you file this on airlines issue page as well?

On Jul 9, 2013, at 7:53 PM, Firespy notifications@github.com wrote:

I tried this but it still produces the same error :(.

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/issues/397#issuecomment-20713569
.

**Comment by alexandersvozil** [comment]
Reinstalling the Bundle bling/vim-air sealed the deal. Thank you.

**Comment by bling** [comment]
just so everyone knows, airline was broken for a 6-7 hour window when a change was pushed that affected people with vim versions lesser than 1058.  updating to the latest will resolve this issue.  thanks.

**Comment by ghost2109** [comment]
Also if you install spf13 vim as root it creates the .vimviews ( also happens with backup and swap directories) with the owner set to root. To fix just chown to your user name 'sudo chown $USER .vimviews.'
