### ISSUE TITLE
powerline broked..

### ISSUE THREAD

**Issue by victoredwardocallaghan** [spf13/spf13-vim#398]
The following comit broke powerline for me by uninstalling it..
4e85118d516b0856ede17614ac7d6277b4a70032
everything was working fine before. :/

**Comment by jcbwlkr** [comment]
Were you using the powerline in `~/.vim/bundle/` for other general powerline usage like your shell prompt or tmux or something?

**Comment by victoredwardocallaghan** [comment]
just added a simple test:

``` vim
if has("python")
  echomsg 'python - true'
endif

if has("python3")
  echomsg 'python3 - true'
endif
```

it would seem python3 is not exposed. I went looking and found:
https://bugs.archlinux.org/task/25529
which made me go looking for:
https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/vim#n109

but it works any way despite that switch being off at configure, why do we bother to check? hate this python2/3 thing for years it has been a pain :p

Cheers,
Edward.

**Comment by spf13** [comment]
I've switched the default to vim-airline which doesn't depend on python at
all and seems to be just as good as powerline (and quite a bit faster).

Why not give that a try?

**Comment by jcurtis** [comment]
Just updated today after a couple months. vim-airline looks great but I'm getting errors about Powerline every time I open a file. Not sure how to disable them...

```
E117: Unknown function: Powerline
E15: Invalid expression: Powerline(19) 
```

**Comment by jcbwlkr** [comment]
Clear out your vimviews `~/.vimviews` and that should take care of it.

**Comment by jcurtis** [comment]
Worked like a charm, thanks @jacobwalker0814
