### ISSUE TITLE
Error detected while processing function SetNumbers..ResetNumbers..NumbersRelati veOff: line    3: E15: Invalid expression: 

### ISSUE THREAD

**Issue by gitig** [spf13/spf13-vim#399]
how should i do...

**Comment by kelvl** [comment]
having the same issues here too. just did a fresh install using the installer

**Comment by kelvl** [comment]
looks to be related to this https://github.com/myusuf3/numbers.vim/issues/36

it hasn't been pulled into master yet, but applying his patch fixed it for me

**Comment by gitig** [comment]
thx kelvl
