### ISSUE TITLE
DelimitMate error.

### ISSUE THREAD

**Issue by cobhimself** [spf13/spf13-vim#4]
Whenever I'm in insert mode and press backspace, I get this error:

=DelimitMate_BS() E117: Unknown function: DelimitMate_BS

**Comment by spf13** [comment]
Ok, figured this one out. 

I previous version of DelimitMate was being stored in a vim view, so any file I had previously edited was "caching" the old operation, trying to execute a function which has since been renamed.

```
rm -rf ~/.vimviews/* 
```

fixed it for me.

**Comment by cobhimself** [comment]
This fixed it for me temporarily. I close macvim and open it again after clearing the .vimviews folder and still get the error. I didn't get it when working with a new file though.
