### ISSUE TITLE
256 colors in terminal seems not working properly

### ISSUE THREAD

**Issue by lxyu** [spf13/spf13-vim#40]
Env: 
1. Mac OS X Lion, iTerm2
2. I use homebrew to install vim and macvim. which have both ruby and python enabled.

Problem:
I try to enable 256-color support based on you config file, but no success.

I modified these lines in Vim UI part

``` vim
" Vim UI {
  colorscheme solarized
  set t_Co=256    " Enable 256 color support                                                                                                                         
  set gfn=Monaco:h12
  " Configure solarized theme {
      set background=dark         " Assume a dark background
      let g:solarized_termtrans=1
      let g:solarized_termcolors=256
  " }
```

But the 256 color only enabled for php files. For other files, I need to manually type 
`:set t_Co=256`
`:colorscheme solarized`
to get 256-colors ﻿﻿enabled.

The config seems not working, It's really weird to me.

Another thing similar is, when I open .php file, the codes were always folded even after I changed the `set foldenable` to `set nofoldenable`.

Why these config not working? I'm still new to vim config, so if there're anything more I should provide, give me a hint.

Thanks.

**Comment by lxyu** [comment]
copy solarized theme from bundle/vim-colors-solarized to rbtweaks/colors/ fixs this problem.

**Comment by lxyu** [comment]
emm. also need to comment out `set term=builtin_ansi`.

**Comment by spf13** [comment]
I believe this is fixed in the latest release. Please confirm (reopen if it's still an issue)
