### ISSUE TITLE
Installation ends with screwed up terminal

### ISSUE THREAD

**Issue by mightyiam** [spf13/spf13-vim#409]
Dear friends,
The installation in my system ends with a screwed up terminal and during it, there are some error messages/warnings:
shahar@shahar-desktop:~$ rm -rf .vim\* .spf13-vim-3/
shahar@shahar-desktop:~$ curl http://j.mp/spf13-vim3 -L -o - | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147  100   147    0     0    155      0 --:--:-- --:--:-- --:--:--   238
100  1404  100  1404    0     0    655      0  0:00:02  0:00:02 --:--:--  2221
Thanks for installing spf13-vim
backing up current vim config
cloning spf13-vim
Cloning into '/home/shahar/.spf13-vim-3'...
remote: Counting objects: 2167, done.
remote: Compressing objects: 100% (1522/1522), done.
remote: Total 2167 (delta 841), reused 1762 (delta 582)
Receiving objects: 100% (2167/2167), 2.51 MiB | 461.00 KiB/s, done.
Resolving deltas: 100% (841/841), done.
Checking connectivity... done
setting up symlinks
Installing Vundle
Cloning into '/home/shahar/.vim/bundle/vundle'...
remote: Counting objects: 2461, done.
remote: Compressing objects: 100% (1592/1592), done.
remote: Total 2461 (delta 834), reused 2389 (delta 775)
Receiving objects: 100% (2461/2461), 297.65 KiB | 163.00 KiB/s, done.
Resolving deltas: 100% (834/834), done.
Checking connectivity... done
update/install plugins using Vundle
Vim: Warning: Input is not from a terminal
shahar@shahar-desktop:~$

And here I have to type "reset" in order for the terminal to work. Otherwise nothing I type is being printed back to me. Line length is screwed up until I 'reset'.

**Comment by spf13** [comment]
We recently upgraded the install script. Can you try it again?

**Comment by mightyiam** [comment]
Ok, now I get this:

```
shahar@shahar-desktop:~$ curl http://j.mp/spf13-vim3 -L -o - | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147  100   147    0     0    384      0 --:--:-- --:--:-- --:--:--   420
100  3792  100  3792    0     0   3866      0 --:--:-- --:--:-- --:--:--  3866
Cloning into '/home/shahar/.spf13-vim-3'...
remote: Counting objects: 2205, done.
remote: Compressing objects: 100% (1549/1549), done.
remote: Total 2205 (delta 849), reused 1797 (delta 593)
Receiving objects: 100% (2205/2205), 2.52 MiB | 558.00 KiB/s, done.
Resolving deltas: 100% (849/849), done.
Checking connectivity... done
\e[32m[✔] Successfully cloned spf13-vim
\e[32m[✔] Setting up vim symlinks
Cloning into '/home/shahar/.vim/bundle/vundle'...
remote: Counting objects: 2461, done.
remote: Compressing objects: 100% (1592/1592), done.
remote: Total 2461 (delta 834), reused 2387 (delta 775)
Receiving objects: 100% (2461/2461), 297.09 KiB | 125.00 KiB/s, done.
Resolving deltas: 100% (834/834), done.
Checking connectivity... done
\e[32m[✔] Successfully cloned vundle
Vim: Warning: Input is not from a terminal
\e[32m[✔] Now updating/installing plugins using Vundle

                                                      Thanks for installing spf13-vim.
                                                                                      © 2013 http://vim.spf13.com/
                                                                                                                  shahar@shahar-desktop:~$
```

And terminal still gets messed up and I have to type `$reset`

**Comment by X4** [comment]
Putting \e[0m after \e[32m[✔] should fix it. @spf13 sorry, forgot that, I think "echo" has broader compatibility than printf in different shells also, so replacing that in msg() would make sense. :)

example: echo -e "\e[32m[✔]\e[0m  ${1}${2}"

**Comment by mightyiam** [comment]
@X4 , I'm not sure how to implement that change because I'm not sure where to insert that string you mentioned exactly and whether to change anything else that might seem obvious to you. Otherwise I would make the change and test.

**Comment by X4** [comment]
@mightyiam just run git pull, @spf13 already fixed it.

**Comment by mightyiam** [comment]
Last change was seven hours ago on it. When did he fix it? Perhaps on another branch?

**Comment by X4** [comment]
@mightyiam 
can you replace the success() and error() function in bootstrap.sh with this and try again?
I think that coloring the shell may cause it, or it's the unicode symbol.

``` bash,
success() {
    if [ "$ret" -eq '0' ]; then
    msg "[✔] ${1}${2}"
    fi
}

error() {
    msg "[✘] ${1}${2}"
    exit 1
}

```

What does echo $SHELL say?

**Comment by mightyiam** [comment]
```
shahar@shahar-desktop:~$ echo $SHELL
/bin/bash
```

I've made the change and ran it. I got the original from `https://raw.github.com/spf13/spf13-vim/3.0/bootstrap.sh`.
While it is running, I'd like to ask you a question. Does this script support the existence of an installation? What does it do on such a case? It is going over all the bundles and takes a while. Should I `rm -rf .vim* .spf13-vim3` before running it?

**Comment by X4** [comment]
@mightyiam Thanks for the quick reply, no you don't need to run that command. The installer renames the .vim,.vimrc and .gvimrc  to ".vim.20130801_1375313973". The the suffix is just the year,month,day and second. Detecting an existing .spf13-vim3 repo should also work.

@spf13 can you rename `date +%Y%m%d_%s` to  `date +%Y%m%d%S`?

**Comment by mightyiam** [comment]
Ah!
Now the terminal seems fine:

```
shahar@shahar-desktop:~$ bash bootstrap.sh 
trying to update spf13-vim
From https://github.com/spf13/spf13-vim
 * branch            3.0        -> FETCH_HEAD
Already up-to-date.
[✔] Successfully updated spf13-vim
[✔] Setting up vim symlinks
Cloning into '/home/shahar/.vim/bundle/vundle'...
remote: Counting objects: 2461, done.
remote: Compressing objects: 100% (1592/1592), done.
remote: Total 2461 (delta 834), reused 2387 (delta 775)
Receiving objects: 100% (2461/2461), 297.09 KiB | 177.00 KiB/s, done.
Resolving deltas: 100% (834/834), done.
Checking connectivity... done
[✔] Successfully cloned vundle
[✔] Now updating/installing plugins using Vundle

Thanks for installing spf13-vim.
© 2013 http://vim.spf13.com/
shahar@shahar-desktop:~$
```

**Comment by X4** [comment]
Thank you for reporting the issues you had, I think that will help fixing problems that other people might have aswell.

Can you tell me what happens when you run:
echo -e "\e[32m test"; followed by reset, then run printf "%b\n" "\e[32m ass"
Does your terminal screw up again?

**Comment by mightyiam** [comment]
No, it doesn't screw up.

```
shahar@shahar-desktop:~$ echo -e "\e[32m test";
 test
shahar@shahar-desktop:~$ 
```

Then I `$reset` and

```
shahar@shahar-desktop:~$ printf "%b\n" "\e[32m ass"
 ass
shahar@shahar-desktop:~$ 
```

Doesn't display any special characters.

**Comment by X4** [comment]
Would you mind running bootstrap.sh again, this time with colors enabled? The only difference with the original bootstrap.sh is that "\033[0m" is replaced by "\e[0m"
Just replace the success() and error() functions again with this:

``` bash,
success() {
    if [ "$ret" -eq '0' ]; then
    msg "\e[32m[✔]\e[0m ${1}${2}"
    fi
}

error() {
    msg "\e[31m[✘]\e[0m ${1}${2}"
    exit 1
}
```

I am curious if not resetting colors properly caused this, or something else.

**Comment by mightyiam** [comment]
Terminal ended up fine. I was asked something during it:

```
shahar@shahar-desktop:~$ bash bootstrap.sh 
trying to update spf13-vim
From https://github.com/spf13/spf13-vim
 * branch            3.0        -> FETCH_HEAD
Already up-to-date.
[✔] Successfully updated spf13-vim
[✔] Setting up vim symlinks
trying to update vundle
From https://github.com/gmarik/vundle
 * branch            master     -> FETCH_HEAD
Already up-to-date.
[✔] Successfully updated vundle
[✔] Successfully cloned vundle
CSApprox skipped; terminal only has 8 colors, not 88/256
Try checking :help csapprox-terminal for workarounds
Press ENTER or type command to continue
[✔] Now updating/installing plugins using Vundle

Thanks for installing spf13-vim.
© 2013 http://vim.spf13.com/
shahar@shahar-desktop:~$
```

**Comment by X4** [comment]
Cool, thank you Shahar & have fun hacking Android!
Don't close the ticket yet, let's have @spf13 verify the changes.

PS: That's a sweet puppy you have on that pic
