### ISSUE TITLE
Syntax highlight in php

### ISSUE THREAD

**Issue by fredrike** [spf13/spf13-vim#41]
When saving a php file the syntax highlight is removed.

(I can see some text flashing by, but I don't know how to find it).

**Comment by fredrike** [comment]
Yep, it were my php installation that were broken..

**Comment by mauserrifle** [comment]
@fredrike I'm having this issue too on a fresh install of spf13-vim. What do you mean with:

> "Yep, it were my php installation that were broken.."

How did you fix this?

**Comment by fredrike** [comment]
I re-installed my php installation and now it works.
