### ISSUE TITLE
openning buffers in new tabs causes error

### ISSUE THREAD

**Issue by sbucek** [spf13/spf13-vim#42]
While opening or changing buffers inside newly created tabs I'm getting the same error message over and over again:

Error detected while processing function <SNR>32_BEActivateBuffer:
line 18:
E684: list index out of range: 3

After pressing enter buffer opens, but it's really annoying. It only occurs inside newly created tabs.
Any ideas on what's  causing this and what to do about it?

Thank you very much.

**Comment by jaywilliams** [comment]
I've been experiencing the same issue myself.

**Comment by sbucek** [comment]
OK, the problem is the bufexplorer plugin. I've removed it from bundles/rbtweaks/plugin  and life is perfect again.
Here's the article which brought me on the right track : http://vim.1045645.n5.nabble.com/Fwd-E684-error-when-changing-buffers-td4753709.html

Cheers!

**Comment by spf13** [comment]
I have fixed this in the 3.0 branch.
