### ISSUE TITLE
Can't set noautochdir

### ISSUE THREAD

**Issue by randomor** [spf13/spf13-vim#420]
I wasn't able to set to `noautochdir`. I followed the instruction in `.vimrc`. I first added the `let g:spf13_no_autochdir = 1` into `.vimrc.bundles.local`, it doesn't work. And then I commented out the whole thing. Still doesn't work. Right now, when I open a file in a new buffer, the current directory will always change to the current file directory. I used `:pwd` to find out. This is causing me some problems since I am not able to run `rspec` with it. The built-in `bin/sh` is also defaulting to that directory and running `rspec` will not able to require the `spec_helper` if I do `:!rspec spec/models/user_spec.rb`, I have to do `:!cd ../.. ; rspec spec/models/user_spec.rb` to make the spec run. Anyone having the same problem or know the solution?

``` viml
 " Most prefer to automatically switch to the current file directory when
 " a new buffer is opened; to prevent this behavior, add the following to
 " your .vimrc.bundles.local file:
 "   let g:spf13_no_autochdir = 1
  if !exists('g:spf13_no_autochdir')
    "autocmd BufEnter * if bufname("") !~ "^\[A-Za-z0-9\]*://" | lcd %:#
    "Always switch to the current file directory
  endif

```

Thanks for the great work!

**Comment by spf13** [comment]
I can think of two possibilities.
1. Vim caching is messing with you. remove your .vimviews directory and try
   again.
2. A different plugin is setting this after the .vimrc is loaded.

**Comment by randomor** [comment]
Sweet. Your first solution helped! Thanks for your expert insight. :+1:
