### ISSUE TITLE
Private use code utf-8 charater in status line (EE82A1)

### ISSUE THREAD

**Issue by msmart** [spf13/spf13-vim#422]
Hi! On my terminal os OS X (both Terminal and iTerm) and on my Ubuntu I have a special character on several placed of my status line. When urlencoded I get this value %EE%82%A1. The characters some how interfers with the rest of the status line.

Any idea what to do about that?

Thanks again for spf13! I use it all time and practically everywhere!

Greetings.
Michael

**Comment by jcbwlkr** [comment]
Michael,

What you are seeing is one of the special powerline symbols in the status bar. You have two options:
1. Install a powerline-enabled font from https://github.com/Lokaltog/powerline-fonts Click on a font, click on a font file, then click View Raw (This is the prettier option)
2. Disabled powerline symbols in the status line. If you are using the default status line "airline" then you can do this by adding the following line to your .vimrc.local `let g:airline_powerline_fonts=0` (This is the easier option)

Jacob

**Comment by msmart** [comment]
wow, looks cool! Thanks a lot!
