### ISSUE TITLE
Closing tagbar window breaks vim-airline status line.

### ISSUE THREAD

**Issue by qva5on3** [spf13/spf13-vim#423]
How to reproduce:
1. open file x
2. open file y
3. go back to file x
4. toggle Tagbar window on
5. toggle Tagbar window off
6. switch to file y
7. from now on statusline lose its colors

It's been confirmed by @bling [majutsushi/tagbar#165](https://github.com/majutsushi/tagbar/issues/165) that issue is only reproducible on spf-13/vim configuration.

**Comment by janlarres** [comment]
After some experiments the culprit seems to be the restore_view plugin. I can even regularly reproduce it without any Tagbar involvement at all by just calling `vim file1 file2` and then executing `:next`.

**Comment by qva5on3** [comment]
@majutsushi Sorry, but by simply opening two files any executing `:next` I was not able to get the same effect I'm seeing when toggling off Tagbar window.

BTW I'm also pretty sure this issue wasn't here ~2/3 weeks ago.

**Comment by janlarres** [comment]
It doesn't always work for me either, I don't know the exact circumstances that are needed. But it certainly does happen sometimes, and even if Tagbar is not involved at all. So I probably can't do anything more to help here, although it seems to be some conflict between the `mkview`/`loadview` commands and airline (this is probably worth looking at for @bling).

Note that I used the stock spf13 config to test this and not your local changes.

**Comment by bling** [comment]
@majutsushi that's definitely the culprit....i'm also having trouble reproducing consistently over here.  long story short, due to ordering of autocmds, restore_view saves the default `statusline` before airline overwrites it.

@qva5on3 for the time being, you can disable views altogether with `let g:spf13_no_views=1`.

**Comment by qva5on3** [comment]
@bling Does it mean that it would be fixed in airline? I really appreciate vim views and loves airline. Be able to use them again would be great.

**Comment by bling** [comment]
@qva5on3 another option you can try is `set viewoptions-=options`.  however, i don't use spf13 or views....so unless you can find a way to consistently reproduce this from scratch (e.g. all `vim*` directories cleared out) i won't know what/how to fix.

**Comment by qva5on3** [comment]
@bling  `set viewoptions-=options` doesn't work. Only disabling views completely solves this issue. 
Is there a way autocmds can be ordered?

**Comment by bling** [comment]
@qva5on3 you would have to clear out the augroups of both plugins and add them again in the correct order.  or you can use a hack fix with `CursorMove` that checks to see if the statusline isn't what it's supposed to be, and reset it.

**Comment by qva5on3** [comment]
@bling Interestingly if after getting corrupted statusline I run `AirlineToggle` twice everything is perfectly good. Even calling `TagbarToogle` on and off doesn't disabled statusline. Any clue?

Then a solution would be to execute `AirlineToggle` twice while starting vim, ex. in .vimrc(.local).

**Comment by bling** [comment]
`AirlineToggle` lets you use airline or the default `statusline`.  so naturally when it turns on it'll overwrite everything to the correct state.

**Comment by qva5on3** [comment]
@bling Yes, but calling it twice persistently fixes the issue. It's enough to call it prior to first `TagbarToggle` and everything works since then.

**Comment by qva5on3** [comment]
Adding those two lines to my .vimrc.local file seems to be valid workaround.

`au VimEnter * AirlineToggle 
  au VimEnter * AirlineToggle`
