### ISSUE TITLE
"Can't open file" errors after upgrading to MacVim 7.4-70

### ISSUE THREAD

**Issue by adambiggs** [spf13/spf13-vim#424]
After upgrading to MacVim 7.4-70, I keep getting "can't open file" errors from various plugins:

![image](https://f.cloud.github.com/assets/857229/995993/e7a3c1ac-09c7-11e3-9707-c1d2270366bb.png)

My shell is zsh, so I thought the problem might be [something like this](http://thejacklawson.com/2011/12/vim-cant-open-errofile/index.html), but shell is already being set to `shell=/bin/sh` so that shouldn't be a problem.

I've tried:
- Reinstalling spf13-vim without any customizations
- Reinstalling MacVim 7.4 (with/without Homebrew)
- Reverting to MacVim 7.4b-69
- Deleting all Vim temp, swap, views, etc. files
- Deleting MacVim preferences
- Repairing disk permissions
- Manually setting owner/permissions on the offending paths
- Launching MacVim from bash instead of zsh
- Uninstalling MacVim all together and using the built-in Vim in bash via Terminal.app

Nothing has helped. For some reason, spf13-vim is now broken on my machine. I don't know what else to try at this point...

Has anyone run into similar problems?

**Comment by comeonly** [comment]
I've changed like this, then it works.

```
" .vimrc.fork
set shell=/bin/zsh
```

**Comment by adambiggs** [comment]
> I've changed like this, then it works.
> 
> ```
> " .vimrc.fork
> set shell=/bin/zsh
> ```

@comeonly That seemed to do the trick! But I would love to know how/why that fixed the problem...
