### ISSUE TITLE
Strange characters on the status line

### ISSUE THREAD

**Issue by ghost** [spf13/spf13-vim#425]
After the last update of spf13 in the status line appeared strange problems.

http://img19.imageshack.us/img19/6853/bom9.png

gvim 7.4.0-2

On the other fonts the same problem. What could be the problem?
Regards K.

**Comment by qva5on3** [comment]
Are you using fonts for powerline?

**Comment by ghost** [comment]
I set only one option:
"set guifont=Source\ Code\ Pro\ Regular\ 10"
On the other fonts the problem also occurs.

**Comment by jcbwlkr** [comment]
@kelloco2 See the suggested steps in this issue: https://github.com/spf13/spf13-vim/issues/422

**Comment by ghost** [comment]
Ok. Thanks, all works
http://img690.imageshack.us/img690/4236/u105.png
However, I thought this distribution after the installation will work OOTB (Out of the box). Maybe I shouldn't update it or it was cause by the Arch Linux.
Regards K.
