### ISSUE TITLE
Status bar displaying strange characters

### ISSUE THREAD

**Issue by iaculch** [spf13/spf13-vim#426]
I apologise if I have put this issue into the wrong section.

I have installed the spf13 vim package onto a brand new mac running osx 10.8.4 and am receiving strange characters in the status bar shown in the screenshot below.

I have tried running the install again (easy install using curl), as well as changing the font.

![screen shot 2013-08-22 at 12 57 04 am](https://f.cloud.github.com/assets/5279217/1001895/75c1a336-0a73-11e3-9132-31e8a1523c03.png)

**Comment by ljani** [comment]
See #425, #422 and #413.
