### ISSUE TITLE
ShowMarks Bundle not installed

### ISSUE THREAD

**Issue by bpizzi** [spf13/spf13-vim#43]
Thanks for sharing this, it's definitely one of the best vim config around ;)

Btw you have some config for ShowMarks in your .vimrc, but I think "vim-scripts/ShowMarks" bundle declaration is lacking somehow, no ?

**Comment by spf13** [comment]
Thanks for the feedback. I'll include it or (preferred) feel free to fork and issue a pull request.

**Comment by bpizzi** [comment]
Yep, I'll cook out a quick PR.
Thanks
