### ISSUE TITLE
Some more Fugitive mappings

### ISSUE THREAD

**Issue by jcromero** [spf13/spf13-vim#431]
For completeness, could it be possible to add these Fugitive commands to .vimrc?

nnoremap <silent> <leader>gr :GRead<CR>:GitGutter<CR>
nnoremap <silent> <leader>ge :GEdit<CR>

**Comment by sbennett18** [comment]
Why not make a pull request with these?

**Comment by jcromero** [comment]
@sbennett18 Done: https://github.com/spf13/spf13-vim/pull/432
