### ISSUE TITLE
Duplicated code in .vimrc and .vimrc.bundles

### ISSUE THREAD

**Issue by jcromero** [spf13/spf13-vim#436]
Can these lines in .vimrc.bundles be deleted?

```
" Setup Bundle Support {
    " The next three lines ensure that the ~/.vim/bundle/ system works
    filetype off
    set rtp+=~/.vim/bundle/vundle
    call vundle#rc()
" }
```

The three lines of code appear in .vimrc already.

**Comment by e7h4n** [comment]
No，because `bootstrap.sh` invoke `.vimrc.bundles` instead `.vimrc`, so `.vimrc.bundles` must contain those lines.

In the other hand, vim will load `.vimrc.bundles.fork` before `.vimrc.bundles` when startup, so you can't remove those lines from `.vimrc`.

**Comment by jcromero** [comment]
Thaks for the explication.
