### ISSUE TITLE
Is vim-gitgutter working?

### ISSUE THREAD

**Issue by jcromero** [spf13/spf13-vim#437]
vim-gitgutter is not working here in my debian machine. I have even installed spf13 from scratch, without any additional packages, only standard ones, and it doesn't work either. Can someone confirm this?

git version 1.7.10.4
VIM - Vi IMproved 7.3

**Comment by jcbwlkr** [comment]
It's working for me with default spf13. Running Fedora 18, git 1.8.14 and vim 7.3.

Do you get any kind of output or errors?

Also maybe try clearing your `~/.vimviews`? I don't know if that matters in this case or not.

**Comment by jcromero** [comment]
@jacobwalker0814 I have tried even a new installation of spf13, and have tried in another machine with git 1.8.4~rc3 and VIM 7.4 (debian unstable) and it doesn't work either. Can I debug the problem somehow? By the way, I removed my `~/.vimviews` directory without any result.

I don't get any output or error. I remove some lines from my `.spf13-vim-3/.vimrc` file (under git control), save with `:w` and the gutter column doesn't appear.

**Comment by spf13** [comment]
Could be an issue with the latest gitgutter. No reason to assume the
same version of git gutter.

Steve Francia
spf13.com
@spf13

**Comment by jcromero** [comment]
@spf13 What version of git gutter are you using? I can try to checkout the same version as you.

**Comment by jcromero** [comment]
@spf13 Confirmed. I have checked out to https://github.com/airblade/vim-gitgutter/commit/ff031d022f2123353bc93a3aa97290287c10a287 version (I basically have bypassed august commits) and now is working fine.

**Comment by FrankFang** [comment]
Thanks!
