### ISSUE TITLE
Numbers.vim Vundle Error

### ISSUE THREAD

**Issue by jordanthornquest** [spf13/spf13-vim#438]
I ran a pull request for the `spf-vim-13` repo, and went to BundleInstall. This was a part of the output for the BundleInstall:

```
! myusuf3/numbers.vim
```

Running Vim gives me this error:

```
~|⇒ vim
Error detected while processing /Users/jordanthornquest/.spf13-vim-3/.vim/bundle/numbers.vim/plugin/numbers.vim:
line   95:
E488: Trailing characters: <<<<<<< HEAD
line  103:
E488: Trailing characters: =======
line  104:
E488: Trailing characters: >>>>>>> 1b8d0a951e9b02cdf57384cbf087340a2ae73df3
```

Anyone else having this problem? 

**Edit**: AirLine was a separate issue from this Numbers.vim error. Sorry about that!

**Comment by bronzehedwick** [comment]
I have the numbers error, but airline is working fine for me after clearing vimviews. 

```
—
```

**Comment by spf13** [comment]
Someone committed a merge conflict to the numbers repo. It's upstream from
us so we can't fix it other than removing it from our distro. Of course we
could submit a pull request or wait for them to fix it, which seem like the
right immediate actions.

Steve Francia
spf13.com
@spf13

On Aug 30, 2013, at 2:02 PM, Jordan Thornquest notifications@github.com
wrote:

I ran a pull request for the spf-vim-13 repo, and went to BundleInstall.
This was the output for the BundleInstall:

! myusuf3/numbers.vim

Running Vim gives me this error:

~|=> vim
Error detected while processing
/Users/jordanthornquest/.spf13-vim-3/.vim/bundle/numbers.vim/plugin/numbers.vim:
line   95:
E488: Trailing characters: <<<<<<< HEAD
line  103:
E488: Trailing characters: =======
line  104:
E488: Trailing characters: >>>>>>> 1b8d0a951e9b02cdf57384cbf087340a2ae73df3

Anyone else having this problem? AirLine is also (resultantly?) broken,
which is totally lame.

## 

Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/issues/438
.

**Comment by jordanthornquest** [comment]
Sweet, will do. Thanks, guys!

**Comment by jordanthornquest** [comment]
Also, clearing the `.vimviews` did help fix my AirLine. You guys rock!
