### ISSUE TITLE
Line number and space between 'if' and 'endif' are highlighted

### ISSUE THREAD

**Issue by jasoncyu** [spf13/spf13-vim#439]
![weird_highlighting](https://f.cloud.github.com/assets/1874847/1061581/4e19db02-11e7-11e3-9256-67187099c7ab.png)
The line numbers and the vertical space between if blocks are highlighted, what's causing that?

**Comment by jphustman** [comment]
That is the indent guides plugin.  It's handy, but I don't like it all the time either.

off the top of my head, but try putting this in your .vimrc.local, then when you want to see them, just hit F11

```
let g:indent_guides_enable_on_vim_startup = 0
noremap <F11> :set list!<CR>
```

**Comment by bronzehedwick** [comment]
@jasoncyu, did this work for you? If so, please consider closing this issue. It's almost a year old :/

**Comment by jasoncyu** [comment]
yup, that worked for me! thanks for the reminder

**Comment by bronzehedwick** [comment]
No problem. Thanks for closing!
