### ISSUE TITLE
UnBundle command not recognized.

### ISSUE THREAD

**Issue by seth-brown** [spf13/spf13-vim#445]
Hi,

Thanks for this great project. I've just started trying spf13 and I am having an issue with the UnBundle command. I've added the following my .vimrc.local config file:

UnBundle 'AutoClose'
UnBundle 'spf13/vim-autoclose'

Unfortunately, neither command seems to disable autoclose. Does anyon know what may be the problem?

Thanks for your time.

**Comment by bronzehedwick** [comment]
Try putting them in .vimrc.bundles.local. 

```
—
```

**Comment by seth-brown** [comment]
Thanks for the help. Unfortunately, this did not work.

**Comment by jcbwlkr** [comment]
@drbunsen after change your bundle configuration you need to run `:BundleClean` and `:BundleInstall` to refresh what is actually installed. You can do it from the command line with `vim +BundleInstall! +BundleClean +qall`.

If it doesn't work then move your UnBundle commands back to `.vimrc.local` and try again.

**Comment by seth-brown** [comment]
Thanks @jacobwalker0814! I should have thought of this. Solved.
