### ISSUE TITLE
Relative line numbers sometimes not working

### ISSUE THREAD

**Issue by adambiggs** [spf13/spf13-vim#452]
Not sure if this is a MacVim bug or something else. But when opening/closing a splits, the line numbers are sometimes drawn as absolute instead of relative.

Also, I've noticed a few times where most of the line numbers update correctly when moving the cursor, but a small block of them will get stuck on absolute line numbers.

Giving focus to a different app and then going back to MacVim solves the problem, but `:redraw!` doesn't do anything.

**Comment by emielvangoor** [comment]
I have the same issue when opening a new buffer, it sometime loses relative line numbering and/or "set nocursorline". Does someone have a solution?

**Comment by spf13** [comment]
Please clear your views (~/.vimviews). We made a change about the time this issue was filed from relative to absolute line numbers. Any file opened prior to that change would have that setting cached in the session view.
