### ISSUE TITLE
vim 7.4.27 w/spf13-vim-3 crashes with SEGV on ruby filetype file during insert

### ISSUE THREAD

**Issue by wwalker** [spf13/spf13-vim#463]
In vim 7.4.27 on Fedora 19, fullly up to date:

I open a file "a" and type:  irequire<Esc>   and all is well.
I open a file "a.rb" and type: irequ    and instant segfault on the "u"

If I move neocomplcache out of my .vim/bundles/ directory, no crash.

If I comment out line 735 of .vimrc (from spf13-vim-3), no crash.
let g:neocomplcache_omni_patterns.ruby = '[^. _\t].\h\w_|\h\w*::'

$ vim ~/a.rb
Vim: Caught deadly signal SEGV
Vim: preserving files...
Vim: Finished.
Segmentation fault (core dumped)

I'll run any test you wish to help nail this down.

**Comment by wwalker** [comment]
I also tried adding Bundle vim-ruby/vim-ruby in case neocomplcache used part of it.  This did not prevent the crash.

**Comment by johntyree** [comment]
Backtrace?

Altohught it seems to me that this is pretty clearly an upstream vim problem. There really should not be anyway to make vim segfault based on your config.

**Comment by dmiedema** [comment]
I'm getting a SEGV also in regards to ruby

OS X 10.9.1 -- MacBookPro 11,2
Latest updates to spf13 && running vim _version 7.4.52_

`VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 21 2014 18:21:58)`

if I comment out the line mentioned above, `let g:neocomplcache_omni_patterns.ruby = '[^. \t].\h\w|\h\w*::'` in _.vimrc_ (line 770 for me) i don't get a SEGV

[vimrc.local](https://gist.github.com/dmiedema/8583745) (made a gist to save space here)

To reproduce I just have to

`$ vi Rakefile` (any where, can be a blank file. Doesn't need to be a valid Rakefile)
Start typing
`RDoc::Task.new` and right after `RD` i get a SEGV

**Comment by spf13** [comment]
Send me a PR please. 
 
Best,
Steve

-- 
Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by johntyree** [comment]
Launching as `vi` instead of `vim` can cause serious problems. `vim` is a
rocket ship and `vi` is a covered wagon.

2014/1/23 Steve Francia notifications@github.com

**Comment by dmiedema** [comment]
Right - i forgot to mention i have

_alias vi=vim_ in my .zshrc to avoid accidentally launching vi

**Comment by wwalker** [comment]
I finally found that this was caused by the ruby that vim was built against being upgraded

**Comment by cloudbring** [comment]
I'm having this issue. vim has crashed on me four times today. How can I ensure the ruby that vim is built against is the correct one and fix this problem? I'm on OSX 10.10 and I use macvim from brew.

**Comment by wwalker** [comment]
Emmanuel,

in vim, run this.  it should either tell you a lot about the working ruby, OR it should throw an error that hopefully explains the problem.

:ruby puts "#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL}"

Are you using rvm/chruby/rbenv/etc?

Wayne

**Comment by cloudbring** [comment]
:ruby puts "#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL}"
//=> 2.0.0-p481

I am using RVM. I updated mvim through brew and have done other things
since then but, that seems to have fixed it. Sorry I can't be more precise
than that. I had work that needed getting out the door. If I see this
happening again, I'll update this thread with more detail.

On Wed, Nov 26, 2014 at 5:13 PM, Wayne Walker notifications@github.com
wrote:

> Emmanuel,
> 
> in vim, run this. it should either tell you a lot about the working ruby,
> OR it should throw an error that hopefully explains the problem.
> 
> :ruby puts "#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL}"
> 
> Are you using rvm/chruby/rbenv/etc?
> 
> Wayne
> 
> On Wed, Nov 26, 2014 at 12:10:17PM -0800, Emmanuel Mwangi wrote:
> 
> > I'm having this issue. vim has crashed on me four times today. How can I
> > ensure the ruby that vim is built against is the correct one and fix this
> > problem? I'm on OSX 10.10 and I use macvim from brew.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/spf13/spf13-vim/issues/463#issuecomment-64703896
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spf13/spf13-vim/issues/463#issuecomment-64733452.

## 

Emmanuel Mwangi
http://linkedin.com/in/emmanuelm

**Comment by sfahlberg** [comment]
I have the same issue- displaying the same thing

**Comment by cloudbring** [comment]
Sam,

Have you tried upgrading your RVM and/or Ruby to the latest?
