### ISSUE TITLE
`sudo vim` display errors

### ISSUE THREAD

**Issue by pjump** [spf13/spf13-vim#468]
Whenever I run sudo vim, e.g. `sudo vim /etc/hosts` and then do something that changes the numbers of lines (o, dd, etc.), the lines won't be redrawn correctly, and I can't rely on what I see on the screen until I manually force it to refresh (e.g., by j'ing or k'ing through the file).

This doesn't happen when I run it in user mode.

**Comment by pjump** [comment]
My vim setup is pretty much the default I got from this package, except for a couple of changes in my .vimrc.local:

UnBundle 'honza/snipmate-snippets'
UnBundle 'myusuf3/numbers.vim'
UnBundle 'kien/ctrlp.vim'
Bundle 'epeli/slimux'
Bundle 'ack.vim'
map <C-c><C-c> :SlimuxREPLSendLine<CR>
vmap <C-c><C-c> :SlimuxREPLSendSelection<CR>
set tabstop=2
set shiftwidth=2
"Nonrelative numbering that starts at 1
set number
colorscheme osx_like
"Switch to English when leaving insert mode
autocmd InsertLeave \* silent !xkblayout-state set 0
"Delete erb tag macro
autocmd BufNewFile,BufRead *.erb let @r='ds%ds<'

fu! CzBuffer()
  :au InsertEnter <buffer> silent !xkblayout-state set 1
endfunction

fu! EnBuffer()
  :au InsertEnter <buffer> silent !xkblayout-state set 0
endfunction

**Comment by jcbwlkr** [comment]
Side note, if you want to refresh the screen without j'ing or k'ing through the whole thing you can do `:redraw`

**Comment by pjump** [comment]
Thanks for the side note, but :redraw doesn't do it for me. Only actually moving through the file does.

**Comment by pjump** [comment]
Update: Actually :redraw! does do the job (but it needs the exclamation point) without having to go through the whole screen line by line.

I've also noticed that this results in this weird stacking of the bottom information area, i.e. instead of the stripe's being redrawn, it stacks on top of each other with each line edit (followed by going back to the normal mode) that is not followed by a :redraw! .

![screenshot1](https://f.cloud.github.com/assets/3763707/1767173/55ebd8ee-6750-11e3-8fe3-8c3454a02daa.png)
