### ISSUE TITLE
starting problems

### ISSUE THREAD

**Issue by zackZarap** [spf13/spf13-vim#47]
Hi,

i got some errors by starting vim after "installing" your config..

Fehler beim Ausführen von "/home/zack/.vimrc":
Zeile   57:
E518: Unbekannte Option: undofile
Zeile   59:
E518: Unbekannte Option: undoreload=10000

Fehler beim Ausführen von "function InitializeDirectories":
Zeile   22:
E518: Unbekannte Option: undodir=/home/zack/.vimundo/

Any ideas how to fix this?

OS: Ubuntu 10.10

**Comment by rayz90** [comment]
I have the same issue.

**Comment by spf13** [comment]
I believe this issue has been fixed in the most recent patch. Please test and confirm (re-open this if it's still an issue).

**Comment by rayz90** [comment]
It works now, thanks!
