### ISSUE TITLE
Too large font in gvim

### ISSUE THREAD

**Issue by ostrolucky** [spf13/spf13-vim#474]
I installed spf13-vim and I found out font in gvim is too large as opposed to vim. In attachment below is comparison between gvim (left) and vim (right). Is this correct default behaviour?
![c4ra6sg](https://f.cloud.github.com/assets/496233/1371351/a379db96-3a38-11e3-8d6b-4556cfba4f85.png)

**Comment by davisein** [comment]
It happened to me the same. The first thing I did was to change that
setting. It was easy enough, but I guess many people would have the same
problem. I think a smaller default (to match standard terminal) might be
better.

On 21 October 2013 12:12, gadelat notifications@github.com wrote:

> I installed spf13-vim and I found out font in gvim is too large as opposed
> to vim. In attachment below is comparison between gvim (left) and vim
> (right). Is this correct default behaviour?
> [image: c4ra6sg]https://f.cloud.github.com/assets/496233/1371351/a379db96-3a38-11e3-8d6b-4556cfba4f85.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/spf13/spf13-vim/issues/474
> .

## 

David Navarro Estruch

**Comment by kennethkalmer** [comment]
Just for the next person that stumbles onto this issue, I simply set the following in the `.vimrc.before.local` to fix it:

```
let g:spf13_no_big_font=1
```

Based on https://github.com/spf13/spf13-vim/blob/3.0/.vimrc#L859

**Comment by rekendahl** [comment]
I wonder why the "BIG FONT" is default? Seems like a strange choice to me. If you want to make it clear that you are in gvim why not switch solarized to light or something?

**Comment by spf13** [comment]
Big is relative. Big is only 16pt font in the config.
https://github.com/spf13/spf13-vim/blob/3.0/.vimrc#L861

Depending on a lot of other things 16pt could be just right, or could be huge. On my laptop in macvim this setting provides me 50 lines on screen at my normal resolution (1050 px tall). 

My standard terminal gives me 60 lines, so it is a bit larger in the visual mode, but not much. 

Perhaps we need a smaller default setting for linux.

**Comment by AlexPanY** [comment]
How to change spf13-vim guifont?

**Comment by qrees** [comment]
For 768px tall it provides 23 lines of text, which I think is definitely to little. In most use case 16pt font is quite big. Standard font size for normal text (not headers, titles etc.) is something like 12pt.

**Comment by davisein** [comment]
:1:

I am used spf13 and it was my introduction to vim. This was one of the two
or three non automatic things and the only one that looked broken.

This makes gvim look broken with spf13. A better detail would be good!

**Comment by spf13** [comment]
I've confirmed this issue. I installed the latest ubuntu and then spf13-vim and the font was HUGE.. Much bigger than on the mac or windows or other linuxes I've tried. We should definitely correct this.

**Comment by davisein** [comment]
Thank you!

On 30 June 2014 18:34, Steve Francia notifications@github.com wrote:

> Closed #474 https://github.com/spf13/spf13-vim/issues/474 via 391f61a
> https://github.com/spf13/spf13-vim/commit/391f61aac77c384205285936fcb105d16ba90e30
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spf13/spf13-vim/issues/474#event-136586087.

## 

David Navarro Estruch
