### ISSUE TITLE
how to go to top/bottom of screen

### ISSUE THREAD

**Issue by rockneverdies55** [spf13/spf13-vim#477]
Seems like something's overriding the native functionality of H and M keys, thus I cannot immediately go to the top of the screen with H key and as well to the bottom with L key.

Is there a way to fix this?
Thanks.

**Comment by spf13** [comment]
There's a setting in the vimrc file to disable this 

Steve Francia 
spf13.com
@spf13

**Comment by rockneverdies55** [comment]
Thank you @spf13 

For future referrals, the relative lines are [here](https://github.com/spf13/spf13-vim/blob/3.0/.vimrc#L264) in .vimrc file.
