### ISSUE TITLE
Curl/sh install comand error on Ubuntu

### ISSUE THREAD

**Issue by AloisJanicek** [spf13/spf13-vim#48]
Hi
when I copy
<code>curl http://j.mp/spf13-vim3 -o - | sh</code>
into my terminal on Ubuntu 11.10, I got
<code>sh: Syntax error: newline unexpected</code>

I thought this was happening because Ubuntu use dash instead of bash but when I switch into bash I got

<code>sh: line 1: syntax error near unexpected token `newline'
sh: line 1:`<html>'</code>

Am I doing something wrong or it is Ubuntu issue?

**Comment by wolfgangpfnuer** [comment]
Same here on macosx snow leopard.

There is a second problem: The install-script tries to install command-t, but command-t was replaced with ctrlp :-)

**Comment by spf13** [comment]
Fixed the command T issue. 

I think there's a patch coming in to fix the other.

Quick fix is to do a `curl http://j.mp/spf13-vim3 -L -o - | sh` instead.

**Comment by spf13** [comment]
The fix is in. Please try and confirm. (reopen if still an issue)

**Comment by AloisJanicek** [comment]
Works fine here (Ubuntu 11.10), problem solved. Thanks for quick fix.

**Comment by gedion** [comment]
I get the sh: Syntax error: newline unexpected with Ubuntu 11.10. I am trying the quick fix at the moment.

**Comment by lawik** [comment]
Just got this for some reason on an Ubuntu server. Have installed spf13-vim successfully on both my debian server and my OS X laptop.

**Update: Check the contents you get. I got a HTML error message. No, this is not working shell script ;) wget:ing the url I got from visiting the URL in a browser worked fine.**

**Comment by bronzehedwick** [comment]
Is it because sh defaults to dash, instead of bash? I know I've had problems in the past using dash to install. What happens if you call bash explicitly instead of sh?
—

**Comment by lawik** [comment]
I tried running it through bash. Then i checked what curl was getting and I was apparently getting a HTML error page of some sort. Then I visited the URL in a browser, took the full URL and wget:ed it and got the right script.

Trying to run the error HTML apparently gives this error :)

**Comment by anil-kumar-ma** [comment]
![screenshot from 2016-01-13 14 21 51](https://cloud.githubusercontent.com/assets/15100205/12305095/0ad47dba-ba01-11e5-9527-cef9342a8883.png)
I am using ubuntu 14.04 LTS and getting this error.

**Comment by ghost** [comment]
@anil-kumar-ma that's for a meteor installer.  and in this case, copy and pasting the text is sufficient. no screenshot is required. Please file that bug at meteor, not here.

**Comment by anil-kumar-ma** [comment]
Sure...Now meteor started working.
