### ISSUE TITLE
surround README.markdown issue

### ISSUE THREAD

**Issue by minshallj** [spf13/spf13-vim#484]
the final example in the README for surround has the command vlllls' but it should be vllllS'

This is with a brand new install of spf13-vim. Typing the lower case s in visual mode causes the selected text to delete.

**Comment by spf13** [comment]
Please send pull request with the correct command

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by minshallj** [comment]
Sorry I took to long. Looks like someone else beat me to it!
