### ISSUE TITLE
gvim crashes on opening .vimrc.local and .vimrc.before.local

### ISSUE THREAD

**Issue by developej** [spf13/spf13-vim#486]
I'm using spf13vim on Windows 7.
It worked before, anything I've done in the meantime is rerunning the .cmd for updates, nothing else strikes me as related to this issue.

I wanted to edit my .vimrc.local, and gvim crashed. Same with .vimrc.before.local.

Even if I delete them, open gvim and do a :e ~\.vimrc.local it crashes

Any ideas?
Thanks

**Comment by developej** [comment]
On a laptop (also Windows 7), it opens .vimrc.local without any problems...
On desktop, I reinstalled vim, I reinstalled spf13vim and I still get vim crashes when trying to open .vimrc, .vimrc.local, .vimrc.before.local...

edit: it crashes even if I do :e ~\Desktop\.vimrc (that is creating a new file, there was no .vimrc on Desktop)
any ideas are welcome really

**Comment by louy2** [comment]
I am also having this problem. Vim also crashed when I wanted to open a random python script from my classmate. My issue is #499.

**Comment by ghost** [comment]
@developej : is this still an issue in recent versions?

**Comment by developej** [comment]
@jrobeson It was an issue on one particular installation of Windows 7, which has since been reinstalled. No issues on any other machine, Windows or Linux.

**Comment by ghost** [comment]
closing for now then. reopen if you have the same problem in the future.
