### ISSUE TITLE
deactivate features (auto close , line numbering Autocorrect)

### ISSUE THREAD

**Issue by bergercookie** [spf13/spf13-vim#487]
I need support on how to deactivate certain features of the vim distribution
More specifically how can I : 
1) Turn off the "Automatic append closing characters (" ", [ ], { }. ( ) )" feature?
2) Turn off the dynamice line numbering
I don't seem to find the usage of this feature anyway. You lose the ability to refer to a certain line in your code unless you are at the very first line.
3) Turn off the auto-correct feature.

Which line of the code correspond to these features?
Thanks in advance.

**Comment by phcostabh** [comment]
Add these lines to your `~/.vimrc.local`
- Turn off relative number: `set number`
- Turn off spell check feature: `set nospell`

Add this line to you `~/.vimrc.before`:
- Turn off auto close feature: `let g:autoclose_on = 1`

**Comment by snusnu** [comment]
Dynamic numbering can be very useful as it will give you a nice clue for how many lines you need to yank, delete, whatever. Yanking 23 lines doing `V23jy` is imo much easier than "manually" scrolling down 23 lines while in `V` mode (by pressing `j` 23 times). It takes some getting used to, but once you are, you probably won't go back. Relative line numbering is perfect for that usecase: your current cursor line is 0, and the relative number will tell you exactly how many lines away your "target" is.

Also, most statuslines include the current line number too, so you always know that.

Anyways, to get the best of both worlds, you can stick this into your `~/.vimrc.local`:

``` vim
function! ToggleNumbering()
  if &relativenumber
    set number
    set norelativenumber
  else
    set relativenumber
    set nonumber
  endif
endfunc

noremap <leader>n :call ToggleNumbering()<cr>
```

You can of course map the function to whatever key you desire ...

**Comment by bergercookie** [comment]
I have added the let g:autoclose_on = 1 option in .vimrc.before but has no effect. It still auto closes the opened parentheses, bracket etc.

**Comment by TheCycoONE** [comment]
@bergercookie The correct line seems to be:
let g:autoclose_on = 0

**Comment by identor** [comment]
Everything went fine when i added `let g:autoclose_on = 0`, but when editing php or html files '<' still auto closes.

**Comment by gravis** [comment]
Almost working: Autoclosing is disabled using `let g:autoclose_on = 0`, but I can't use the arrows anymore (I know, I should use hjkl instead).
When in edit mode, using arrows will produce new lines with

`9 B
 10 C
 11 A
 12 D
 13 D
`

This plugin is very annoying :(
