### ISSUE TITLE
vim-signify instead of vim-gitgutter?

### ISSUE THREAD

**Issue by mhinz** [spf13/spf13-vim#488]
Disclaimer: I'm the author of vim-signify.

I understand that vim-gitgutter is already integrated and probably proved to be working. I don't even want to convince anyone to use Sy instead of vim-gitgutter. I haven't tried it for a long time either.

Moving _might_ be a good choice nevertheless, since a lot of people seem to report that it works a lot faster. That alone should be a good reason. It also works not only for git, but for other popular version control systems as well. It also has some features that vim-gitgutter doesn't have.

I just wanted to leave this note. If you don't think changing is an option, just close this issue. :-)

**Comment by ljani** [comment]
Sadly no comments from @spf13 here either: #456. Of course this issue provides a lot better reasoning than the other one.

**Comment by mhinz** [comment]
Oh, I didn't even see that issue. Thanks for mentioning.

**Comment by spf13** [comment]
I'm happy to merge a solid pull request, especially if you are willing to help with support. 

gitgutter has been fine for me, but supporting other VCSs would be great.

**Comment by mhinz** [comment]
Okay, I'll look into it, but it might take some days.

**Comment by mhinz** [comment]
Okay, this is my first try. Play around with it a bit since I'm not sure what exact settings you want.

NOTE: Sign colors are linked to the default highlight groups `DiffAdd`, `DiffChange`, `DiffDelete`. (`:h signify-section-colors` for more information.)

p.s. I'll write a proper section for the README in case this gets accepted

**Comment by louy2** [comment]
Since I have met some gitgutter error in #499 I would like to try this.

**Comment by jcbwlkr** [comment]
I've been using vim-signify on some of my machines and have generally preferred it. The ability to show diffs in other VCSs has been nice and I have not yet experienced some of the weird tmp file errors I used to get like what @louy2 mentioned.

**Comment by mhinz** [comment]
This was merged a long time ago -> closed.
