### ISSUE TITLE
Gitgutter error

### ISSUE THREAD

**Issue by louy2** [spf13/spf13-vim#499]
So I was trying to open some shift_jis encoded txt file, but vim gave me the following:

```
Error detected while processing function GitGutter..<SNR>66_is_active..<SNR>66_is_in_a_git_repo:
line    2:
E484: Can't open file C:\Users\louy2\AppData\Local\Temp\VIo741B.tmp
```

The file I want to open is in no way in a git repo.
Also vim crashes when I want to open any of the `.vimrc.xxx`s.

I am using spf13-vim on Windows 8 Enterprise.

**Comment by ljani** [comment]
Probably related: airblade/vim-gitgutter/issues/104

**Comment by teasp00n** [comment]
Gitgutter was recently removed in favor of signify. Clear out your ~/.vimviews/ directory and the problem should go away.
