### ISSUE TITLE
"The Ultimate Vim Distribution" suggests that this is a "Vim Distribution"

### ISSUE THREAD

**Issue by Sequoia** [spf13/spf13-vim#501]
It's a set of plugins for vim, not an actual vim package, I realized after uninstalling gvim & attempting to install this :)

Install instructions should note "first make sure vim is installed" maybe with some suggested paths (Chocolately for windows if that one is known to work).

**Comment by sbennett18** [comment]
It does say:

"Installing on Windows

On Windows and *nix Git and Curl are required. Also, if you haven't already, you'll need to install Vim."

In the readme and gives a link to get Vim.

**Comment by spf13** [comment]
Sequoia,

Please feel free to suggest a revision that you think would make things
clearer in a pull request.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by Sequoia** [comment]
@sbennett18 hmm... what url are you looking at?  This is what I'm seeing right now after hard refresh (with instances of "vim" highlighted):
![vindows](https://f.cloud.github.com/assets/317498/1634632/2aaddb76-579e-11e3-8c78-6dbc797ddf95.png)

Confirmed this copy with `curl` to ensure not getting browser cache.

**Comment by Sequoia** [comment]
@spf13 would you be amenable to me changing to title to "The Ultimate Vim Config Distribution" or something like that?  I don't want to PR such a major change if it's not welcome but I'd suggest that this is _not_ a "Vim Distribution."  If you like I'll submit a PR changing the following:
1. Change title to reflect that this is a config bundle not a vim distro
2. Make first paragraph more explicitly state that it's a set of plugins & configuration defaults
3. Mention that you need vim before you start in install instructions

Would these changes be welcome?  If so I'm happy to create a PR.

**Comment by spf13** [comment]
He's looking at the readme https://github.com/spf13/spf13-vim

It's not on the website. It's just an oversight that needs to be fixed.
Apologies it's not clearer.

It's the gh-pages branch if you want to suggest a change.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by Sequoia** [comment]
@spf13 Will do.  Leaving this issue open 'til I (or someone) gets around to fixing the `gh-pages` branch (probably after thanksgiving for me :us:)

**Comment by spf13** [comment]
It is a distribution "for" vim not "of" vim.
Every other project that works similarly also refers to itself as a vim
distribution... It also goes way beyond just a config distribution.

Happy to entertain anything change suggested that makes it clearer. Can't
promise I'll go with it, but certainly will revise based on the feedback.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13
