### ISSUE TITLE
Prevent vim from setting current directory

### ISSUE THREAD

**Issue by randomor** [spf13/spf13-vim#502]
Recently my vim will change current directory no matter what I do. I'm using spf13 distribution and when I am in a rails app root directory and did `vi`, my `pwd` will be correctly in app root directory. But once I open some file, any file, it will change the `pwd` to `abosolute/path/to/app/assets/stylesheets`, 

When I have `let g:spf13_no_autochdir = 1`, vim will change the `pwd` to current file directory; When I don't, it will change to the stylesheet directory whenever I open a file. 

I'm also using `rails.vim`. Here is the related code inside my `.vimrc`

``` vimscript
    if !exists('g:spf13_no_autochdir')
         autocmd BufEnter * if bufname("") !~ "^\[A-Za-z0-9\]*://" | lcd %:p:h | endif                                                                                         
         " Always switch to the current file directory
    endif
```

I also tried to put set `noautochdir` to the `.vimrc.local`, but that didn't help either.
I have also posted this issue in stackoverflow: http://stackoverflow.com/questions/20272535/how-to-prevent-vim-from-setting-current-directory
Any ideas?

**Comment by johntyree** [comment]
I'm not having this issue, but I'm not using `rails.vim`. If you unbundle it does this still happen?

**Comment by johntyree** [comment]
In general I'd say `UnBundle` everything and test them one by one.

Also you can try grepping through your `/bundle/` dir for "cd" but you'll get a lot of hits.

**Comment by randomor** [comment]
Thanks all. I guess I thought there might be an easier way to find out the problem source. I've turned over to Janus, but might be back some time.
