### ISSUE TITLE
Haskell-mode fails

### ISSUE THREAD

**Issue by schickling** [spf13/spf13-vim#508]
The following occurs when opening a haskell file.

![screenshot 2013-12-02 13 39 49](https://f.cloud.github.com/assets/1567498/1654549/f79e9612-5b4e-11e3-902a-df69d190d202.png)

**Comment by johntyree** [comment]
Do you have hdevtools and ghcmod in your path? Haskell-mode expects you to.
Additionally you need to set your default browser for haddock in `vimrc.local` if you want to be able to jump to docs.

**Comment by schickling** [comment]
Thanks!
