### ISSUE TITLE
Lag when exiting insert mode

### ISSUE THREAD

**Issue by adambiggs** [spf13/spf13-vim#510]
When in insert mode, there is a 1s timeout lag after pressing `<Esc>` before returning to normal mode.

This caused by `<Esc>` key mappings found in these 2 places:
- [.vimrc](https://github.com/spf13/spf13-vim/blob/3.0/.vimrc#L332)
- [AutoClose plugin](https://github.com/spf13/vim-autoclose/blob/master/plugin/autoclose.vim#L92)

When these bindings are unmapped, exiting insert mode happens instantly without any lag.

**Comment by biluncloud** [comment]
I have the similar problem, both when I press ESC from insert mode and visual mode to normal mode, the lag would appear. However when I run VIM using the vimrc without any plugins, the problem still exist. So I tried again and found when ESC is pressed in insert mode, the cursor remained unchanged for 1 or 2 seconds, however before the cursor could be changed, any further action was already permitted immediately after ESC is pressed. So did exit visual mode. (I am running gVim on Windows) .

**Comment by johntyree** [comment]
I don't remember what I was doing at the time, but I have a comment in my `.vimrc.local` that says

```
" Map <ESC> to \033\015 in .Xresources. Now our Meta bindings don't
" conflict and <ESC> is instant! Beautiful!
```

That's linux only of course _and_ I'm not using autoclose so who knows.

**Comment by ljani** [comment]
> I don't remember what I was doing at the time

[MinTTY's Tips](http://code.google.com/p/mintty/wiki/Tips) page has nice explanation:

> It's a historical flaw of Unix terminals that the keycode of the escape key, i.e. the escape character, also appears at the start of many other keycodes. This means that on seeing an escape character, an application cannot be sure whether to treat it as an escape key press or whether to expect more characters to complete a longer keycode.
> 
> Therefore they tend to employ a timeout to decide.

**Comment by adambiggs** [comment]
I should probably mention that I already had settings in my `.zshrc` and `.tmux.conf` files to remove the lag at the terminal level, but Vim was still adding it's own lag because of these mappings.

**Comment by ljani** [comment]
I finally spend some time with this.. Cygwin works fine with the [MinTTY's Tips](http://code.google.com/p/mintty/wiki/Tips) for remapping `ESC`, but that obviously doesn't work for gVim.

With gVim, changing `timeoutlen` to eg. 50ms helps, but I'm not quite sure if I want to do that. `ttimeoutlen` doesn't seem to have any effect with the current plugins.

I was going to try see if there's any difference with removing the mappings @adambiggs suggested, but as the `.vimrc` link points to `HEAD` I'm not quite sure what he's referring to. @adambiggs: could you provide updated info, this time referring to the line of the file of a specific commit, thanks?

**Comment by adambiggs** [comment]
@ljani Sorry, this was a while ago and I didn't think about line numbers going out of sync.

I think [these](https://github.com/spf13/spf13-vim/blob/5c7b264ea6ec6d770c17996a6697ca9c9ca9fc1b/.vimrc#L332) were the .vmrc lines. The AutoClose line hasn't changed, but [here's a link](https://github.com/spf13/vim-autoclose/blob/c098b4f45da6232e66c14898ff6b197f360a29cc/plugin/autoclose.vim#L92) just in case.

**Comment by adambiggs** [comment]
FWIW, the .vimrc issue was fixed by adding this to my .vimrc.fork:

``` vim
unmap <Esc>[H
unmap <Esc>[F
iunmap <Esc>[H
iunmap <Esc>[F
```

And I forked AutoClose to comment out the offending line.

**Comment by ljani** [comment]
I just commented [these four lines](https://github.com/spf13/spf13-vim/blob/ebd410b8a9e220e2fe4a90f2efae5b00afdd6fb5/.vimrc#L376) to test and the delay seems to be gone, even if I didn't remove or fix `vim-autoclose`. I guess I'll install screen someday and test if I lose any mappings.. I don't have access to a Mac tho.

Also, https://github.com/spf13/spf13-vim/issues/534 seems to be a duplicate.

**Comment by johntyree** [comment]
It appears I already have this commented out in my own, which I use on mac with no problem. That said, I don't use the home and end keys.

Personally, I think remapping this is terrible and it should be taken out. At the very least, it should wrapped in a variable in `.vimrc.before` with a good comment so that it's obvious what's happening and it can be easily disabled.

**Comment by johntyree** [comment]
I also don't use autoclose, if that's relevant.

**Comment by rekendahl** [comment]
I tested to comment out these lines as well and it makes open/close so much faster. 

I don’t like that mapping for screen is on by default especially when we now now it causes performance issues (perhaps when you don’t have screen installed?). I use TMUX and not screen.

I would suggest making these line an opt-in. I.e disable it by default and have uses enable it in their “local” file. 

I don’t have time to create a pull request today as I’m heading out but can do so on Monday unless someone else can do it earlier

/Robert

**Comment by johntyree** [comment]
@rekendahl still able to whip up a PR for this this week?

**Comment by rekendahl** [comment]
Yeah. I can get to it tomorrow sometime.

Robert

**Comment by rekendahl** [comment]
Added pull request #559 that solves this issue

**Comment by rekendahl** [comment]
This  issue is merged and can be closed

**Comment by adambiggs** [comment]
Thanks guys!

**Comment by ljani** [comment]
FYI: Just installed a clean-ish environment on Cygwin x64 and I'm seeing the lag again. Removed `vim-autoclose` and the lag is gone. So, my test earlier doesn't seem to be valid..

EDIT: oh and `vim-autoclose` seems to toggle the replace mode at the start randomly.

**Comment by Chun-Yang** [comment]
try to remove https://github.com/spf13/spf13-vim/blob/eeb5c57451ca945d8523aaad1851eb376b427f06/.vimrc#L64
