### ISSUE TITLE
Consider using The Silver Searcher as an alternative to Ack.vim

### ISSUE THREAD

**Issue by charl** [spf13/spf13-vim#512]
https://github.com/ggreer/the_silver_searcher
https://github.com/rking/ag.vim

"A code-searching tool similar to ack, but faster.
http://geoff.greer.fm/2011/12/27/the-silver-searcher-better-than-ack/"

**Comment by teasp00n** [comment]
This is already supported. If you have ag installed (and remove ack actually as I believe this is checked first) it will use ag as the command behind the ack plugin.

**Comment by spf13** [comment]
We should probably flip that. Check for ag first and use that if both are available. Ag is great.

**Comment by spf13** [comment]
This has happened. Ag is now the default.
