### ISSUE TITLE
[plugin bundle] vim-coloresque

### ISSUE THREAD

**Issue by novalore** [spf13/spf13-vim#522]
I'm enthusiastically using your configs and I'm quite happy with them.
The only lacking feature I could find (it wasn't easy :-) ) is colour highlight in css files.

An excellent (and fast) plugin for that is [gorodinskiy/vim-coloresque](https://github.com/gorodinskiy/vim-coloresque).

Have a look at it.

**Comment by spf13** [comment]
Looks good. Please Send a PR.
