### ISSUE TITLE
Replace gocode plugin

### ISSUE THREAD

**Issue by casimir** [spf13/spf13-vim#525]
This plugin (https://github.com/Blackrush/vim-gocode) just got an update for Go 1.2. It seems to be a fork from the original one (https://github.com/nsf/gocode) and is much more active.
I didn't have the occasion to test it yet but it seems promising. It provides a Vundle package too (https://github.com/Blackrush/vim-gocode#vundle).

**Comment by spf13** [comment]
I actually was playing with this last night. I'll push it now.

**Comment by casimir** [comment]
That was quick! By the way thanks for your work.
