### ISSUE TITLE
with the latest installer, the shortcode '<C-k>' for neocomplcache does not work correctly again.

### ISSUE THREAD

**Issue by yssource** [spf13/spf13-vim#526]
1) With the latest installer, the shortcode '<C-k>' for neocomplcache does not work correctly again.
2) Is it possible to combine neocomplcache and ultisnips working together? if it is ok, that would be very appreciated.

**Comment by reverland** [comment]
Faced with the same problem about 1

add 

``` bash
imap <C-k> <Plug>(neosnippet_expand_or_jump)
smap <C-k> <Plug>(neosnippet_expand_or_jump)
```

to vimrc.local works for me temperately

**Comment by spf13** [comment]
Can someone make a pull request to add this fix in?

Best,
Steve

-- 
Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

On January 13, 2014 at 8:32:28 PM, reverland (notifications@github.com) wrote:

add
Faced with the same problem about 1

imap <C-k> <Plug>(neosnippet_expand_or_jump)
smap <C-k> <Plug>(neosnippet_expand_or_jump)
to vimrc.local works for me temperately

**Comment by yssource** [comment]
a workaround to fix the issue 1),  
just adding this following line in file .vimrc.before.local 
let g:spf13_noninvasive_completion = 1

**Comment by bronzehedwick** [comment]
The let g:spf13_noninvasive_completion = 1 fix doesn't work for me :/ An error came up once about a conflict in snippet plugins, but it didn't stay on screen long enough to get any more details.

**Comment by spf13** [comment]
:messages may show you the error. 

Steve Francia
spf13.com
@spf13

**Comment by yssource** [comment]
I have tried to fix this issue 1 in my fork 'https://github.com/yssource/spf13-vim.git'.

**Comment by jtuz** [comment]
@yssource  It works for me!  thanks for your help

**Comment by spf13** [comment]
Submit a PR please.

Best,
Steve

-- 
Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

On January 16, 2014 at 10:37:26 AM, jimmy.m.gong (notifications@github.com) wrote:

I have tried to fix this issue 1 in my fork 'https://github.com/yssource/spf13-vim.git'.
