### ISSUE TITLE
easytags?

### ISSUE THREAD

**Issue by wolfgangpfnuer** [spf13/spf13-vim#53]
should easytags be included or not?

```
" EasyTags {
    let g:easytags_cmd = 'ctags'
" }
```

is there, but 

```
    Bundle 'xolox/vim-easytags'
```

is not.

**Comment by spf13** [comment]
No. Should remove that section from the config.

Steve Francia
@spf13

On Feb 16, 2012, at 7:50 AM, "Wolfgang Pfnür"
reply@reply.github.com
wrote:

**Comment by ghost** [comment]
Probably not the best place to ask but are tag files created automatically?

**Comment by wolfgangpfnuer** [comment]
install http://ctags.sourceforge.net/

ctags -R -a -f ~/.vimtags path/to/your/sources
ctags -R -a -f ~/.vimtags path/to/your-other/sources
...

-R for recursive, -a for append, -f for specifying the tags-file (~/.vimtags, this is already in the .vimrc here)

**Comment by spf13** [comment]
Tagbar automatically creates them when you open a file, but not for
the project in its entirety.

Steve Francia
@spf13

On Mar 7, 2012, at 8:02 AM, "Wolfgang Pfnür"
reply@reply.github.com
wrote:

**Comment by wolfgangpfnuer** [comment]
Maybe include a short ctags howto like I posted above into readme?
