### ISSUE TITLE
neosnippet-snippets cannot be found

### ISSUE THREAD

**Issue by xu-cheng** [spf13/spf13-vim#539]
Just install a fresh `spf13-vim`, get below error in vim.

```
neosnippet default snippets cannot be loaded.
You must install neosnippet-snippets or disable runtime snippets.
Press ENTER or type command to continue
```

![Imgur](http://i.imgur.com/luvmIYZ.png)

And it's odd that there's no such error in MacVim.

**Comment by abijr** [comment]
I've got this error too.

**Comment by tvanhens** [comment]
I've got this error as well. Fresh install on osx.

**Comment by abijr** [comment]
That erro stops if I add this line:

``` vim
let g:neosnippet#disable_runtime_snippets = 1
```

But I start getting this new error:

```
Error detected while processing function neosnippet#init#_initialize..<SNR>168_initialize_cache..neosnippet#commands#_make_cache..neosnippet#helpers#get_snippets_directory:
line    2:
E712: Argument of get() must be a List or Dictionary
```

Not sure what to do now.

**Comment by abijr** [comment]
After reading the code from neosnippets I found out that `g:neosnippet#disable_runtime_snippets` must be a dictionary. So adding to your `.vimrc.local` this line:

```
let g:neosnippet#disable_runtime_snippets = { "_": 1, }
```

Fixes the problem. It's either that or adding the default snippets from Shougo.
