### ISSUE TITLE
foldmethod=syntax

### ISSUE THREAD

**Issue by tschaume** [spf13/spf13-vim#54]
Hi,

Sorry in advance for filing this rather simple issue. However, I figured it might be of interest for other "black box users", too :-)
It seems like automatic folding via "set foldmethod=syntax" doesn't work. I put it in .vimrc.local but it seems to be ignored or collides with a different definition elsewhere. I assume the folding of .vimrc is based on manual markers.

How can get it working again?

Thanks

**Comment by spf13** [comment]
What language are you trying? A few of the language specific plugins may be overriding that value.

**Comment by tschaume** [comment]
I'm trying c++.

**Comment by sabonis** [comment]
Same issue here. 
I'm using javascript

**Comment by bronzehedwick** [comment]
This is a really old issue. @tschaume, @sabonis, is this still occurring, or can it be closed?

**Comment by tschaume** [comment]
I haven't used spf13-vim since I opened this issue, hence I can't really say. Sorry.

**Comment by ghost** [comment]
if it isn't fixed it can always be reopened, so closing

**Comment by sabonis** [comment]
Not a issue anymore.
