### ISSUE TITLE
on changing the app base directory ($HOME/.spf13-vim-3) 

### ISSUE THREAD

**Issue by ghost** [spf13/spf13-vim#548]
I was about to submit a PR that added `base_dir` to bootstrap.sh set to `$HOME/.spf13-vim-3` by default, (to match the `%BASE_DIR%` env var in the windows install scripts) but it seemed like this had already been previously the case with the endpath variable and was removed in this changeset https://github.com/spf13/spf13-vim/commit/7677bdaf86af1be8f8af9db960de8ac2311a4f18 . Is there any reason we can't shouldn't have this variable as long as we keep this: `endpath="$( cd "$( dirname "$0" )" && pwd)"`?

**Comment by spf13** [comment]
Looking at the bootstrap.sh from head, it appears that base_dir is being set still as endpath="$HOME/.$app_name-3" ... which becomes $HOME/.spf13-vim-3. The other line you reference has since been removed/replaced.

It looks like some consolidation & cleanup could be done.
