### ISSUE TITLE
LaTeX symbols

### ISSUE THREAD

**Issue by kli6891** [spf13/spf13-vim#55]
After installing this, characters in LaTeX are actually substituted in. (e.g. the command \alpha appears as the literal character α in my gvim window).

I would like to turn this off. Which plugin is controlling this?

**Comment by spf13** [comment]
I'm not sure on this one, it's certainly not any behavior I've intentionally included. I'm also not able to reproduce this on my machine. Are you sure it's spf13-vim doing this?

**Comment by kli6891** [comment]
Actually, nevermind. I just installed a fresh copy of spf13-vim to test this, and it seems to be something else that's causing the issue.

**Comment by dapicester** [comment]
Today I got this problem too, it's `neosnippet`, here is how to disable symbols substitution:
http://stackoverflow.com/questions/18160953/disable-latex-symbol-conversion-in-vim/18161073?noredirect=1#18161073
