### ISSUE TITLE
How to disable one specific plugin

### ISSUE THREAD

**Issue by tchar** [spf13/spf13-vim#553]
Hello lets say i want to disable neocomplcache and the snipsets and add the YouCompleteMe plugin.
How can i do that without redefining all the groups i want.

Or is there a command to show me which groups are currently active?

Thank you.

**Comment by reem** [comment]
Usually you would use the UnBundle function like so:

~/.vimrc.local

```
UnBundle 'Twinside/vim-haskellConceal'
```

However, neocomplcache is a little more complicated and disabling it means you will have to disable the neocomplcache group and enable the youcompleteme group.

You should, then, in your ~/.vimrc.before.local, add this line:

```
let g:spf13_bundle_groups=['general', 'youcompleteme', 'programming', 'php', 'ruby', 'python', 'go', 'twig', 'javascript', 'haskell', 'html', 'misc', 'scala']
```

All I've done is take line 94 of .vimrc.bundles and replace neocomplcache with youcompleteme.

**Comment by johntyree** [comment]
@tchar, this is the right answer. Closing this.
