### ISSUE TITLE
transparency error 

### ISSUE THREAD

**Issue by sergiovier** [spf13/spf13-vim#56]
I've installed a new copy of 3.0 and when I start vim in my gnome-terminal, this warning appears each time:

CSApprox skipped; terminal only has 8 colors, not 88/256
Try checking :help csapprox-terminal for workarounds

GNOME Terminal just evades detection. That error was fixed putting in ~/.vimrc.local "set t_Co=256"

**Comment by spf13** [comment]
I believe this has been resolved. If it is an issue still then please reopen.
