### ISSUE TITLE
vim (but not gvim) opens with light solarized

### ISSUE THREAD

**Issue by reem** [spf13/spf13-vim#569]
I have no earthly idea why. My background is set to dark, and changing line 148 of .vimrc to something like `color molokai` loads that colorscheme properly. To reiterate, solarized is loaded, just the light instead of dark version.

To add to my confusion, gvim has no such problems and loads fine. Additionally, if I do :color solarized as soon as I open vim it changes to the correct (dark) version.

I have no other colorscheme or background related lines in any of my .local files and this error was not present until I updated spf-13 yesterday.

Any help would be much appreciated.

**Comment by tonglil** [comment]
I believe I have the same issue, vim with colorscheme solarized is now white instead of the right color.
Tried setting background=dark.

**Comment by reem** [comment]
Ok, I've done a bit more tinkering and have identified the culprits:

.vimrc, Vim UI, line 144:

```
        let g:solarized_termcolors=256
```

These settings do lead to a correct loading of the dark solarized colorscheme, however, this is the degraded, 256 color version of the solarized colorscheme. 

:h solarized_termcolors yields:

```
------------------------------------------------
g:solarized_termcolors=   256     |   16        *'solarized_termcolors'*
------------------------------------------------
The most important option if you are using vim in terminal (non gui) mode!
This tells Solarized to use the 256 degraded color mode if running in a 256
color capable terminal.  Otherwise, if set to `16` it will use the terminal
emulators colorscheme (best option as long as you've set the emulators colors
to the Solarized palette).

If you are going to use Solarized in Terminal mode (i.e. not in a GUI
version like gvim or macvim), **please please please** consider setting your
terminal emulator's colorscheme to used the Solarized palette. I've included
palettes for some popular terminal emulator as well as Xdefaults in the
official Solarized download available from:
http://ethanschoonover.com/solarized . If you use Solarized without these
colors, Solarized will by default use an approximate set of 256 colors.  It
isn't bad looking and has been extensively tweaked, but it's still not quite
the real thing.
```

Note the **please please please**. I use iTerm2 and have downloaded the iterm2 colorscheme from the website in the help text and am currently using it. However, running solarized using solarized_termcolors=16 causes it to load the light version of solarized on boot - but when I do :color solarized again it loads the high-quality version of dark solarized instead of the degraded version.

Hopefully some of this is helpful to someone who knows a bit more than me. I'm not really sure what to do from here, because I'd really like to have the best version of dark solarized instead of the degraded version, but having to :color solarized every time I launch vim is quite annoying.

**Comment by reem** [comment]
This can be fixed by unbundling `godlygeek/csapprox` as detailed in #579.

**Comment by afterhill** [comment]
@reem I unbudled this plugin, but this issue is still existing. When I typed "Vim xxx.py" in the command line, it will always show the wrong color.

**Comment by ghost** [comment]
i know this was awhile ago, but are you still having this problem @MengJueM . It could be simply that you didn't clear out the .vimviews directory

**Comment by ghost** [comment]
@MengJueM : please open another issue if you can still reproduce this. The csapprox unbundling should have fixed it.
