### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by frankmullenger** [spf13/spf13-vim#57]
I had a problem with some dependency, wanted to revert back to my original .vimrc file (uninstall) but could not find it. 

According to this it should be called .vimrc.old somewhere?
https://raw.github.com/spf13/spf13-vim/master/bootstrap.sh

In the end had to replace .vimrc in spf13-vim... with a basic version I found here:
http://vim.wikia.com/wiki/Example_vimrc

**Comment by spf13** [comment]
On Thu, Mar 1, 2012 at 3:11 AM, Frank Mullenger <
reply@reply.github.com

> wrote:
> 
> I had a problem with some dependency, wanted to revert back to my original
> .vimrc file (uninstall) but could not find it.
> 
> According to this it should be called .vimrc.old somewhere?
> https://raw.github.com/spf13/spf13-vim/master/bootstrap.sh

The bootstrap file is very straightforward. It simply makes a copy of the
critical vim files with the extension .old. Not sure why you can't find it.
What are you doing to look for it?

> In the end had to replace .vimrc in spf13-vim... with a basic version I
> found here:
> http://vim.wikia.com/wiki/Example_vimrc

This is also the outdated version of spf13-vim. The current version (3.0)
is significantly better (though the install routine is nearly identical).

**Comment by frankmullenger** [comment]
I thought I could find the *.old files in the ~/.vim and ~/.vimrc folders but they have been changed into symbolic links?

I used something like this command to look for them:
    find ~/ -name *.old

**Comment by matthewmatician** [comment]
I never found any .old files. but I did find .vimrc.120503 and .vim.120503/ available when removing the old .vimrc and .vim/, I then just renamed these backups to their original names. Presto, everything is back to the way it was before.

**Comment by stephpy** [comment]
yes @matthewmatician that's how spf13-vim can be uninstalled.

A backup at each installation will copy your actually .vimrc and .vim at .vimrc.TIME .vim.TIME.

**Comment by variousauthors** [comment]
Except that spf13 creates a bunch of files. I think if you have an install script, you should provide an uninstall script.

**Comment by spf13** [comment]
Great idea, please feel free to write one and issue a pull request.  

I find that manually uninstalling is quite easy and obvious, but would be happy to include a well written uninstall script if someone is so inclined to write one.  

Best,
Steve

http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by taxilian** [comment]
if you were to elaborate on what the problem you ran into was, we'd also be happy to try to help you resolve that issue so you could use spf13-vim =]

**Comment by gprimosch** [comment]
Are there any instructions on how to uninstall spf13? I don't really see it in the README.markdown.

**Comment by spf13** [comment]
I wrote an uninstall script recently that is in the repo. It's not well
tested, but if you look at what it's doing you should be able to tell what
steps to take.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13
