### ISSUE TITLE
Using Term correct term colors but something is off

### ISSUE THREAD

**Issue by paulhkulla** [spf13/spf13-vim#573]
Using urxvt and the following (only background slightly modified) .Xresources colors (defaults provided by solarized):
https://gist.github.com/paulhkulla/9302782

Take a look at what my terminal VIM looks like: http://imgur.com/r6qePrN

As far as I understand my VIM is using the 16 color palette from .Xresources but I just cannot figure out why the colors don't match with Solarized. Also how can one force the syntax highlighting match dark/light in this scenario (as they are different). In my .vimrc I am not setting a colorscheme btw. Shouldn't the colors in .Xresources look like solarized scheme anyway? If not is there perhaps a .Xresources color palette that would closely resemble that (so as to bypass all the issues with using the actual color scheme in terminal URXVT vim)

Perhaps you can shed some light and provide some tips. Thanks

**Comment by ghost** [comment]
try updating to the latest version, see if that helps.

**Comment by ghost** [comment]
please try again . some changes were made a few months ago (removing the csapprox plugin) that might have fixed this for you.

**Comment by ghost** [comment]
closing due to lack of response
