### ISSUE TITLE
csapprox takes 150+ ms to startup

### ISSUE THREAD

**Issue by reem** [spf13/spf13-vim#579]
Unbunlding godlygeek/csapprox leads to a significant (700+ ms -> 547 ms) decrease in loadtime for vim.

Using `vim --startuptime` you can see that this sourcing this plugin takes more time than sourcing `.vimrc.bundles`.

Interestingly enough, unbundling this also fixes #569.

**Comment by ghost** [comment]
hmm. should this really be bundled by default?

**Comment by spf13** [comment]
Let's remove it from the default. I think it's been more trouble than good for the majority of users.

**Comment by ghost** [comment]
Im wondering if we should apply semantic versioning to sfp13-vim. It seems like removing something that some folks probably depend on is not such a good idea since we don't have a real good way to warn them that this happened.

Alternatively we could keep a good changelog file and fetch it during bootstrap.sh

**Comment by spf13** [comment]
I prefer the change log approach. It's not like it's typical software.. The best job we can do would be invisible... it would just work. Since there aren't typical releases (and since packages upgrade all the time). I only reserve major version numbers for new package systems / approaches.

**Comment by ghost** [comment]
so actual changelog file or enforce a certain style of commit messages.

**Comment by ghost** [comment]
@spf13 : how do you think the changelog should work? when should the user see it?

**Comment by spf13** [comment]
I think ideally it would happy as a preloading screen on install / upgrade.. whenever the shell script is run. 
It would be pretty easy to distribute a file (could even be a plugin) and have that sourced/displayed on install. 

The file could have some basic instructions as well as the changlog and would be displayed in Vim.

I haven't given the mechanics a ton of thought, but I think the experience should be pretty unintrusive... only happening after the user did an install / upgrade seems like the right time.

**Comment by spf13** [comment]
Also let's move this discussion to a different thread... it have very little directly to do with csapprox.

**Comment by ghost** [comment]
csapprox was unbundled in https://github.com/spf13/spf13-vim/commit/c11055ed29f81f1a232c8c6abcdafdab7209cedf
