### ISSUE TITLE
error when opening python files

### ISSUE THREAD

**Issue by neerajsingh** [spf13/spf13-vim#58]
i have done an automatic install using curl on osx. i get the following error upon opening any python file...any suggestions on how to fix this and get rid of this startup error messages?

---

Error detected while processing /Users/ns/.spf13-vim-3/.vim/bundle/python-mode/ftplugin/python/pymode.vim:
line   48:
E121: Undefined variable: g:pymode_doc
E15: Invalid expression: g:pymode_doc
line   64:
E121: Undefined variable: g:pymode_lint
E15: Invalid expression: g:pymode_lint
line  103:
E121: Undefined variable: g:pymode_rope
E15: Invalid expression: g:pymode_rope
line  123:
E121: Undefined variable: g:pymode_run
E15: Invalid expression: g:pymode_run
line  139:
E121: Undefined variable: g:pymode_breakpoint
E15: Invalid expression: g:pymode_breakpoint
line  151:
E121: Undefined variable: g:pymode_utils_whitespaces
E15: Invalid expression: g:pymode_utils_whitespaces
Error detected while processing /Users/ns/.spf13-vim-3/.vim/bundle/python-mode/after/ftplugin/python.vim:
line    2:
E121: Undefined variable: g:pymode_rope
E15: Invalid expression: g:pymode && g:pymode_rope && g:pymode_rope_vim_completion

---

**Comment by arcollector** [comment]
I have the same problem, have you find any solution for it??

**Comment by siberianluck** [comment]
I came across this issue and for me it was caused by vim not being compiled with python support.  I followed <a href="http://iamnearlythere.com/installing-vim-python-ruby-support-homebrew">this tutorial</a> and it was resolved for me.

**Comment by neerajsingh** [comment]
its been a while so i don't really remember how i solved this.
i think i added the following values(see link below) to the .vimrc.local file

https://github.com/klen/python-mode

**Comment by tehmaspc** [comment]
@siberianluck - cool; i needed that info; worked.

**Comment by kurten** [comment]
I fixed this by add let g:pymode_doc = 1 and  let g:pymode_lint = 0 and let g:pymode_rope = 0 under "PyMode {  in .vimrc file.
For more infomation you can find in this file https://github.com/klen/python-mode/blob/master/plugin/pymode.vim

**Comment by abdarraafi** [comment]
What @siberianluck mentioned applied to me, too: https://github.com/spf13/spf13-vim/issues/58#issuecomment-5504406 

While waiting for Vim to compile with Python enabled, I discovered an easier solution for me: 

``` sh
aptitude install vim-nox
```

`vim-nox` is a Debian (and thus Ubuntu and other ripoff) package of Vim with scripting languages enabled: http://packages.debian.org/stable/vim-nox

You can check if your Vim supports Python using this (you should see a line with `+python` in it as a result):

```
vim --version | grep +python
```
