### ISSUE TITLE
Double completion popup w/ neocomplete

### ISSUE THREAD

**Issue by TFenby** [spf13/spf13-vim#581]
When using neocomplete, when the popup window comes up, hitting escape will cause a second popup window of a different size (and sometimes with different completions) to pop up, requiring two more presses of the escape key to get out of insert mode.

Here's a video of what I mean: https://asciinema.org/a/8151

(Would have put in a gif instead, but I couldn't find anything to convert screencasts to gifs without X.)

This doesn't happen when running neocomplete by itself.

**Comment by Shougo** [comment]
You should use `neocomplete#smart_close_popup()` to close popup.

``` vim
inoremap <expr><C-y>  neocomplete#close_popup()
```

**Comment by TFenby** [comment]
I don't know if both popups are created by neocomplete. Sometimes they have different contents. Is there a way for me to find out which plugin created a popup?

Also, Neocomplete by itself doesn't have this issue.

**Comment by Shougo** [comment]
> I don't know if both popups are created by neocomplete. Sometimes they have different contents. Is there a way for me to find out which plugin created a popup?

To close popup, you must use neocomplete functions.  Because neocomplete does not know if it is popup close.
I don't know spf13-vim mappings configure.  But I think it have problem for it.
