### ISSUE TITLE
How to disable the automatic closing brackets?

### ISSUE THREAD

**Issue by fernandoferreira-me** [spf13/spf13-vim#588]
In my personal opinion this behaviour slows me down =/

**Comment by jonuts** [comment]
Put `let g:autoclose_on = 0` in your .vimrc.local

**Comment by ghost** [comment]
@fguimara : can you close this now then?

**Comment by ghost** [comment]
added to FAQ  page https://github.com/spf13/spf13-vim/wiki/faq

**Comment by pritambaral** [comment]
`let g:autoclose_on = 0` no longer works. From a prelimirary look, it seems like `spf13-vim` is no longer using `vim-autoclose`. I couldn't find any way to disable autoclosing now.

**Comment by dancompton** [comment]
You're right.  spf13-vim now uses https://github.com/jiangmiao/auto-pairs

Update: You can disable it in your .vimrc.local via:

```
   let g:AutoPairs = {}
```

I attempted to remove the plugin via:

```
echo UnBundle \'jiangmiao/auto-pairs\' >> ~/.vimrc.bundles.local
```

and ended up receiving errors like 

```
Unknown function: AutoPairsInsert
Invalid expression: AutoPairsInsert('"')
```

even after running BundleClean!

Edit:  You need to clear your .vimviews directory
