### ISSUE TITLE
Nerdtree and statusbar problems

### ISSUE THREAD

**Issue by sbucek** [spf13/spf13-vim#59]
Hi,  firstly I want to thank you for the awesome 3.0 version  of your wonderful vim-distro, but I have some cosmetic issues I would like to get rid of:

1.) My statusbar looks like this, with a  ^B instead of the pipe sign.
http://i43.tinypic.com/551jdz.png

2.) When I doubleclick on a filename in the NerdTree window the following error occurs.
http://i44.tinypic.com/2942ezn.png
- I'm not able to open maps in nerdtree when  clicking on them and the plus sign next to the directory name is  gone. 

PS: 

I'm using Debian.

UPDATE:

2.) Seems to be a NerdTree bug.

**Comment by spf13** [comment]
On Fri, Mar 2, 2012 at 12:49 PM, Simon Bucek <
reply@reply.github.com

> wrote:
> 
> Hi,  firstly I want to thank you for the awesome 3.0 version  of your
> wonderful vim-distro, but I have some cosmetic issues, I would like to get
> rid of:
> 
> 1.) My statusbar looks like this, with a  ^B instead of the pipe sign.
> http://i43.tinypic.com/551jdz.png
> 
> Can you try a different font?
> 
> 2.) When I click on file in NerdTree window the following error occurs.
> http://i44.tinypic.com/2942ezn.png
> - I'm not able to open maps in nerdtree when  clicking on them and the
>   plus sign next to maps is  gone.
> 
> Seems like a bug with NerdTree. I'd file a ticket there.

For most Vim users the mouse is not a very common tool.
When navigating using the keyboard the "c" key will change to that
directory in NerdTree. "o" will open it.

**Comment by sbucek** [comment]
1.) I've tried all the different fonts, removed my vimrc.local, but with no success. Pipe symbol still shows up as ^B even in terminal. 
2.) Ticked is filed.

**Comment by BjornW** [comment]
@buceks Is this issue solved for you?

**Comment by sbucek** [comment]
I've repleaced the NerdTree git package with the one from the vim plugins homepage and it works perfectly.

But the ugly ^B in the statusbar instead of the pipe symbol still remains. Dunno how to solve it...

**Comment by sbucek** [comment]
I've repleaced the NerdTree git package with the one from the vim plugins homepage and it works perfectly.

But the ugly ^B in the statusbar instead of the pipe symbol still remains. Dunno how to solve it...
