### ISSUE TITLE
The numeration of files in vim-airline is wrong

### ISSUE THREAD

**Issue by tonykevin** [spf13/spf13-vim#592]
How I can change the file numbering (vim-arline), when I start VIM; the first file is assigned the label 1: index, then when I open the second file is labeled
3: styles.css.
case:
![issue](https://cloud.githubusercontent.com/assets/3784449/2638991/6f554498-beba-11e3-9fb5-6456e62720e2.png)

**Comment by spf13** [comment]
It’s just listing your buffers. Type :buffers to see them all. Not sure why 2 isn’t listed. Probably is being used by a plugin (nerd tree, ctrl p). Try opening files the normal way (:e file) to see if the second buffer is fine there.

Best,
Steve

-- 
Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by tonykevin** [comment]
I have tried and tested the solution, this is correct. It possible disable the list of buffers of ctrl p and nerd tree in the vim-airline?

**Comment by spf13** [comment]
It's not possible. vim-airline is just reporting the vim buffers (a core feature). Tons of plugins use these buffers as it's the only way to show a side or bottom window.
