### ISSUE TITLE
split windows moves simultaneously when go down or up

### ISSUE THREAD

**Issue by pacuna** [spf13/spf13-vim#596]
When I have n vertically split windows, all move together when I go down or up on one of them (using j/k). Is this normal behaviour? if it's normal how can I disable this?
thanks.

**Comment by ybc37** [comment]
I'm not sure if I understood the question correctly ;)
But take a look at the following lines in the spf13-vimrc:

``` viml
    " Easier moving in tabs and windows
    " The lines conflict with the default digraph mapping of <C-K>
    " If you prefer that functionality, add the following to your
    " .vimrc.before.local file:
    "   let g:spf13_no_easyWindows = 1
    if !exists('g:spf13_no_easyWindows')
        map <C-J> <C-W>j<C-W>_
        map <C-K> <C-W>k<C-W>_
        map <C-L> <C-W>l<C-W>_
        map <C-H> <C-W>h<C-W>_
    endif
```

`<C-W>_` maximizes the window. If that's the behavior you don't like, you can just remap it in your `.vimrc.local`:

``` viml
map <C-J> <C-W>j
map <C-K> <C-W>k
map <C-L> <C-W>l
map <C-H> <C-W>h
```

**Comment by pacuna** [comment]
sorry, I wasn't clear enough. My problem is that when I scroll on a window using j/k all other windows also scroll together. Is that normal? I don't know if it's a problem with my console, or VIM, or spf13. Thanks!

**Comment by ybc37** [comment]
hmmm...can't reproduce this issue (tested with both vim and gvim on Linux).
Maybe `vim -u NONE` will help you (it will load vim without any initializations -> without plugins and spf13 config). So you can verify if it's a problem with your console.

**Comment by kew-l** [comment]
Try `:set noscrollbind`

**Comment by pacuna** [comment]
@kevinwaddle thank you! that did the trick.
