### ISSUE TITLE
Problem: residual key mapping after uninstalling a bundle.

### ISSUE THREAD

**Issue by xu-cheng** [spf13/spf13-vim#602]
I found that there are residual key mapping after I uninstall a bundle. And I'm not quite sure that it's spf13-vim causing this. Is there any cache created by spf13-vim?

**Comment by xu-cheng** [comment]
Under the advice of reddit, I run the command `:verbose map <YourMapping>` to find where is the mapping from. I found it comes from `~/.vimviews/`

```
 _ll          @:Latexmk<CR>
     Last set from ~/.vimviews/=+private=+tmp=+test.tex=
```

So I think these caches should be removed during `:BundleClean`.

**Comment by louy2** [comment]
Have you resolved this? If not I suggest you move it to the [Vundle](https://github.com/gmarik/vundle) repo since it looks like a upstream bug.

**Comment by xu-cheng** [comment]
@louy2 I solved this, see my last comment. Solution is manually clean the `~/.vimviews/` folder.

**Comment by ljani** [comment]
Kind of offtopic, but anyway, I don't want to create another issue yet:
Would it be good to have `:BundleClean` (and `:BundleInstall`?) to empty `~/.vimviews/`? Many issues are solved by cleaning the directory..

**Comment by chrischoy** [comment]
thanks it worked!
