### ISSUE TITLE
golang syntax highlighting does not work with vim-go

### ISSUE THREAD

**Issue by pyanfield** [spf13/spf13-vim#608]
Just add 

```
    Bundle 'fatih/vim-go'
    Bundle 'Valloric/YouCompleteMe'
```

on my `.vimrc.bundles.local`, everything is fine,except syntax highlighting and auto complete. But I can use commands e.g`:GoRun`.

**Comment by spf13** [comment]
Instead of putting the bundles in your .local file, please add go to the bundle groups list so the additional configuration associated with that bundle is also included.

**Comment by pyanfield** [comment]
just need to add "go" in `.vimrc.bundles` line 94, right? `let g:spf13_bundle_groups=['general', 'writing', 'neocomplcache', 'programming', 'php', 'ruby','python', 'twig', 'javascript', 'html', 'misc','go']`
then run `:BundleInstall` and `fatih/vim-go` will be added automatically.

But the highlighting is still not work for me? Do I miss something?
