### ISSUE TITLE
Vundle is deprecating `Bundle` for `Plugin`

### ISSUE THREAD

**Issue by corburn** [spf13/spf13-vim#609]
https://github.com/gmarik/Vundle.vim/blob/v0.10.2/doc/vundle.txt#L372-L396

**Comment by mikedfunk** [comment]
+1 Someone should also rename UnBundle to UnPlugin or something

**Comment by spf13** [comment]
To make upgrading to the latest vundle possible for people we shouldn't change the name we reference for a while. 

Agree it should become unplugin while still supporting unbundle for a while.

**Comment by diraol** [comment]
Repeated issue ( #603 )?
