### ISSUE TITLE
Removing trailing whitespaces and ^M chars does not work for JAVASCRIPT file.

### ISSUE THREAD

**Issue by lihuazhang** [spf13/spf13-vim#61]
Hi
The line:
 autocmd FileType c,cpp,java,php,js,python,ruby autocmd BufWritePre <buffer> :call setline(1,map(getline(1,"$"),'substitute(v:val,"\s\+$","","")'))

does not work for JAVASCRIPT file.

But when I change js to javascript:
 autocmd FileType c,cpp,java,php,javascript,python,ruby autocmd BufWritePre <buffer> :call setline(1,map(getline(1,"$"),'substitute(v:val,"\s\+$","","")'))

It works.

I use mac 10.7.3 vim 7.3

**Comment by spf13** [comment]
Can you fork and submit a pull request please?

**Comment by spf13** [comment]
Closed with pull request 62
