### ISSUE TITLE
set nospell in .vimrc.local has no effect

### ISSUE THREAD

**Issue by ma0ho** [spf13/spf13-vim#614]
I'm trying to disable spell checking by adding `set nospell` to my .vimrc.local but that has no effect. Other options in this file do what they should - therefore I assume it's loaded. If I type `:set nospell` while editing a file it works - but I want to disable it globally. Any suggestions?

**Comment by ma0ho** [comment]
Ok, I found it.. I did not consider the .vimviews where the state for each file is stored. Just removed everything it and all is fine.. Sorry for the confusion.

**Comment by 90arther** [comment]
@ma0ho Hi, I met the same program.  where is the .vimviews file please?

**Comment by 90arther** [comment]
wow, I found it. Thank u.

**Comment by 1yndonn3u** [comment]
➜  ~ cd ~/.vimviews
➜  .vimviews pwd
/Users/$USER/.vimviews
➜  .vimviews ls
~=+Documentsxxxxx
➜  .vimviews


delete these files !
