### ISSUE TITLE
Syntax Error during update with curl

### ISSUE THREAD

**Issue by raratiru** [spf13/spf13-vim#615]
It has been for some weeks now.
When I run:`curl https://j.mp/spf13-vim3 -L -o - | sh`

I receive the following error:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147  100   147    0     0    139      0  0:00:01  0:00:01 --:--:--   139
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100   226  100   226    0     0    104      0  0:00:02  0:00:02 --:--:--   104
sh: line 1: syntax error near unexpected token `newline'
sh: line 1: `<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">'
```

The alternative method of updating is working fine.

**\* Update ***

The same error appears when using `curl https://j.mp/spf13-vim3 -L > spf13-vim.sh && sh spf13-vim.sh`.

Updates are somehow disabled. I will try to reinstall.

I am running on Gnome/Fedora 20.

**Comment by hasmo** [comment]
I have the same problem. Centos 6.5.

Edit: "curl http://j.mp/spf13-vim3 -L -o - | sh"     works as a quick fix.

**Comment by raratiru** [comment]
Actually I am unable to install or update, using all the relevant commands provided at the Readme file or the quick fix `curl http://j.mp/spf13-vim3 -L -o - | sh`.

git: 1.9.3-1
vim: 2:7.4.179-1
OS: Gnome/Fedora 20

**Comment by ragingdave** [comment]
I have used the same command since I started and have never had an issue of this nature. The original call I used and use now is `curl https://j.mp/spf13-vim3 -L -o - | sh` I actually just had to reinstall today, with no issues on centOS 6 box.

**Comment by raratiru** [comment]
After applying twice the above command, the update was successfully accomplished on all my boxes.

However, when trying to re-update, the same error is generated.

Diffucult to understand what happens!

**Comment by ragingdave** [comment]
just ran the same command to update a machine of mine and no issues with that, not really sure what the issue is for you? This particular update was run on:
MacOSX 10.9
git: 1.8.5.2
vim: 7.3
curl: 7.30.0

the centOS6 box was:
git: 1.8.5.1
vim: 7.4
curl: 7.21.1

All ran flawlessly

**Comment by raratiru** [comment]
I have just updated successfully on both my boxes. The first one with the first try. The second one with the third try. 

When I rerun the command on any box, the error appears, no matter what.

I can say that it "partially" or  "randomly" works. 

I will try on a third box, in my work. However all of them are running on Fedora and -of course- it might be a Fedora bug.

git: 1.9.3-1
vim: 2:7.4.179-1
curl: 7.32.0
OS: Gnome/Fedora 20

Anyway, it is not a problem for me, as long as it performs an update once in a while. 

I will close this issue in a few days if I have nothing more to add.

Thank you for the communication.

**Comment by ljani** [comment]
So, what's the output if you do `curl https://j.mp/spf13-vim3 -L -o -`? I needed to add `-k` to get rid of the certificate validation.

**Comment by raratiru** [comment]
Actually, when the command is not working properly the output is the following:

```
$curl https://j.mp/spf13-vim3 -L -o -
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
```

Adding `-k` seems to be working for those couple of times I tried it. Would that be the issue?

**Comment by raratiru** [comment]
Seems that this was the solution. 

Thank you!
