### ISSUE TITLE
Zenburn colorscheme and python

### ISSUE THREAD

**Issue by ghostkadost** [spf13/spf13-vim#616]
I am used to zenburn colorscheme and I have the following setting in vimrc.local : 
---------8<----8<--------
colorscheme zenburn
set textwidth=80
---------8<----8<--------
While this works perfectly fine when I am editing a c file 
![c_output](https://cloud.githubusercontent.com/assets/1317952/3080604/0c6b1e9c-e4b3-11e3-9703-1db0b39a275c.png)

it does not work if I am editing a python file. 
![python_out](https://cloud.githubusercontent.com/assets/1317952/3080605/0c6e8546-e4b3-11e3-9df9-14a565369173.png)

I have installed spf13 using the standard installation method.

**Comment by ghost** [comment]
does it
1. work fine with zenburn scheme outside of spf13-vim
2. work fine on spf13-vim without zenburn

**Comment by spf13** [comment]
It may also be a problem of the prior color scheme being stored in the session for when you last opened that file. Does it work on a brand new python file?

**Comment by ghostkadost** [comment]
It worked on a brand new file. I then deleted the entry corresponding to this file in .vimviews directory and now zenburn theme correctly loads up. Thanks for the resolution.
