### ISSUE TITLE
Adding 

### ISSUE THREAD

**Issue by harikt** [spf13/spf13-vim#628]
In the https://github.com/spf13/spf13-vim/wiki/faq

>  How do disable auto close tags?
> Add let g:autoclose_on = 0 to your .vimrc.local file

Adding makes the right and left up arrows in vim non usable.

**Comment by ghost** [comment]
works fine here. i just tested it. using  fedora linux 20 with 

```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb 19 2014 15:11:09)
Included patches: 1-182
(rest snipped)
```

**Comment by harikt** [comment]
@jrobeson mine is 7.3. and yes it is a bit old .

**Comment by ghost** [comment]
that release is about 4 years old now. that might be the problem. can you try on another machine with 7.4?

**Comment by harikt** [comment]
Hm. no other machine currently.

Work / Home is same machine ;-) .

_Hari K T_

You can ring me : +91 9388 75 8821

http://harikt.com , https://github.com/auraphp ,
http://www.linkedin.com/in/harikt , http://www.xing.com/profile/Hari_KT

Skype  : kthari85
Twitter : harikt

**Comment by ghost** [comment]
Well perhaps 7.4 is a requirement. you could attempt to unbundle the autoclose bundle instead though.

**Comment by harikt** [comment]
Thank you @jrobeson . I will look into how I can unbundle it.

**Comment by spf13** [comment]
I don't think we should make 7.4 a requirement. 7.3 is still the default for a ton of systems and I like that spf13-vim works well on most centos boxes.. I think one of the big features is you can ssh into just about any vps, or virtual machine and install spf13-vim and it just works.  That said, we can't control it if individual plugins adopt a requirement of 7.4... which over time some certainly will. 

I think unbundling it is best in this situation.
