### ISSUE TITLE
move spf13-vim to a github organzation?

### ISSUE THREAD

**Issue by ghost** [spf13/spf13-vim#632]
This could be one way to help with #622. 

Is there anybody else who is interested in being involved on that?

**Comment by tebowy** [comment]
I am starting the summer break, so I could find some time to dig through open issues and close those that are stale or just ask for help

**Comment by tebowy** [comment]
Also, repositories can be redirected, so moving wouldn't broke current installations.

**Comment by spf13** [comment]
I'd rather not move it.. but I'm happy to give many more people access to commit and work with the issues. @jrobeson I gave you access this morning. Anyone else who wants access should ask (and show some effort deserving of commit access first).

**Comment by spf13** [comment]
Happy to discuss further, but I don't see a real difference between moving vs opening access towards solving the issue and moving brings up a bunch more complications.
