### ISSUE TITLE
linux install spf13-vim met strange error

### ISSUE THREAD

**Issue by metrue** [spf13/spf13-vim#633]
Hi Guys,

I have git installed and set it in the PATH.
but the installation still met this error, please help on this, thanks.
# 

✔] Setting up vim symlinks
trying to update vundle
From https://github.com/gmarik/vundle
- branch            master     -> FETCH_HEAD
  Already up-to-date.
  [✔] Successfully updated vundle
  [✔] Successfully cloned vundle
  Error detected while processing /remote/us01home41/huangmh/.vimrc.bundles:
  line   59:
  E107: Missing braces: vundle#rc()
  line   77:
  E492: Not an editor command:         Bundle 'gmarik/vundle'
  line   78:
  E492: Not an editor command:         Bundle 'MarcWeber/vim-addon-mw-utils'
  line   79:
  E492: Not an editor command:         Bundle 'tomtom/tlib_vim'
  line   94:
  E15: Invalid expression: ['general', 'writing', 'neocomplcache', 'programming', 'php', 'ruby', 'python', 'twig', 'javascript', 'html', 'misc',]
  E15: Invalid expression: ['general', 'writing', 'neocomplcache', 'programming', 'php', 'ruby', 'python', 'twig', 'javascript', 'html', 'misc',]
  line  103:
  E121: Undefined variable: g:spf13_bundle_groups
  E116: Invalid arguments for function count(g:spf13_bundle_groups, 'general')
  E15: Invalid expression: count(g:spf13_bundle_groups, 'general')
  Hit ENTER or type command to continue

**Comment by spf13** [comment]
Which version of vim are you using?

**Comment by metrue** [comment]
@spf13  vim7.4

since the I install vim7.4 without root permission.
so after vim7.4 installation, I alias vim to vim7.4.

**Comment by spf13** [comment]
Can you try reinstalling spf13-vim?

**Comment by ghost** [comment]
@metrue: please reopen if this isn't fixed now.
