### ISSUE TITLE
Some motion commands aren't working

### ISSUE THREAD

**Issue by mrthebob** [spf13/spf13-vim#641]
There are a few motion commands that aren't working in a stock install (Ubuntu Linux).  Namely:   c&lt;motion&gt;   and   d&lt;motion&gt;

And most specifically, the following:

cE, cB,  dE, dB

Thanks!

**Comment by spf13** [comment]
This is an Ubuntu problem. They ship with a crippled Vim. Please install the complete Vim package. 

http://docs.oseems.com/general/operatingsystem/ubuntu/install-vim
