### ISSUE TITLE
Copy paste between two terminals

### ISSUE THREAD

**Issue by bkuberek** [spf13/spf13-vim#645]
Sorry if I should asked this somewhere else. I could not find an answer anywhere else. I am vim noob as you might have noticed.

I have installed this awesome vim package on my remote servers as well my local mac

I am logged into 2 remote machines at once and I am trying to copy text from one machine into another. I am unable to do that.

Apparently, yanking the text does not place it on the clipboard. Also I am not sure how to configure that since I am using vim on a remote machine.

Please advise.

Thanks

**Comment by ghost** [comment]
there's no single way to manage copy to clipboard. so it's hard to provide generic instructions for how to configure it easily.  So it's likely you're going to have to do some googling.

**Comment by bkuberek** [comment]
k thanks
