### ISSUE TITLE
Runtime loading and unloading of bundles?

### ISSUE THREAD

**Issue by webmaven** [spf13/spf13-vim#646]
Does Vim/Vundle have the concept of 'profiles' or something similar? I am finding that I want slightly different sets of plugins or configuration when using Vim for writing prose vs. code vs. data (CSV, JSON, etc.), but I seem to be constrained to switching off features like spell-checking individually.

What I'd really like is something like `:profile prose` that would turn on the 'writing' bundle, switch the color scheme and font, and a few other tweaks. Subsequently `:profile code` would turn the writing bundle off, etc.

**Comment by spf13** [comment]
There isn't anything like this built in, but it wouldn't be very hard to do on your own..

If I wanted to do this I would actually have two different versions of spf13-vim installed each with a unique set of bundles and local files.

I would then run 
vim -u /path/to/prose/vimrc
or
vim -u /path/to/code/vimrc

**Comment by spf13** [comment]
There isn't anything like this built in, but it wouldn't be very hard to do on your own..

If I wanted to do this I would actually have two different versions of spf13-vim installed each with a unique set of bundles and local files.

I would then run 
vim -u /path/to/prose/vimrc
or
vim -u /path/to/code/vimrc

Then I'd automate that into some aliases in my .zshrc (or .bashrc) file.

**Comment by webmaven** [comment]
Hmm. That might work, but seems a bit heavy-handed. Can bundles at least be turned on and off at runtime?

If so, I might get a partial solution just by regrouping the plugins into slightly different bundles.

**Comment by ljani** [comment]
@webmaven: You should check out [NeoBundle](https://github.com/Shougo/neobundle.vim) and `:NeoBundleLazy`. There was some [talk about migrating to NeoBundle](https://github.com/spf13/spf13-vim/pull/408), but it seems to have stalled.

```
:NeoBundleLazy {repository} [[,{revision}] [,{options}]]
:NeoBundleLazy {repository} ,{revision}, {default} [,{options}]]
Registers a bundle, but doesn't add it to 'runtimepath'.

NeoBundleLazy 'The-NERD-tree', {'augroup' : 'NERDTree'}
NeoBundleSource The-NERD-tree

You can use it to load plugins for specific filetypes.

NeoBundleLazy 'Rip-Rip/clang_complete'
autocmd FileType c,cpp NeoBundleSource clang_complete
```

**Comment by webmaven** [comment]
@ljani, that looks _really_ close to what I am after. Is the runtime loading/unloading limited to being based on filetypes, or can the user trigger it on demand?

**Comment by ljani** [comment]
Sure you can trigger loading a bundle on demand by typing `:NeoBundleSource clang_complete`. There seems to be `:NeoBundleDisable clang_complete`, but I haven't tried that.

EDIT: oh, `:NeoBundleDisable` says following:

```
:NeoBundleDisable {name}... *:NeoBundleDisable*
Disables bundles specified by {name}. If a bundle is
disabled, its path will be removed from 'runtimepath'.
Note: This command must be executed before neobundle loads
the plugins(after |neobundle#end()|).
```

So, dynamic unloading doesn't really work..? I kinda expected that :)

**Comment by webmaven** [comment]
That's enough for me to want this.

If you can also define bundles of bundles, or load+unload multiple bundles
with a single command (ideally in a declarative fashion defining the target
set), that would be enough to transform Vim instantly from a prose writing
environment, to a code editor, to an IDE, and back, not to mention
enabling/disabling more specific programming language or framework related
plugins as well.

That would be truly _awesome_.
