### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git - on Windows

### ISSUE THREAD

**Issue by entrptaher** [spf13/spf13-vim#647]
I know bumping this won't solve anything, but as you can see the problem raises again. This time its in windows and I really can't use the whole spf13.  
I _can use_ the _gVim_ without any problem (a little bit slower than the usual), but the vim from cmd/console/cygwin or anything related brings me 

`fatal: Not a git repository (or any of the parent directories): .git`

I actually had to press any key to pass this error stage.

The color is disastrous. And direct `vim` command shows this problem and results into a white board.

![vim problem](https://cloud.githubusercontent.com/assets/8284972/3715913/8ab7c9da-15fa-11e4-8766-2353fdacf051.jpg)

To reproduce, I install spf13 in any way and just use any windows cmd/console/cygwin to enter `vim` and voila!

Now what?

**Comment by ghost** [comment]
sorry.. i've got no windows here. nothing i can do about that. maybe @spf13 does

**Comment by spf13** [comment]
The root problem is that your cygwin vim has completely different paths and variables than gVim on windows.

The goal for spf13-vim is and has always been to make the best cross platform Vim distribution. It works great in Windows, OSX and native Linux and other *nix flavors.  

Cygwin is a unique unix distribution which has loads of incompatibility issues... but in general provides value for many people. After years of frustratedly using it and running up against many of such issues I've concluded that cygwin is fundamentally flawed and that running linux/freebsd in a VM is far superior. 

Given that, I have no interest in personally making spf13-vim work with it. As I've said many times before, this is a community distribution, and I'd be happy if someone else took the initiative. 

For me the first place I'd start is to check all the environment variables and make sure they are set properly. I have no idea if cygwin identifies as Windows or *nix in vim. 

`vim -V` should be very helpful here. Additional this page on the vim wiki may also help http://vim.wikia.com/wiki/Category%3ACygwin .

**Comment by ljani** [comment]
I use vim on Cygwin (with spf-13) daily and it works fine. MinTTY is my terminal.

It's CSApprox requiring you to press enter. And that's shown because the normal Command Prompt doesn't support more than 16 colors, does it? I see you're using ConEmu and it should support more than 16 colors (according to the manual), but sadly I have no idea how to tell vim that. If you read the manual, there's [this](https://code.google.com/p/conemu-maximus5/wiki/AnsiEscapeCodes#Example_1:_Vim), no idea if it works or not.

Also, that's the reason the colorscheme is not working correctly either.

**Comment by entrptaher** [comment]
Problem solved after fresh installation and/or new user Creation.
Might helped if added in the wiki with additional context.
Will check what caused the problem.

**Comment by entrptaher** [comment]
I didn't install using/with Cygwin.
Works good on a fresh installation of windows 7 & windows 8, slower in
windows 8 though.
I checked the paths, wondering if it's the culprit.
it would helped if included in wiki/readme.

**Comment by entrptaher** [comment]
Vim version 7.2, 7.4, some others.

Tried gvim from installer. No hope!
Tried vim+cmd/conemu/console2. No hope!
Tried vim on Cygwin+conemu/mintty. Not working!

Giving up for now as no official wiki and workaround found and the
developer already in a lot of pressure.

Let this issue be closed until another windows person appears.

BTW, I'm not windows person, I love Linux as much as I hate it.

**Comment by liudonghua123** [comment]
I have faced the same problem, "-v" option doesn't help!
The following is the error message! (I also tried console2, same error message)

C:\Users\Liu.D.H>vim > d:/error
Vim: 警告: 输出不是到终端(屏幕)
fatal: Not a git repository (or any of the parent directories): .git

C:\Users\Liu.D.H>vim -v > d:/error
Vim: 警告: 输出不是到终端(屏幕)
fatal: Not a git repository (or any of the parent directories): .git

C:\Users\Liu.D.H>

**Comment by entrptaher** [comment]
I stopped using spf13 on windows because of those laggings+ some newer
problems. There must be some plugin causing the whole problem, I ended
up installing plugins on my own and it was never been a problem for me
onwards.
