### ISSUE TITLE
How to uninstall ?

### ISSUE THREAD

**Issue by antoniobrandao** [spf13/spf13-vim#648]
Sorry if it is a noob question. I am a vim noob!

**Comment by lijoantony** [comment]
There is an uninstall.sh script at the root of your ~/.spf13-vim-3 directory.
I have never tried it though.

**Comment by spf13** [comment]
Either use the uninstall script, or simply read it and follow the steps manually.

**Comment by fkzhao** [comment]
exec  ~/.spf13-vim-3 directory uninstall.sh，It's great!!
