### ISSUE TITLE
NERDCommenter not included by default??

### ISSUE THREAD

**Issue by haiyamicode** [spf13/spf13-vim#66]
NERDCommenter is mentioned in this github README homepage.
However, I notice that it isn't included in my installation, so it isn't installed by default right?
Why does it appear in the homepage? So misleading? Or that's the problem with my installation?

**Comment by lihuazhang** [comment]
Run bundleinstall again in vim.
It stops at "Bundle 'spf13/snipmate-snippets'
            " Source support_function.vim to support snipmate-snippets.
            source $HOME/.vim/bundle/snipmate-snippets/snippets/support_functions.vim " due to no support_functions.vim found at first.

**Comment by haiyamicode** [comment]
Thank you, I just rerun BundleInstall then it works now.
