### ISSUE TITLE
In markdown file all ' turn to ‘ or ’

### ISSUE THREAD

**Issue by poppinlp** [spf13/spf13-vim#665]
In file with suffix md or markdown, i can't input symbol ', it auto turn to ‘ or ’.
Need some help.

**Comment by bronzehedwick** [comment]
Hm, I am not able to reproduce the problem. Straight quotes stay straight in markdown files on my machine. Is there anything you've done to customize your setup outside of spf13?

**Comment by kevinushey** [comment]
I believe this behaviour is included as part of the `vim-textobj-quote` package, which is part of the `writing` bundle:

```
" Writing {
    if count(g:spf13_bundle_groups, 'writing')
        Bundle 'reedes/vim-litecorrect'
        Bundle 'reedes/vim-textobj-sentence'
        Bundle 'reedes/vim-textobj-quote'
        Bundle 'reedes/vim-wordy'
    endif
" }
```

You could check your `~/.vimrc.before.local` and see if you've specified it within the `g:spf13_bundle_groups` variable; you might prefer having it off.

**Comment by poppinlp** [comment]
@kevinushey 
That's really help. Thx.

**Comment by tonglil** [comment]
Is there a way to unbundle this one group? I don't know what all the other bundles are and don't want to risk miss including other bundles to just exclude this one.
