### ISSUE TITLE
Remove (unistal spf13-vim)

### ISSUE THREAD

**Issue by andrewmori** [spf13/spf13-vim#668]
Hi.

I was very keen to start using this, but after installation I can no longer edit files (even as root its tellling me its readonly) and I would like to simply go back to normal vim.

I just did a sudo apt-get autoremove vim
and then re-installed it, but I can still see it is spf13.

How can I remove spf13?

Thank you

**Comment by spf13** [comment]
There is an uninstall script in the github repository.
