### ISSUE TITLE
highlighted text cannot be read

### ISSUE THREAD

**Issue by apoo** [spf13/spf13-vim#67]
Hi,
I dont know why some of my variables and texts gets highlghted, could you please tell me which plugin does this? I would like to remove it because I cant read the variables!
http://i44.tinypic.com/anl9ar.png

Thank you

**Comment by spf13** [comment]
That's strange,  I've never seen that before. What Colorscheme are you
using?
Can you try other colorschemes to check if it's an issue with that
colorscheme?

**Comment by apoo** [comment]
I was using molokai but I just changed it to ir_black and I get those highlighted text in RED!!! :D
http://i39.tinypic.com/xunib.png

**Comment by apoo** [comment]
I dont think its a colorscheme issue, I can see those highlighted text in all colorschemes but in different colors!

**Comment by grzlus** [comment]
I have sama problem. But when I open gvim I see that this is underlined with dashes. Could I disable that underline?

**Comment by spf13** [comment]
I haven't been able to reproduce.

Can you give me more information about your environment?

What OS, Version, Vim version?

**Comment by grzlus** [comment]
FreeBSD 9.0, Vim 7.3 (latest from ports).  Only solarized theme works good (if I use solarized only tabs are red).

**Comment by apoo** [comment]
Its due to storing variables in sessions!! I tried to narrow it down what I am gonna do now is, removing bundle one by one to see what happens.

**Comment by apoo** [comment]
in some color schemes it draw undereline for those variables,txt or whatever (those that you have search before), in others it highlights the. 
its not highlight seach, i turned that off I could still see those highlighted texts

**Comment by grzlus** [comment]
Highlighting last searched value looks pretty good and that isn't problem. I have problem becouse in some languages (Ruby, Pascal (I'm student...), C++) I kave highlighted part od string, or name of procedure.

**Comment by apoo** [comment]
I meant the same thing!!!

**Comment by spf13** [comment]
Can you post a screenshot?

**Comment by grzlus** [comment]
I'm sorry for late. Here you are http://piklus.pl/screen.tar

**Comment by grzlus** [comment]
I found answer. I type `set nospell` and everything is fine now.

**Comment by apoo** [comment]
YOU saved me zillions of hours of going through each line of spf13!! Thank you Worked!!!

**Comment by apoo** [comment]
what does that line do? what does set spell do?

**Comment by grzlus** [comment]
Spell turn on spellchecking. I started removing some features from config and found that. I needn't that feature in my projects, so i turned that off. Also I don't like gvim, I preffer console.

**Comment by arsane** [comment]
seems even I set nospell, the vim still hightlight any word with a spell issue which make the vim unreadable.

**Comment by jamestomasino** [comment]
I'm seeing the same problem in the Mac terminal using ir_black. Highlighted words are getting styled incorrectly. Once the file is open, if I manually call: 'color ir_black' again, the problem disappears. Something seems to be affecting highlighting colors in one of the bundles.

Is there a post-bundle execution .vimrc file? I believe this problem could be worked around easily by delaying the color setting until then.

**Comment by spf13** [comment]
There's not, but that's a good idea. I'll see what I can come up with.

**Comment by heyimmowee** [comment]
set nospell worked for me too. Thank you very much

with set spell: http://oi48.tinypic.com/9gvcsj.jpg
with set nospell: http://oi45.tinypic.com/2lc3g2b.jpg

**Comment by ghost** [comment]
@arsane  Not only you should change set spell to set no spell,but also you should delete the last word spell in line 2 in .vimrc. this works for me.

sometimes it happens again, don't know why

**Comment by victoredwardocallaghan** [comment]
Same problem, set nospell fixes issue however does not seem to set it if I put it in .vimrc.local ?

**Comment by kbambridge** [comment]
I think something is saving the state of the previous vim session, thats why you don't see the update in files that you have edited before with the old configuration.  I just manually `:set nospell` when it comes up and it fixes the problems.  In new files though I don't have the issue, so I believe it is working.

**Comment by jamestomasino** [comment]
It's either ~/.vimviews or ~/.vimswap where the states are saved for previously opened files. You can blow away those folders to reset it.

**Comment by lumbric** [comment]
I think that this problem is caused by a terminal which does not support enough colors and a colorscheme which cannot deal with that in a good way. You might want to place something like this in your .vimrc or .vimrc.local:

```
highlight SpellBad ctermbg=0 ctermfg=1
```

**Comment by jmsegrev** [comment]
This solved the issue for me:
`autocmd VimEnter * set nospell`

**Comment by spf13** [comment]
In conclusion. Spell checking does exactly what you want it to, it highlights misspelled words. In programming you probably don't want this as many words aren't dictionary words. 

However the larger problem is that people are running vim with either terminals with limited colors or color schemes with poor support for limited colors. 

The comments above instruct people how to disable spell checking which will eliminated the highlighted words. Alternatively using a vim installation with support for lots of colors (gVim, macVim) will highlight the misspelled words in a less offensive manner.

**Comment by cocobear** [comment]
Use this config could be more comfortable , it will only check spell for txt type file.
    `au FileType txt setlocal spell spelllang=en_us`

**Comment by turkus** [comment]
> This solved the issue for me:
> `autocmd VimEnter * set nospell`

The best and not annoying solution which works.
