### ISSUE TITLE
Let vim-go manage gotags path for tagbar

### ISSUE THREAD

**Issue by moorereason** [spf13/spf13-vim#670]
I did a fresh install of spf13-vim today (new to golang and hugo!) and noticed that the tagbar didn't work properly with gotags.  I was seeing the same problem mentioned at https://github.com/fatih/vim-go/issues/157.  gotags is not in my system path, which is not a problem for vim-go.

The problem is that spf13-vim sets the `tagbar_type_go` variable in .vimrc ([line 626](https://github.com/spf13/spf13-vim/blob/3.0/.vimrc#L626)) when it should let vim-go manage it.  After deleting that setting, the vim-go tagbar integration works as expected.

**Comment by fatih** [comment]
I'm defining `g:tagbar_type_go` so I can use the custom `ctagsbin`. In vim-go it's defined like:

```
if !exists("g:tagbar_type_go")
    let g:tagbar_type_go = {
        \ 'ctagstype' : 'go',
        \ 'kinds'     : [
            \ 'p:package',
            \ 'i:imports:1',
            \ 'c:constants',
            \ 'v:variables',
            \ 't:types',
            \ 'n:interfaces',
            \ 'w:fields',
            \ 'e:embedded',
            \ 'm:methods',
            \ 'r:constructor',
            \ 'f:functions'
        \ ],
        \ 'sro' : '.',
        \ 'kind2scope' : {
            \ 't' : 'ctype',
            \ 'n' : 'ntype'
        \ },
        \ 'scope2kind' : {
            \ 'ctype' : 't',
            \ 'ntype' : 'n'
        \ },
        \ 'ctagsbin'  : expand(g:go_gotags_bin),
        \ 'ctagsargs' : '-sort -silent'
    \ }
endif
```

A solution would be:

```
let ctagsbin = 'gotags'
" check if vim-go is available and has the binary
if !executable('gotags') && !exists("g:go_gotags_bin")
    let ctagsbin = expand(g:go_gotags_bin),
endif
```

and use `ctagsbin` variable in spf13's tagbar configuration: `\ 'ctagsbin'  : ctagsbin`.

Btw @spf13 I also check whether `g:tagbar_type_go` is defined or not in vimrc. I suggest to add a guard to your configuration so it doesn't override previously created configs, like:

``` vimrc
if !exists("g:tagbar_type_go")
    let g:tagbar_type_go = {
                \ 'ctagstype' : 'go',
                \ 'kinds'     : [  'p:package', 'i:imports:1', 'c:constants', 'v:variables',
                \ 't:types',  'n:interfaces', 'w:fields', 'e:embedded', 'm:methods',
                \ 'r:constructor', 'f:functions' ],
                \ 'sro' : '.',
                \ 'kind2scope' : { 't' : 'ctype', 'n' : 'ntype' },
                \ 'scope2kind' : { 'ctype' : 't', 'ntype' : 'n' },
                \ 'ctagsbin'  : 'gotags',
                \ 'ctagsargs' : '-sort -silent'
                \ }
endif
```
