### ISSUE TITLE
spf13-vim not installing in Win 8.1

### ISSUE THREAD

**Issue by tharindu-mathew** [spf13/spf13-vim#673]
I'm trying to install spf13-vim and it seems to hang when executing this command from the script - call vim -u "C:\Users\mackie.spf13-vim-3/.vimrc.bundles" +BundleInstall! +BundleClean +qall. I've tried through choclatey and by executing it manually but it just seems to hang there indefinitely. I'm running it through an cmd prompt with admin privileges.

**Comment by switchspan** [comment]
I have updated the Chocolatey package: https://chocolatey.org/packages/spf13-vim -- You might want to try it again. Sometimes Vundle takes a like while depending on your network speed.

**Comment by ghost** [comment]
@mackiem : have you tried it?

**Comment by tharindu-mathew** [comment]
Yes, it worked! A note for anyone else who tries, I had to completely wipe out the old installation, and re-run the cmd file for it to work.
