### ISSUE TITLE
CoffeeScript does not syntax highlight

### ISSUE THREAD

**Issue by kineticac** [spf13/spf13-vim#68]
I've narrowed it down to the InitializeDirectories function.  I'm not entirely sure why this block is keeping CoffeeScript syntax from highlighting properly.

**Comment by spf13** [comment]
This is very odd. Looking through the initializeDirectories function, I can't think of any part here that would block. 

One thing to think of is to clear the cache by removing the directories created by initializeDirectories. 

Also make sure the file type is appropriate. I'm not sure that coffeeScript has syntax support out of the box, but javascript does. 

Did you install additional syntax support for coffeeScript or are you using javascript?

As an aside, I'd be happy to add support for coffeeScript if you'd like to fork, add and send a pull request.

**Comment by kineticac** [comment]
Hey Steve, thanks for the reply!  It was really strange, as long as I removed the call to initializeDirectories the syntax highlighting worked great.  I'm also using vim-coffee-script, which I installed using Vundle.

Since I reported the issue initially, I haven't looked back at what was going on in the initializeDirectories function.

Is there a doc that quickly outlines what initializeDirectories does and is used for?  Maybe that will help me understand what might be going wrong there.  You mention that the cache is created by it?  That could be something that went wrong.  I'm not even using it now, which could cause more problems down the line.

Thanks so much!

**Comment by ghost** [comment]
I can confirm that commenting out the invocation of initializeDirectories fixes the coffeescript syntax highlighting issue (also using vim-coffee-script). Very strange! I tried keeping that line but deleting the directories and opening a .coffee file with gvim, but the highlighting was still off. Commenting that line back out restores the syntax highlighting. (I also tried moving the section labeled "Functions" in the .vimrc to see if the ordering of the .vimrc-local and the function would matter, but no dice.)

I am also curious if we are losing something important by commenting this out. Thanks for looking into this! spf13 is great!

**Comment by led** [comment]
Same problem here. It would be nice to find a cleaner solution.

**Comment by racc** [comment]
I am having the same problem with getting scala syntax highlighting to work - if I remove the call to the function it works!

**Comment by AndreRoehrig** [comment]
Is there an easy way to install Coffeescript syntax-highlighting? I have no idea what to do.

**Comment by marshallzheng** [comment]
I also encountered this problem... need help

**Comment by GEverding** [comment]
Has anyone found a solution to this problem?

**Comment by spf13** [comment]
I'll spend some time looking into it. It's very strange.  

Best,
Steve

http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by GEverding** [comment]
For those still having trouble loading the coffee syntax add this line to your .vimrc.local file 

```
autocmd BufNewFile,BufRead *.coffee set filetype=coffee
```

**Comment by spf13** [comment]
Can you add this as a pull request?

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

On Wed, Sep 19, 2012 at 11:07 AM, Garrett Everding <notifications@github.com
