### ISSUE TITLE
Groovylang support

### ISSUE THREAD

**Issue by EPadronU** [spf13/spf13-vim#683]
Hi, everyone. The following are errors that I've found while working with groovy:
- Lack of automatic indentation
- Groovy / (slash) syntax highlighting is wrong ![screenshot from 2014-10-22 18 13 42](https://cloud.githubusercontent.com/assets/829947/4778818/b18cc412-5c03-11e4-8dc9-ff7459592bde.png)

**Comment by ReneFroger** [comment]
Why are you using spf13-vim? Start with a new refreshing vim, spf13-vim is a terrible crap of bloatware.

**Comment by EPadronU** [comment]
I think "convenience" is the best way to put it. Can you point out a resource or, even better, a collection of resources to learn how to tweak/hack/learn the internals of vim?

**Comment by ReneFroger** [comment]
You are speaking about "Vim internals" which proves the point that spf13 will learn you nothing about Vim. It has nothing to do with the Vim internals (newflash: you will find the Vim internals on Neovim). 
Spf13 is just a collection of vimrc's to please everyone, and not personally you.  

You could take a look on reddit.com/r/vim to get some idea's. 

Try this link for example: http://www.reddit.com/r/vim/comments/26z00g/going_to_start_learning_vim_pretty_overwhelmed/

**Comment by EPadronU** [comment]
I know the differences, because of that I asked for the vim internals. With that knowledge I will be capable of tweak vim to please my personal needs and make different plugins play well with each others. Thanks for your time and the links.

**Comment by ReneFroger** [comment]
No problem, EPadronU, we are always glad to help. 

Maybe you find [this another link](http://nvie.com/posts/how-i-boosted-my-vim/) useful too.

**Comment by EPadronU** [comment]
Closing this due the `Groovy / (slash) syntax highlighting is wrong` point has nothing to do with spf13-vim. Also, the indentation can be achieved through the use of  [vim-groovy](https://github.com/johnlim/vim-groovy)
