### ISSUE TITLE
Custom tab space for coffee script files

### ISSUE THREAD

**Issue by edi9999** [spf13/spf13-vim#705]
In my project, I use two spaces for tabs for coffeescript.

So I wrote: 

`au BufEnter *.coffee set expandtab tabstop=2 shiftwidth=2 softtabstop=2`

in my .vimrc.local

However, this doesn't change anything, as the tabstop is still of 4 in my coffee files. Any idea where I should change this ?

**Comment by ghost** [comment]
did you clear your .vimviews directory after changing it?

**Comment by edi9999** [comment]
Right, this is a good fix for that.

What exactly are .vimviews for ? And why are they kept so long ?

**Comment by ghost** [comment]
it saves fold states and other file specific stuff. It speeds things up a bit too. like a cache.

I'm gonna close this out now then.
