### ISSUE TITLE
garbled characters (tab) on linux

### ISSUE THREAD

**Issue by rizza** [spf13/spf13-vim#711]
ubuntu 14.04
vim 7.4

![screenshot from 2014-12-31 14 31 28](https://cloud.githubusercontent.com/assets/10241341/5586029/e235969e-90fa-11e4-96ba-55cc17e0d297.png)

**Comment by ghost** [comment]
i think your locale isn't set properly to some utf8 variant. Can you check?

**Comment by rizza** [comment]
@jrobeson thank you, fixed.
