### ISSUE TITLE
Disable spell check by "set nospell" fails

### ISSUE THREAD

**Issue by amghost** [spf13/spf13-vim#722]
I append ‘’set nospell" to my .vimrc.local, but it does not work.
However, I can disable spell check in vim command line with "set nospell"

Anybody helps?

**Comment by FiloSpaTeam** [comment]
I've the same situation :+1: 
Sometimes, and idk why, i solve cleaning .vimviews folder :)

**Comment by amghost** [comment]
Yes, after searching I find that cleaning `.vimviews` directory solve the problem.
Still I wonder what the directory is used for and will it be a little bit tedious since I have to clean it every time :(
Anyway I am closing this issue

**Comment by ghost** [comment]
it's sorta like a cache. to speed up reopening the same files you've previously opened.

**Comment by FiloSpaTeam** [comment]
So when you change your configuration, the views does not change their cache?

**Comment by amghost** [comment]
I am thinking that maybe the cache of `.vimrc` should be deleted after being modified.

well say every configuration file, including `.vimrc`, `.vimrc.local`, etc

**Comment by ghost** [comment]
no it doesn't, it'd be hard to detect which plugins affect which files. although i suppose spf13-vim itself could clear the cache after changing configuration.. assuming you were using spf13-vim while editing the files.

**Comment by amghost** [comment]
well, that should be it. since the solution is found, the issue is closing now.
