### ISSUE TITLE
Error with ^M

### ISSUE THREAD

**Issue by kxxoling** [spf13/spf13-vim#729]
Got this error while installing on Xubuntu VirtualBox Machine:

Error detected while processing /home/windrunner/.spf13-vim-3/.vimrc.bundles.default:
line    2:
E492: Not an editor command: ^M
line    4:
E15: Invalid expression: filereadable(expand("~/.vimrc.before"))^M
line   15:
E171: Missing :endif
Press ENTER or type command to continue
\e[32m[✔]\e[0m Now updating/installing plugins using Vundle

Thanks for installing spf13-vim.
© 2015 http://vim.spf13.com/

**Comment by ghost** [comment]
hmm. try opening up the file and see if does have ^M on every line. although i have no idea how that might occur if installed on Linux

**Comment by kxxoling** [comment]
@jrobeson Cannot find ^M while opening the sh file via Vim. I tried to install it manually finding the font  of [✔] is correct now.

![2015-03-05 5 31 55](https://cloud.githubusercontent.com/assets/1227139/6502377/e1fc5f2e-c35d-11e4-8dc5-7a3a62da0486.png)

**Comment by kxxoling** [comment]
I found this is affected by the git automatically add <clrf> to files, to avoid this, I changed the git conifg:

```
$ git config --global core.autocrlf input
```

I deleted all the related files and install spf13 again, everything is OK now.
