### ISSUE TITLE
How to install specific pluging, not batch?

### ISSUE THREAD

**Issue by wxlfight** [spf13/spf13-vim#761]
when i add a plugin to vimrc, and run command "vim +BundleInstall! +BundleClean +q" , it seems to install all the exist plugins again, it takes me a lot of time. So in what way can i install the plugin i just added ?

**Comment by ghost** [comment]
It's probably in the vundle documentation. Have you already tried reading the vundle docs?

**Comment by nxnfufunezn** [comment]
`:PluginInstall tpope/vim-surround tpope/vim-fugitive`
Installs both `tpope/vim-surround` and `tpope/vim-fugitive` from GitHub.
