### ISSUE TITLE
Inbearably slow in Laravel Projects

### ISSUE THREAD

**Issue by janwirth** [spf13/spf13-vim#763]
The suggestions being loaded make fluid typing impossible.

**Comment by ghost** [comment]
then it's up to you to take out the ones that don't work well for you or at least point them out. There's nothing actionable in this report atm.

**Comment by FiloSpaTeam** [comment]
I've the same problem. I work with Laravel. Try my [fork](https://github.com/FiloSpaTeam/spf13-vim) that has a lot of changes (for laravel too).

**Comment by ghost** [comment]
@FiloSpaTeam : were there nay specific plugins that were slowing you down?

**Comment by FiloSpaTeam** [comment]
I understand this:
- syntax highlight terrible slow and buggy so i changed to another 
- autocompletion was veryvery uncomplete without YouCompleteMe, another good thing of YCM is async
- a lot of plugins for a simple work or duplicated when i can use one like unite (that is aync too)
- i think another is the integration with git for symbols at left.
- i think powerline is better than airline but i ve problem with first one.

**Comment by ghost** [comment]
what did you change the syntax highlighthing to?  BTW there's an open ticket for integrating unite, but i'm not sure of the status of that.

**Comment by FiloSpaTeam** [comment]
I changed for [this](https://github.com/StanAngeloff/php.vim).
In bigger files works well.
Unite is very good with async.
in my fork i changed the system of bundle too, it is divided into 2 groups: functions and languages.
I replaced plugins with others for better integration with tagbar and so on.
My experience with Laravel projects is quite goodgoo, sometimes i ve slow performance but only for big blade files. in services and others all works. Only problem that i m solving is slow autocompletion due to big big big words.

**Comment by ghost** [comment]
i'm planning on trying out neovim myself to solve some of the async plugin issues.

**Comment by FiloSpaTeam** [comment]
Yeah in fact i m porting this conf locally (neovim gentoo version). A lot of plugins doesn t load correctly but i m solving ;-)

**Comment by janwirth** [comment]
@FiloSpaTeam I just checked out your fork, vim still crashes when typing in a somewhat big controller file. Can you keep me posted on the results of your neovim port?

Apart from that, whenever i open a file i have to hit enter at least 3 times just to start working.

**Comment by FiloSpaTeam** [comment]
Have you cleaned up your .vimviews folder and .vimswap??

I don-t have at the moment a repo with NeoVim port because i'm testing it locally :+1:

**Comment by janwirth** [comment]
it's crashing, no matter what.
would be awesome to check out that repo

**Comment by FiloSpaTeam** [comment]
Mmmh strange. In my office this doesn't happens (we are 4 pc's).
I'll investigate. :+1:

**Comment by janwirth** [comment]
I meant it's crashing when I'm typing in a large laravel controller file. The autosuggests slow down the fps to 1 and sometimes it just freezes.
No need to investigate for me, it's not that critical, I'll find my way. Just let me know once you've got it running on neovim and what the performance is like.

**Comment by janwirth** [comment]
http://kevin.colyar.net/2011/05/fixing-vim-auto-complete-slowness-in-large-projects/

this seems to have fixed it for me!
can you confirm it @FiloSpaTeam?

**Comment by FiloSpaTeam** [comment]
This night i ll put in my conf and i ll try! :) 
;-)

**Comment by FiloSpaTeam** [comment]
I tried but no differences. What changed for you??

**Comment by janwirth** [comment]
autocomplete is not so very slow anymore while in insert mode in a bigger controller

did you just try typing
<code>:set foldmethod=manual</code>
while in slow insert mode and watched if something changed?

**Comment by FiloSpaTeam** [comment]
I have automatically this. (My biggest controller contains 500 rows)
I know your problem maybe. Are you using [this](https://github.com/spf13/PIV) plugin instead of [this](https://github.com/StanAngeloff/php.vim)?

**Comment by janwirth** [comment]
yes I'm using PIV as it is the default in this package.

**Comment by FiloSpaTeam** [comment]
Ok try the bundle the other plugin instead of PIV ;-) i changed because PIV have some bugs and slow down VIM :)

**Comment by janwirth** [comment]
checking out your fork now. seems quite promising. how come you're not issuing pull requests?
do you have twitter?

**Comment by FiloSpaTeam** [comment]
I ve twitter @CMaradonna ;-) 
i ve done some pull request some times ago but no integration, a lot of times for single pull.... i decided to maintain myself a configration :)

**Comment by janwirth** [comment]
I switched to mawww/kakoune from vim.

**Comment by abidulrmdn** [comment]
related to blade performance

https://github.com/Te-cho/compile-blades
