### ISSUE TITLE
"some useful mappings" commit breaks "fastTabs" tab navigation mappings

### ISSUE THREAD

**Issue by toejough** [spf13/spf13-vim#764]
commit 96678bcd9960684373e18de8f9e51ec0c6d32b3e includes mappings for `H` and `L`, which now override the preexisting mappings in .vimrc.

The pre-existing mappings allowed you to navigate among your tabs quickly with `H` and `L`.

The new mappings take you to the start and end of the line you're on.  `^` or `0` and `$` already did that, so my preference would be to remove the new mappings.

[Pre-existing mappings](https://github.com/spf13/spf13-vim/blob/3.0/.vimrc#L329) (still there, just non-functional now):

``` vim
if !exists('g:spf13_no_fastTabs')
        map <S-H> gT
        map <S-L> gt
    endif
```

[New mappings](https://github.com/spf13/spf13-vim/blob/3.0/.vimrc#L369):

``` vim
"go to first and last char of line
    nnoremap H ^
    nnoremap L g_
    vnoremap H ^
    vnoremap L g_
```

**Comment by cpitt** [comment]
I would vote to just revert the changes from 96678bc , they don't add much at all

**Comment by aVolpe** [comment]
Yes, please revert the changes from https://github.com/spf13/spf13-vim/commit/96678bcd9960684373e18de8f9e51ec0c6d32b3e, they also add the `gv` map to "minimize a word", when gv is the default key bind for last visual selection.
