### ISSUE TITLE
Hitting arrow keys adds characters in vi

### ISSUE THREAD

**Issue by iwoork** [spf13/spf13-vim#770]
I did a fresh install of spf13-vim. Getting the same issue here at:

http://askubuntu.com/questions/353911/hitting-arrow-keys-adds-characters-in-vi-editor

But when i totally uninstall spf13-vim, I don't get the problem. Any plugin known to cause this?

**Comment by rinchen** [comment]
I was just going to file a bug about this myself. 

It happens in insert mode.  I've removed all of the bundles and it still happens.  When I remove .vimrc the problem goes away.  I've tried a few of the .vim.before.local overrides such as let g:spf13_no_easyWindows = 1  but so far I haven't found the culprit.

**Comment by ghost** [comment]
is this is the issue you're seeing? https://github.com/spf13/spf13-vim/issues/567  If so, then you should close this bug.

**Comment by rinchen** [comment]
@jrobeson Yep that's the one for me. The fix works.

**Comment by iwoork** [comment]
Thanks! that fix worked. Closing this issue.
