### ISSUE TITLE
Reinstall on Mac causing error with autocomplete and navigation keys.

### ISSUE THREAD

**Issue by wpoosanguansit** [spf13/spf13-vim#772]
I just reinstall everything new on Mac OS 10.9 and I am getting weird errors with snippet having neocomplete showing up in the autocomplete selection.  At the same time, the arrow keys are mapped to DCBA.  I am not sure how to have it back to when everything was working again.  Any help is appreciated.

![screenshot](https://cloud.githubusercontent.com/assets/90733/7531135/1519ef06-f523-11e4-9c08-460a0153336e.png)

**Comment by janwirth** [comment]
1. I don't see any problems with the autocompletion as Bundle\* are editor commands.
2. I've run into this issue aswell but I'd recommend you to perceive it as a cue to use hjkl instead of the arrow keys ;) Arrow key movement is very inefficient and is not really compatible with muscle memory.

**Comment by wpoosanguansit** [comment]
Thanks for your help.  Since the arrow keys do not work, how do I move down the suggestion list?  In insert mode I can't use hjkl keys neither.  Thanks again.

**Comment by MuschPusch** [comment]
It should be working with the 'tab' key

**Comment by wpoosanguansit** [comment]
Hmm, it is not.  Then how do I get this to work again like before I reinstall everything new.  Also, I tried to do autocomplete this is the string I get when I do tab which selects the first one

import<Plug>(neosnippet_expand)

I think something changed in between somewhere because it was working fine a couple of weeks ago before reinstall.  Any suggestion is appreciated.

**Comment by ghost** [comment]
+1 also having this problem after updating to newest trying to fix another problem with ruby seg faults on autocomplete - basically unusable.

**Comment by ghost** [comment]
Fixed the broken arrow keys with set term=xterm-256color

**Comment by wpoosanguansit** [comment]
that does not work for me though.

**Comment by wpoosanguansit** [comment]
The issue is the same as this https://github.com/spf13/spf13-vim/issues/567.  So this is more prevalent than I thought.  I am gonna close it and follow the other issue instead.
