### ISSUE TITLE
Neovim support

### ISSUE THREAD

**Issue by bronzehedwick** [spf13/spf13-vim#774]
I wanted to try and start a discussion about including support for [Neovim](https://github.com/neovim/neovim). Even though it doesn't have a 1.0 release yet, it brings a lot of exciting features, especially for the [plugin ecosystem](https://github.com/neovim/neovim/wiki/Plugin-UI-architecture), while maintaining a lot of backwards compatibility. One plugin in particular, [neomake](https://github.com/benekastah/neomake), is very exciting in it's potential for speeding up vim in-editor code checking.

Neovim uses `.nvimrc` as it's main dotfile, so it can exist alongside vim without conflict. Adding support would probably look like adding an `.nvimrc` file to spf13 customized for Neovim support, that would only be copied to the home directory if the neovim binary existed on the system.

Of course, the major downside to this is adding something else to support, but I at least wanted to float the idea and see what people thought.

**Comment by ghost** [comment]
did they ever finish supporting lua in plugins? that's the main blocker for me before i give it a shot.

**Comment by FiloSpaTeam** [comment]
I started a branch in my fork to have support for NeoVim.
https://github.com/FiloSpaTeam/spf13-vim/tree/neovim

**Comment by bronzehedwick** [comment]
@jrobeson Looks like they haven't completed the lua support for plugins yet, but it's near the top of their TODO, which probably means it'll ship before a 1.0 release.

@FiloSpaTeam thanks for the link! I'll play with that in the mean time.

**Comment by FiloSpaTeam** [comment]
You're welcome!! Help is very appreciate :+1:

**Comment by bronzehedwick** [comment]
I just ran a test and I am able to use neovim locally with spf13-vim, with bvery few changes. I have a vanilla spf13, and then symlinked `.spf13-vim-3/.vimrc` to `~/.nvimrc` and `.spf13-vim-3/.vim` to `~/.nvim`. After installing neovim python support, everything just works.

**Comment by ghost** [comment]
as mentioned in #777, you shouldn't need a .nvimrc  .nvim should work
