### ISSUE TITLE
Setting g:spf_leader to "\<Space" has no effect

### ISSUE THREAD

**Issue by addisonamiri** [spf13/spf13-vim#779]
I tried remapping leader to space and it's not working. I have a fresh install of spf13 and in my .vimrc.before.local I have `let g:spf_leader="\<Space>"`. Is there any way I can map leader to Space?

**Comment by haifengkao** [comment]
it should be `g:spf13_leader`

**Comment by addisonamiri** [comment]
Thanks ^w^
