### ISSUE TITLE
Press arrow keys input A/B/C/D instead of moving the cursor, after removing plugin vim-autoclose.

### ISSUE THREAD

**Issue by mnloop** [spf13/spf13-vim#780]
I'm using iTerm2 with spf13-vim, after upgrading to the latest version of spf13-vim today, I've run into such problem.

The reason is the plugin **vim-autoclose** has been removed. [This solution fixed it.](http://vim.wikia.com/wiki/Fix_arrow_keys_that_display_A_B_C_D_on_remote_shell#Solution_21)

Just add following lines into your .vimrc.local

```
if &term[:4] == "xterm" || &term[:5] == 'screen' || &term[:3] == 'rxvt'
  inoremap <silent> <C-[>OC <RIGHT>
endif
```

**Comment by barraponto** [comment]
Yeah, this is bugging me too.

**Comment by fabianhjr** [comment]
Got same issue, you should probably do a pull request for the patch @appbead

**Comment by fabianhjr** [comment]
Created pull request #781 @spf13
