### ISSUE TITLE
NeoSnippet not working as expected.

### ISSUE THREAD

**Issue by nxnfufunezn** [spf13/spf13-vim#784]
![1](https://cloud.githubusercontent.com/assets/9052031/7785392/af726620-01ab-11e5-8b58-4aeddc22c3a9.png)

Did fresh install of spf-vim after facing issues after recent update.
Now NeoSnippet is not working as expected.

**Comment by nxnfufunezn** [comment]
Removing `jiangmiao/auto-pairs` fixed this problem.
Similar issues-
https://github.com/spf13/spf13-vim/issues/769
https://github.com/spf13/spf13-vim/issues/775

**Comment by kevinushey** [comment]
This also implies that the default installation of spf13-vim is broken. I hope the plugin conflicts can be resolved soon.
