### ISSUE TITLE
Python autocomplete seems to be messed up

### ISSUE THREAD

**Issue by raratiru** [spf13/spf13-vim#785]
I am writing in Python. When the autocomplete menu appears I used to navigate with the arrows, select the proper solution and hit enter to insert it.

This behavior has ceased now and I am unable to find a constant way to select the proper proposal and insert it.

TAB is a safe selector and more convenient, but when it comes to insertion, sometimes is achieved when I continue typing, some other times is achieved when I hit `<ctrl>k`, some others when I hit the right arrow. However, no one guarantees that the current working solution will work in the next menu appearance. 

Is this an issue or just a new behavior in which I am not accustomed?

**Comment by nxnfufunezn** [comment]
In my case https://github.com/spf13/spf13-vim/issues/784 removing `jiangmiao/auto-pairs` solved the problem. So try removing  `jiangmiao/auto-pairs` from bundle.

**Comment by raratiru** [comment]
Thank you, it works!

I was aware of case #784 and I tried to remove auto-pairs before, but I did not succeed because:

1) After deletion, the folder `.vimviews` has to be cleaned manually
2) In my `.vimrc.local` I had `imap`ped the arrows to scroll by visual lines.

Everything works great now. :+1:
