### ISSUE TITLE
Weird highlighting

### ISSUE THREAD

**Issue by logitick** [spf13/spf13-vim#786]
I recently did a VundleUpdate now I am getting this.
![image](https://cloud.githubusercontent.com/assets/807325/7804602/be5108b6-0397-11e5-85d1-a458bf4798ee.png)

changing the colorscheme doesn't seem to work.

**Comment by janwirth** [comment]
could you get more specific? did you try <code> :colorscheme solarized </code> and <code> :set syntax=php <code> ?

**Comment by logitick** [comment]
Seemed to have disappeared after a restart. And yes, I tried both when I was still having the issue.

**Comment by VMatrix1900** [comment]
This issue should be closed.
