### ISSUE TITLE
NERDTree resize and CWD mapping

### ISSUE THREAD

**Issue by theycallmeswift** [spf13/spf13-vim#79]
I'm having a couple of problems using NERDTree in your config.

 1) I get "Press ENTER or type command to continue" the first time I use one of the commands.  After the first time, it works as expected.

![SS](https://www.evernote.com/shard/s196/sh/fa0ea8e2-b872-48c3-8c79-28bda37772d0/413156f84e81d3c468d2625d038a14cb/res/5cbfe208-6b49-4ef7-9e9a-64cdcfe881c3/1._tmux-20120429-154243.jpg.jpg)

2) `:Vex` resizes to a sliver of the screen, `:Sex` resizes to 50/50 as expected.  I'd like to have `:Vex` resize to half the screen width as I would normally expect.

![SS2](https://www.evernote.com/shard/s196/sh/a6892ca1-6569-4240-a364-78cf0ca940dc/88c7d5bf9c93b778d17441117272efda/res/22bd24ee-0519-4935-a62a-f1c7558534dc/1._tmux-20120429-154649.jpg.jpg)

3) `:E` is now ambiguous.  In my previous vim config, I could type `:E` to get a vertical split with NERDTree in the current directory.  Now, I'm getting these "Ambiguous use of user defined command" errors.  Any idea how to fix?

![SS3](https://www.evernote.com/shard/s196/sh/d82b0b3f-87cf-4483-a265-079f6a6028fe/08d4604f7630cc97d3b492c558662c53/res/8b2ecdf9-c56c-4ac5-90b7-a377b1f79dfc/1._tmux-20120429-154911.jpg.jpg)

**Comment by bronzehedwick** [comment]
@theycallmeswift, it seems like this issue is no longer relevant. Is that correct? If so, please close. Thanks!

**Comment by bronzehedwick** [comment]
@jrobeson can this issue be closed?

**Comment by ghost** [comment]
guess so. it's been awhile with no response!
