### ISSUE TITLE
Why are tabs being highlighted, and how to disable that?

### ISSUE THREAD

**Issue by derekchiang** [spf13/spf13-vim#797]
![screen shot 2015-06-20 at 12 54 07 am](https://cloud.githubusercontent.com/assets/1535686/8266520/fd7c6fb4-16e6-11e5-9a98-05ed623cb0e0.png)

See that the tabs above are being highlighted.  What is causing this?  How to disable this behavior?

**Comment by bronzehedwick** [comment]
This is enabled by the standard vim option `list`. You can disable it by running `:set list!`.

**Comment by derekchiang** [comment]
Great, thanks!
