### ISSUE TITLE
How to use the file listing on the botton of the editor window?

### ISSUE THREAD

**Issue by derekchiang** [spf13/spf13-vim#799]
![screen shot 2015-06-20 at 8 51 05 pm](https://cloud.githubusercontent.com/assets/1535686/8270304/48f14bf2-178e-11e5-9cf3-6ed381c3c9c9.png)

See that there is a listing of filenames.  I'm guessing that I can somehow jump to those files using the numbers?

**Comment by bronzehedwick** [comment]
Yes, those are buffer numbers. You can jump to the specified buffer using :b [buffer number]

**Comment by derekchiang** [comment]
Great, thanks!

**Comment by MuschPusch** [comment]
Is there an easy way to open a buffer in a vertical split?

**Comment by bronzehedwick** [comment]
Yep, use `:vert sb [buffer_name || buffer_number`.
