### ISSUE TITLE
submodule update --init fails for VimDebugger

### ISSUE THREAD

**Issue by ghost** [spf13/spf13-vim#8]
> git submodule update --init
> ...
> Initialized empty Git repository in /home/vincent/source/spf13-vim/.vim/bundle/VimDebugger/.git/
> remote: Counting objects: 61, done.
> remote: Compressing objects: 100% (60/60), done.
> remote: Total 61 (delta 27), reused 0 (delta 0)
> Receiving objects: 100% (61/61), 42.98 KiB, done.
> Resolving deltas: 100% (27/27), done.
> fatal: reference is not a tree: 45d8ca46870f45a3d839aeec643d44d8c57c9395
> Unable to checkout '45d8ca46870f45a3d839aeec643d44d8c57c9395' in submodule path '.vim/bundle/VimDebugger'

**Comment by myszek123** [comment]
yup, after merge i do experience the same issue 

spf13-vim$ git submodule update
fatal: reference is not a tree: 45d8ca46870f45a3d839aeec643d44d8c57c9395
Unable to checkout '45d8ca46870f45a3d839aeec643d44d8c57c9395' in submodule path '.vim/bundle/VimDebugger'

**Comment by myszek123** [comment]
ok, i've just removed it and added again manually. seems to work fine

**Comment by cdracars** [comment]
I also have this issue.

**Comment by spf13** [comment]
Resolved in 11cf257671bd47bdd88d7a287efff2ca026c64f0

**Comment by Broza** [comment]
Hi,
I'm a big noob of git and don't understand this error. I don't know if it's the same type of problem, but I have this one:
Initialized empty Git repository in /home/bro/Git/spf13-vim/.vim/bundle/command-t/.git/
remote: Counting objects: 112, done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 112 (delta 41), reused 98 (delta 36)
Receiving objects: 100% (112/112), 19.31 KiB, done.
Resolving deltas: 100% (41/41), done.
fatal: reference is not a tree: 85fd8b0ce657f772ad9c1c50fe502e08ca2bf04c
Unable to checkout '85fd8b0ce657f772ad9c1c50fe502e08ca2bf04c' in submodule path '.vim/bundle/command-t'
Thanks in advance for your help, and sorry for my bad english :).
