### ISSUE TITLE
i can't remove the highlighting of words,just like the picture.

### ISSUE THREAD

**Issue by wangdashuaihenshuai** [spf13/spf13-vim#801]
![Image of iss](http://upload-images.jianshu.io/upload_images/624315-effaef74a6b9ebff.png)
i rewrite the vimrc,but i can't find where to change this.

**Comment by nxnfufunezn** [comment]
put `set nospell` in your local vimrc file

**Comment by misakaok** [comment]
> put set nospell in your local vimrc file

:+1: Oh, I see
