### ISSUE TITLE
no ack after upgrade

### ISSUE THREAD

**Issue by royts** [spf13/spf13-vim#803]
Hi,
A friend told me about Ack for text search in files. I was happy to find out that spf13-vim already includes it.
Problem is - even though I upgraded to the latest version, I don't see it in the list of plugins and can't run it.
Any idea why?

Thanks!

**Comment by bronzehedwick** [comment]
The ack vim plugin is only installed if the ack or ag binary is also installed. Do you have either running on your machine?

**Comment by royts** [comment]
oh. installed Ack , run the install script again and it is there!
thanks.
