### ISSUE TITLE
window size confusing

### ISSUE THREAD

**Issue by halfcrazy** [spf13/spf13-vim#809]
When i am using nerdtree and tagbar plugin on the same time, i sometimes got strange window size. It looks like this 
<img width="1280" alt="screen shot 2015-07-28 at 16 28 37" src="https://cloud.githubusercontent.com/assets/4113173/8926876/d3d03844-3545-11e5-93fe-e5aa26c2eb57.png">

I'm using osx iterm2 zsh vim7.4

**Comment by byliu** [comment]
I have the same problem, what should I do?

**Comment by halfcrazy** [comment]
@byliu add `let g:NERDTreeWinSize=25` to your .vimrc.local
