### ISSUE TITLE
<Plug>delimitMateRight for delete and arrow keys

### ISSUE THREAD

**Issue by nddery** [spf13/spf13-vim#82]
Hey, first, thank you very much for this awesome version three, it rocks!

Everything seems to be working fine but I can't use the delete and the arrow keys. Whenever I use one of these keys, Vim insert this: "<Plug>delimitMateDel" (where "Del" would be replaced by "Left" if I used the left arrow key)...

This would not be a big problem usually but as I am on a Mac and am using the Mac keyboard, my "delete in front" key is FN+DELETE, which produce this problem. I looked in the .vimrc file but did'nt see anything related to delimitMate.

Any idea how to fix this ?

I am on Mac OSX Lion 10.7.3 running MacVim 7.3.

Thanks,

Nicolas

**Comment by nddery** [comment]
Hey again,

unfortunately, this problem now made my MacVim unusable as when I press ESC to escape form insert mode, instead of exiting insert mode, it output '<Plug>delimitMateEsc'. Is there a way to disable a plugin from my .vimrc.local ?

**Comment by nddery** [comment]
Ok, this issue is now fixed, it apparently was an issue with my system.. I deleted all files in "~/.vimundo , ~/.vimswap , ~/.vimviews , ~/.vimbackup" to fix the problem. It was not happening with all my files, only certain one.

**Comment by farneman** [comment]
Thanks @nddery. I found this solution worked for a similar problem for me as well.
