### ISSUE TITLE
Auto Pairs cannot be disabled

### ISSUE THREAD

**Issue by haifengkao** [spf13/spf13-vim#820]
I have added `UnBundle 'jiangmiao/auto-pairs'` and the bundle is removed during `PluginClean`.
But the `imap` setting like `AutoPairsDelete()` still effective when a file is loaded.
It causes `E117:Unkown function: AutoPairsDelete()` whenever I type `<BS>`.

**Comment by ghost** [comment]
did you  clear your ~/.vimviews folder?

**Comment by haifengkao** [comment]
clean `~/.vimviews` fixed this issue. thanks
