### ISSUE TITLE
Not Working on MacVim

### ISSUE THREAD

**Issue by a37z** [spf13/spf13-vim#828]
Hi can you please help me? I am getting this error whenever I try and vim, I tried to update by I still get the following errors

I installed using the easy command

Thanks

![screen shot 2015-09-25 at 12 45 06 am](https://cloud.githubusercontent.com/assets/5222244/10084017/c414686a-631e-11e5-8f88-5e31768530a7.png)

**Comment by bronzehedwick** [comment]
Looks like vundle isn't installed, or is installed to a directory vim isn't looking for. 

I'm assuming `vi` is symlinked to `mvim`? And does your `~/.vim` directory exist? You might need to re-run `~/.spf13-vim-3/bootstrap.sh`.
