### ISSUE TITLE
any reference to a puppet plugin?

### ISSUE THREAD

**Issue by lmayorga1980** [spf13/spf13-vim#835]

**Comment by bronzehedwick** [comment]
@lmayorga1980 can you provide more information on what you want addressed in this ticket?

**Comment by lmayorga1980** [comment]
It seems that there is no puppet plugin included with the default settings.

**Comment by bronzehedwick** [comment]
Okay, can you make a PR or suggestion with which plugin you want included? 

I don't know under which plugin grouping it would fall under, but maybe @jrobeson would want to weigh in on if it should be included in the base distro, or if it should just be kept in individuals `.vimrc.bundles.local`.
