### ISSUE TITLE
Many questions arise after  I have installed spf13-vim

### ISSUE THREAD

**Issue by ThroughLee** [spf13/spf13-vim#838]
Every time I use vim,it shows this:
oracle@woxin-B85MG:/opt/oracle$ vim test.c
���� /opt/oracle/.vimrc ʱ��������:
��  234 ��:
E474: ��Ч�Ĳ���: listchars=tab:???? 
�� 1031 ��:
E115: ȱ������: '
E15: ��Ч�ı���ʽ: '????  " Slightly fancier than '>'
���� /opt/oracle/.vim/bundle/nerdtree/plugin/NERD_tree.vim ʱ��������:
��   71 ��:
E114: ȱ������: "▸")
E116: Invalid arguments for function <SNR>32_initVariable
��   72 ��:
E114: ȱ������: "▾")
E116: Invalid arguments for function <SNR>32_initVariable
�밴 ENTER �������������

How to solve this？(I'm a Rookie~~)
thx.

**Comment by Eredawn** [comment]
I have installed it as root user,it works well.Unfortunately，it did't work when I install it as oracle user.
