### ISSUE TITLE
Terminal needs reset after update

### ISSUE THREAD

**Issue by raratiru** [spf13/spf13-vim#839]
I am using `GNOME Shell 3.14.4` under `Debian GNU/Linux 8`.

When updating spf-13 with the command `curl https://j.mp/spf13-vim3 -L -k -o - | sh`, the terminal is left in a funny state where no new lines exist and the characters are not printed anymore. 

I have to type `reset` in order to bring back the original terminal state.

**Comment by MaerF0x0** [comment]
+1 ubuntu 14.04LTS
