### ISSUE TITLE
swap file

### ISSUE THREAD

**Issue by hbcbh1999** [spf13/spf13-vim#845]
I don't know what happened. Ever since I started to use this plugin, I always have problems with swap files. It will just mess up the syntax. Even I deleted .swap. I cannot use the same name for the file. Any solution, guys?

**Comment by ghost** [comment]
Please explain exactly what you're trying to do, and what happens.

**Comment by hbcbh1999** [comment]
I open up a file in iTerm and close it by accident or for whatever reason. there will be a swap file generated under ~/.vimswap/ directory. I tried to delete the file and reopen the file. all the syntax are gone. the only temporary fix is to rename the file( to a different name) and the syntax will come back. please try it to see if you guys can duplicate the problem. it happens to me every single time. thanks

**Comment by hbcbh1999** [comment]
<img width="922" alt="screen shot 2015-11-02 at 09 35 06" src="https://cloud.githubusercontent.com/assets/1378193/10884278/21150558-8145-11e5-80b7-389030977233.png">

This is how a Python file look like on my machine.

**Comment by hbcbh1999** [comment]
I didn't figure out how to resolve the issue. I backed up the configuration file, uninstalled spf13 and re-installed. The previous issues seem gone by now.

**Comment by hbcbh1999** [comment]
My concern is I don't want to just delete spf13 and installed a fresh version without knowing what happened. Any input will be appreciated greatly.

**Comment by ghost** [comment]
if it happens again, try `rm -rf ~/.vimviews`
