### ISSUE TITLE
running sudo vim <whatever> dies

### ISSUE THREAD

**Issue by matthewmatician** [spf13/spf13-vim#86]
Any thoughts on why this error is happening?

Error detected while processing /Users/matthew/.spf13-vim-3/.vim/bundle/neocomplcache/plugin/neocomplcache.vim:
line   37:
"sudo vim" and $HOME is not same to /root are detected.Please use sudo.vim plugin instead of sudo command or set always_set_home in sudoers.

Also, trying to run :w!! doesn't do anything. The .vimrc states that it allows for writing a read-only file (when you forget to run sudo vim <whatever>)

Thanks!

**Comment by gerrywastaken** [comment]
Yeah I ran into the same issue when trying to use "sudo vi", however for me ":w!!" does allow me to save as root, which is an ok temporary solution. Still it would be great if I could just run vi with sudo.

**Comment by larrylv** [comment]
@matthewmatician @gerrywastaken

You can add always_set_home in following way

`sudo visudo`

and change line

`Defaults    env_reset`

to

`Defaults    env_reset,always_set_home`

save and exit

btw. `sudo vi/vim` is a bad idea. u should use `sudoedit` instead.

Reference:
- https://groups.google.com/forum/#!msg/spf13-vim-discuss/q76OnZt4tZ4/3zwcRsNzaoYJ
- http://superuser.com/questions/23428/vim-sudo-vim-bad-idea

**Comment by gerrywastaken** [comment]
Thanks for the tips. :)

Although instead of sudoedit I might use rvim instead as it's implicit as to the editor I wish to run and blocks me from running commands.

I really like the tip though, thanks. It was a very good point that I hadn't considered.

**Comment by chrisramakers** [comment]
@larrylv I'm on osx mountain lion and it works as expected, when I add the `always_set_home` directive `sudo vi` does no longer display an error prior to launching. 

Problem now is that when i'm running `sudo vi` i'm getting vanilla vim, without colorschemes, etc ...

Any way to solve that?

**Comment by bronzehedwick** [comment]
This is because sudo runs as the root user, not yours. You would need to install spf13 as root to fix. 

```
 sudo su root
```

Then install spf13 again.
