### ISSUE TITLE
NERDTree opens on startup

### ISSUE THREAD

**Issue by Rakin05** [spf13/spf13-vim#87]
I'm new to vim and spf-13 so please bother with me if it is trivial.

NERDTree opens open every time on startup. I find this a bit annoying. How can i prevent this?

**Comment by HendrikRoth** [comment]
Would be nice to open NERDTree only on startup, if no file is choosen.

**Comment by Rakin05** [comment]
add this to your vimrc and you should be done

``` viml
function! StartUp()                                                                                                                                                                                         
    if 0 == argc()
        NERDTree
    end
endfunction

autocmd VimEnter * call StartUp()
```

**Comment by HendrikRoth** [comment]
This still startups vim with nerdtree opened (with file opened)

**Comment by frayedknot** [comment]
This still occurs.  I have tried the fix that Rankin05 submitted, but it did not work for me.  I have using this with gvim 7.3 on Windows XP.

**Comment by nddery** [comment]
I have the same issue and the solution posted above is not working for me neither. MacVim7.3 on OSX Lion.

**Comment by jphustman** [comment]
Yeah NERDtree opening everytime is annoying and time consuming... Please make this optional

**Comment by wolfgangpfnuer** [comment]
simply put this into your .vimrc.local

let g:nerdtree_tabs_open_on_gui_startup=0

**Comment by nddery** [comment]
Thank you SO MUCH !!! This was driving me crazy!

**Comment by spf13** [comment]
I usually close it as well. I wonder if most people prefer this behavior.  

Best,
Steve

http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by jaywilliams** [comment]
Thank you @wolfgangpfnuer for the tip. I've added that to my .gvimrc file, so NERDTree doesn't open by default in MacVim, but still opens by default in terminal Vim.

**Comment by jamestomasino** [comment]
Oh my goodness. This has been a lifesaver. I've been hammering at my .vimrc.local for hours trying to override that! Thanks so much, wolfgangpfnuer

**Comment by taxilian** [comment]
This should either be closed or the action item stated as adding that information to the README (or somewhere else?) on how to customize things.

**Comment by wolfgangpfnuer** [comment]
the setting found its way into master 2 days ago :-)
this issue should be closed.

**Comment by macunan** [comment]
wolfgangpfnuer  you rock thanks for your great tip 
let g:nerdtree_tabs_open_on_gui_startup=0
