### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by spacexnu** [spf13/spf13-vim#880]
Could not resolve airline theme "solarized". Themes have been migrated to github.com/vim-airline/vim-airline-themes.

**Comment by saiichihashimoto** [comment]
+1

**Comment by johnpa** [comment]
+1

**Comment by spacexnu** [comment]
Hello all,

Adding `Plugin 'vim-airline/vim-airline-themes'` into ~/.vimrc.bundles.local and run: `:PluginInstall` should fix the issue.

**Comment by mnichols** [comment]
Yup, fixed it for me. Thanks @adlermedrado !

**Comment by SoulEst** [comment]
Many thanks @adlermedrado

**Comment by dragonito** [comment]
Thx!

**Comment by jsalamin** [comment]
Thank you @adlermedrado for the workaround, it perfectly fixed the issue. Hope that the next release will include this modification.

**Comment by willneumob** [comment]
+1 ;/

**Comment by shoubusi** [comment]
Thanks!

**Comment by novalore** [comment]
I added the bundle an ran BundleInstall and the themes are now included in the "themes" directory inside vim-airline. roblem is that now vim does not complain about the theme anymore but I don't see it in use either.
![vim-snapshot](https://cloud.githubusercontent.com/assets/1128726/12971946/00978552-d0a1-11e5-9c30-506a28c06797.png)

**Comment by dustinrc** [comment]
Duplicate PRs for this: #883 and #886.

**Comment by dreispt** [comment]
+1!

**Comment by AntonioGarRod** [comment]
+1, Thanks @adlermedrado it's work for me!

**Comment by lastjune** [comment]
+1,Thanks @adlermedrado

**Comment by zonyitoo** [comment]
+1

**Comment by DelightRun** [comment]
+1, Thanks

**Comment by honger05** [comment]
+1, thanks a lot

**Comment by immissile** [comment]
fixed! thx

**Comment by argentum47** [comment]
I am using pathogen, I did a git pull, but that didn't help

**Comment by gidway** [comment]
and what with Pathogen?
