### ISSUE TITLE
Red bars

### ISSUE THREAD

**Issue by Cir0X** [spf13/spf13-vim#899]
Function names are often covered by these red bars.
I'm using iTerm2 with the jellybeans theme.
Vim uses also the jellybeans theme.

Any idea which plugin is causing that? How do I turn it off?

![screen shot 2016-03-09 at 17 49 01](https://cloud.githubusercontent.com/assets/4539597/13643152/bd2a0e4a-e61f-11e5-9bd2-afb6480345d7.png)

**Comment by LomigLavnek** [comment]
I think it comes from spelling correction. Try

:set nospell

**Comment by Cir0X** [comment]
Yes this works. Thanks!
