### ISSUE TITLE
Fix CSApprox skipped; terminal only has 8 colors, not 88/256 in gnome-terminal / terminator maybe others

### ISSUE THREAD

**Issue by CoolGoose** [spf13/spf13-vim#90]
CSApprox skipped; terminal only has 8 colors, not 88/256
Try checking :help csapprox-terminal for workarounds

```
set t_Co=256
```

Fixes this. not sure if this should be only in my local vimrc :)

**Comment by skyeagle** [comment]
+1

**Comment by orsenthil** [comment]
I realized this issue today and suggested fix does solve it.

**Comment by jphustman** [comment]
This happens to me too, and that does fix it, thanks CoolGoose.

**Comment by jgrowl** [comment]
+1

**Comment by anthonybrown** [comment]
It kind of fixed it but now I am getting:
Error detected while processing function <SNR>39_CSApprox..<SNR>39_CSApproxImpl:
line   27:
E121: Undefined variable: s:presets_256:
E116: Invalid arguments for function index(s:presets_{&t_Co}, str2nr(color)) < 0
E15: Invalid expression: color > 15 && index(s:presets_{&t_Co}, str2nr(color)) < 0
Error detected while processing /Users/anthonybrown/.spf13-vim-3/.vim/bundle/csapprox/after/plugin/CSApprox.vim:
line   28:
E171: Missing :endif
Press ENTER or type command to continue

I created a .vimrc.local file and added  set t_Co=256
or should I have added that line in some other file?

**Comment by productgabi** [comment]
+1

**Comment by illogic-al** [comment]
Gentlemen, I too have the issue listed in [comment-11484317](https://github.com/spf13/spf13-vim/issues/90#issuecomment-11484317) in windows 7.
Just to provide a bit more info as I've done something atypical.
- I installed msysgit
- then I installed the msys minimal environment to a different directory.
- After that, I installed msys' version of vim (7.3) and copied the necessary executables and library files from msys $bindir to msysgit $bindir. 

At that point, vim launched fine. ( msysgit runs vim using a script btw, which I've modified to run msys' vim.exe )
All bundles installed fine  -- eventually (I needed to repeat the install command multiple times).
Vim also runs fine prior to installing the bundles.
After installing the bundles I get the error above in [comment-11484317](https://github.com/spf13/spf13-vim/issues/90#issuecomment-11484317). 
Removing the csapprox directory gets rid of the error, and as I'm not actually using any gvim color schemes, this is fine for me. 

I think I could probably help with hunting down this bug though, so if you're interested, just give me a holler.
Hope the info above was helpful.

**Comment by illogic-al** [comment]
I'll just paste the actual error again instead of referencing the above:

```
   $ vi ~/Documents/.gitignore
   Error detected while processing function <SNR>41_CSApprox..<SNR>41_CSApproxImpl:
   line   27:
   E121: Undefined variable: s:presets_256^M
   E116: Invalid arguments for function index(s:presets_{&t_Co}, str2nr(color)) < 0
   E15: Invalid expression: color > 15 && index(s:presets_{&t_Co}, str2nr(color)) < 0
   Error detected while processing /c/Users/---/.vim/bundle/csapprox/after/plugin/CSApprox.vim:
   line   28:
   E171: Missing :endif
   Press ENTER or type command to continue
```

**Comment by illogic-al** [comment]
Came back to say that this was my fault. i noticed the '^M' in the output above (which is due to CRLF line endings on windows) and went on a mighty search to find where that was being introduced.

The git repos check out fine. (using this command):

``` sh
find.exe ~/.vim/bundle/ -name "*" -type f -exec /bin/dos2unix.exe {} \;
```

It seems this was my fault because in my ~/.vimrc.local file I put 

``` sh
set t_Co=256^M
```

The ^M portion indicates this line had a dos line ending. 

I think if anyone is still getting this error then either their terminal, or line endings aren't set up quite right. 
With mintty at least, I've put the following in /usr/share/vimrc (on windows) and things works fine. 

``` sh
if (&term == "xterm" || &term == "xterm-256color")
    let &t_Co=256
    let &t_AF="\e[38;5;%dm"
    let &t_AB="\e[48;5;%dm"
endif
```

The above works because I've set my terminal (mintty) to xterm-256color. Modifying ~/.vimrc.local and putting

``` sh
set t_Co=256
```

with unix line endings -- for mintty users -- should also suffice.

HTH

**Comment by isimmons** [comment]
What if TERM = msys?
Running this via Cmder and I see the recent version by default has this in the .vmrc

```
if &term == 'xterm' || &term == 'screen'
            set t_Co=256            " Enable 256 colors to stop the CSApprox warning and make xterm vim shine
endif
```

I tried adding msys to the end of the conditional list but it does not make the warning go away.

Though if I just replace the whole if statement with

```
set t_Co=256
```

It resolves the issue. Guess I should do this right though and add that to a .vimrc.local file instead.

**Comment by Xk0nSid** [comment]
I have a similar problem. I did put set t_Co=256 in .vimrc.local but I still get this error:
`Vim: Warning: Input is not from a terminal
vim.go: $GOPATH is not set
vim.go: you can disable auto install with 'let g:go_disable_autoinstall = 1'
CSApprox skipped; terminal only has 8 colors, not 88/256
Try checking :help csapprox-terminal for workarounds
Press ENTER or type command to continue
\e[32m[✔]\e[0m Now updating/installing plugins using Vundle
sh: 175: Syntax error: Unterminated quoted string`
Can someone please tell me how to fix this?

**Comment by spf13** [comment]
These are two different problems.

I think I figured out what’s happening for the go issue.
I updated it to a new go plugin that expects go installed and configured before installing it. I’ve now made it opt in. 

Please update to the latest and try again.

For the colors / term problem please tell us what the following command returns.

:!echo $TERM

Best,
Steve

-- 
Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by Xk0nSid** [comment]
@spf13 That did it. Thanks Steve. The output of the echo command is `xterm`. Also whenever I edit a file for instance a `python` file and when I write and quit it shows python error checking and stucks there. I'm not able to do anything else. Can you tell me how to disable it. It's really annoying. I'm not even able to ctrl-c out of it.
![vim-errors](https://cloud.githubusercontent.com/assets/2370863/2593884/ca18bda2-ba86-11e3-97dc-3cba30e08dd7.png)

**Comment by spf13** [comment]
The issue here is that the python plugin for vim runs python checks on the file on save. If it's not running properly then it would just hang. It's probably an incompatible python version.

Try running  :PymodeTroubleshooting

**Comment by bronzehedwick** [comment]
@CoolGoose, I think this ticket is no longer relevant, seeing that csapprox has been removed from the base install. Is that correct? If so, please close :)

**Comment by ghost** [comment]
ah thanks @bronzehedwick  : if it reoccurs then that will be up to csapprox folks

**Comment by andrete** [comment]
@Xk0nSid @spf13 I'm sorry, I have seen your discuss, but I also meet the problem:sh: 175: Syntax error: Unterminated quoted string. I still don't know how to fix it, please help me, Thanks!

**Comment by ghost** [comment]
@andrete : csapprox is no longer bundled or supported by spf13-vim.  you should upgrade spf13-vim and delete the content of ~/.vimviews directory.

**Comment by ghost** [comment]
@andrete : after you upgraded spf13-vim and cleared your vim-views and made sure you are not using csapprox? If so, then you should file a totally new ticket as it is unrelated to this issue.

**Comment by andrete** [comment]
@jrobeson Thank you very much. I am a beginner, I open the ~/.vimviews, there is nothing in it. how to upgraded spf13-vim?

**Comment by ghost** [comment]
it's in the main page of this repository in the readme

**Comment by andrete** [comment]
@jrobeson Thank you! I succeed!
