### ISSUE TITLE
cannot fold python code

### ISSUE THREAD

**Issue by wugh** [spf13/spf13-vim#915]
hi, all
I can fold my python on macvim, but cannot fold python code on linux.
Is there anyone get this problem too?

**Comment by MortalCatalyst** [comment]
Is this the same as #924 https://github.com/spf13/spf13-vim/issues/924

**Comment by whogotpwned** [comment]
@wugh The solution proposed by @howiehu worked for me! Maybe you should give it a try 😄 See #924

**Comment by wugh** [comment]
thank you
