### ISSUE TITLE
How to disable the auto behavior when entering {{

### ISSUE THREAD

**Issue by haiyamicode** [spf13/spf13-vim#92]
When entering 2 consecutive braces,  `{{`, Vim with spf-13 changes it to

```
{
}
```

Since i'm writing jinja2 template files, `{{` is essential, so how can I disable that behavior?

**Comment by thelinuxlich** [comment]
+1

**Comment by jaywilliams** [comment]
See #73 for two solutions.

**Comment by taxilian** [comment]
You can also just disable the AutoClose bundle if you never want this to work or on a case-by-case basis by pressing ctrl-v and then the second {.  ctrl-v basically tells vim "don't use any plugins for the next character I type"

**Comment by spf13** [comment]
I've swapped out the AutoClose bundle with a better one that doesn't get in your way as much. I think for 90% of the people it will be viewed as an improvement (and the other 10% can still use the old plugin in their own fork or local).

 See a2b1b34a15d3797b47c86e9d79407bee41833ed7
