### ISSUE TITLE
CtrlP doesn't search in submodule.

### ISSUE THREAD

**Issue by alexche8** [spf13/spf13-vim#923]
I have project with .git root in "project" folder. Submodule located 3 levels deeper - "project/Source/AppEngine/submodule" . CtrlP doesn't search files in "submodule" folder. What do I need to setup to make it possible? Thanks.

**Comment by alexche8** [comment]
Anyway, I added 
let g:ctrlp_cmd = 'CtrlPMixed' to vimrc. So it search in buffers also. This is enough for me for now.

**Comment by tony** [comment]
Related https://github.com/kien/ctrlp.vim/issues/735
