### ISSUE TITLE
E887: Sorry, this command is disabled, the Python's site module could not be loaded.

### ISSUE THREAD

**Issue by with0out** [spf13/spf13-vim#927]
Hello, I'm in windows 7 x64.
Before using spf13-vim, python works fine(`python print 'test'` gives **test**)
but after setting up spf13-vim, it won't work(E887).

I installed python in D:\Python27, and 
python --version gives **Python 2.7.11**
`:ver` gives **+python/dyn**
`:set all` gives **pythondll=python27.dll**
`:echo has('python')` gives **1**
`:echo has('python3')` gives **0**
`:python print 'test'` gives **E887** error

I have following lines in .gvimrc,
`let $PYTHONHOME='D:\Python27'`
`let $PYTHONPATH='D:\Python27\Lib'`

Anything in spf13-vim's config might cause this problem?
Or any suggestion as to find out the cause of it?
Thanks!

**Comment by ghost** [comment]
@with0out : try running vim without spf13-vim (via the -u NONE option to vim),and then set those python variables. If it still doesn't work then, then it isn't spf13-vim config.

**Comment by with0out** [comment]
@jrobeson thanks for the tip, **-u NONE** gave same error,so it seems it's not spf13-vim's fault.
