### ISSUE TITLE
autocomplete can't work

### ISSUE THREAD

**Issue by caiyaodeng** [spf13/spf13-vim#934]
when i coding ,youcompleteme can't work for me.

**Comment by alexche8** [comment]
Can you please provide more information about your problem?

**Comment by caiyaodeng** [comment]
VIM can't give me a hint when I'm coding.

**Comment by caiyaodeng** [comment]
I fix it by myself.  Anyway ,thank you very much.

**Comment by caiyaodeng** [comment]
It  works very well！！！

**Comment by alexche8** [comment]
Then close your issue please.
