### ISSUE TITLE
how to remove the gray block

### ISSUE THREAD

**Issue by Zefrain** [spf13/spf13-vim#936]
I know I can disable the column by :
`let g:indent_guides_enable_on_vim_startup = 0`
but there is still the gray block like the following picture:
https://pbs.twimg.com/media/CjwQrQqUkAEbqzb.jpg
or 
`<leader> ig`
but what I want is to keep the column but disable the block

I sovled the problem by converting tabstops to spaces: `:retab`
But there is no tabstop  any longer

Thank U very much!

**Comment by Whiothes** [comment]
by the way , I can't indent 'xml' file by '==' now, could you help me  ?

**Comment by Whiothes** [comment]
I sovled the problem by converting tabstops to spaces
