### ISSUE TITLE
How to change tabs?

### ISSUE THREAD

**Issue by vkhv** [spf13/spf13-vim#950]

**Comment by vkhv** [comment]
Hi, thx for your work.
I need analog for ctrl + tab from chrome to change active tab. How i can change my active tab in this vim build?
Help me pls

**Comment by AdrienLemaire** [comment]
what tab are you talking about ?
There are tabs within your terminal, within tmux if you use it, tabs within vim, and in parallel you can use panes.

You can learn more about vim tabs doc with something like `:h tabs`. But honestly, I never use it and find panes much more useful (learn with `:h ctrl-w`).

Anyways, I don't think this is related to spf13-vim :)

**Comment by vkhv** [comment]
@Fandekasp I mean these - http://prntscr.com/bsb7jm

**Comment by AdrienLemaire** [comment]
These are vim tabs. Means you created them with `:tabnew` or something.
Again, I don't use vim tabs, but a quick look at the doc `:h tabn` shows that you can use CTRL-<PageDown> to change tabs.
If you want to custom your key mappings, I guess the best place to define them is your `~/.vimrc.local`. Good luck!

**Comment by vkhv** [comment]
@Fandekasp, unfortunately no, if i use tab, which you said i got  these - http://prntscr.com/bsps2e, but i want to learn how use bottom tabs. Thanks for your attention!

**Comment by AdrienLemaire** [comment]
oh you're right, I didn't pay attention. Actually this is just your list of buffers. Seems to be coming from this plugin:

https://github.com/bling/vim-bufferline

**Comment by vkhv** [comment]
@fandekasp thx! commands :bn ( buffer next ) and :bp - satisfied me.

**Comment by vkhv** [comment]
ctrl + i or ctrl + 0, the thing I was looking for

**Comment by AdrienLemaire** [comment]
yeah, that's the default way to navigate through vim buffers. Sorry I hadn't understood your problem at the time ^^
