### ISSUE TITLE
unable to use system clipboard

### ISSUE THREAD

**Issue by hoswey** [spf13/spf13-vim#955]
when install spf13 in ubuntu, I find it the vim cannot copy to and paste from the system clipboard.
I have tried the way in  [how-to-make-vim-paste-from-and-copy-to-systems-clipboard](http://stackoverflow.com/questions/11489428/how-to-make-vim-paste-from-and-copy-to-systems-clipboard) but it doestn't work

Below is my system infomation

``` shell
vim --version | grep clipboard
+clientserver +clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
+xsmp_interact +xterm_clipboard -xterm_save

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04 LTS"
```

**Comment by zx1986** [comment]
In Mac, with spf13-vim, I `dd` in vim, and then my system clipboard got the things I delete in vim.
I don't want that ...

**Comment by zx1986** [comment]
Maybe this will help?
https://github.com/spf13/spf13-vim/issues/191

**Comment by eromoe** [comment]
Ubuntu 12.04 , can't paste too.

**Comment by smurfhunter** [comment]
To whoever maintains this, this should be closed. Their problem was they were using a vim package that does NOT have clipboard support. You can check this by running "vim --version". If you see "+clipboard", then you're good, if you see "-clipboard", please compile vim with clipboard enabled or find a package that has this.
