### ISSUE TITLE
How to disable underlined words?

### ISSUE THREAD

**Issue by alejandroandreu** [spf13/spf13-vim#968]
Hi,

First of all, thanks for all the effort you put into this!

This is not a bug but just a doubt. How do I prevent Vim from underlining certain words? I disabled the `set spell` in the main config but something is still underlining gramatically incorrect words.

Thanks!

**Comment by mkp7** [comment]
+1

**Comment by offa** [comment]
Use `set nospell` (within Vim or in your rc file).

**Comment by mkp7** [comment]
@offa I've `set nospell` in my `.vimrc.local` and I also updated `.vimrc` link file where it had `set spell` to `set nospell`. I've no idea what's keeping it on.

**Comment by offa** [comment]
Does it work from within vim (use `:set nospell`)?

**Comment by elliotmr** [comment]
I just had this problem.  In the second line of .vimrc (in the comment) change spell to nospell, that should get rid of the problem.

**Comment by alejandroandreu** [comment]
`nospell` solved the issue. I stripped down the config and found out that line was the one 😄
