### ISSUE TITLE
Undefined Variables when Loading Python File

### ISSUE THREAD

**Issue by duckworthd** [spf13/spf13-vim#98]
I experience the following error messages when opening any python file with MacVim from the command line,

```
chickadee:kalman duckworthd$ Error detected while processing /Users/duckworthd/Dropbox/vim/.vim/bundle/github-klen-python-mode/ftplugin/python/pymode.vim:
line   43:
E121: Undefined variable: g:pymode_doc
E15: Invalid expression: g:pymode_doc
line   59:
E121: Undefined variable: g:pymode_lint
E15: Invalid expression: g:pymode_lint
line   98:
E121: Undefined variable: g:pymode_rope
E15: Invalid expression: g:pymode_rope
line  118:
E121: Undefined variable: g:pymode_run
E15: Invalid expression: g:pymode_run
line  134:
E121: Undefined variable: g:pymode_breakpoint
E15: Invalid expression: g:pymode_breakpoint
line  146:
E121: Undefined variable: g:pymode_utils_whitespaces
E15: Invalid expression: g:pymode_utils_whitespaces
line  155:
E121: Undefined variable: g:pymode_folding
E15: Invalid expression: g:pymode_folding
Error detected while processing /Users/duckworthd/Dropbox/vim/.vim/bundle/github-klen-python-mode/after/ftplugin/python.vim:
line    2:
E121: Undefined variable: g:pymode
E15: Invalid expression: g:pymode && g:pymode_rope && g:pymode_rope_vim_completion
```

These errors only appear if I execute `mvim script.py` or open `script.py` via the GUI. If I open MacVim, then edit the file, no errors appear.  I see this error on using MacVim build 62 and 64.

**Comment by spf13** [comment]
It looks like this is an issue with the python plugin when you don't have python support built into vim. It should be wrapped with a conditional check for this capability first.  

Best,
Steve

## 

Steve Francia
@spf13 (http://twitter.com/spf13)

**Comment by duckworthd** [comment]
`:version` lists `+python`, which is why it's so puzzling.

**Comment by florentx** [comment]
same issue (MacVim, OS X 10.6)

**Comment by florentx** [comment]
actually, not exactly the same issue.

With "mvim some_file.py" it works.
With "vim some_file.py" it gives errors.

The problem was about the "+python" support missing in the "/usr/bin/vim" included with OSX.
Once I symlink vim -> mvim in "/usr/local/bin", it works.

```
$ mvim --version |head -5
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Sep 18 2011 16:19:12)
MacOS X (unix) version
Included patches: 1-315
Compiled by Bjorn Winckler <bjorn.winckler@gmail.com>
Huge version with MacVim GUI.  Features included (+) or not (-):

$ vim --version |head -4
VIM - Vi IMproved 7.2 (2008 Aug 9, compiled Aug 10 2010 22:09:22)
Included patches: 1-108
Compiled by stripes@il0204d-dhcp43.apple.com
Normal version without GUI.  Features included (+) or not (-):
```

**Comment by duckworthd** [comment]
I tried that but it still threw up the same errors.  What version of MacVim are you using?

**Comment by florentx** [comment]
> What version of MacVim are you using?

MacVim snapshot 62 on OSX 10.6

**Comment by duckworthd** [comment]
So I figured out what was going on.  Somewhere in my `vimrc` I had put in `filetype detect` thinking it was enabling filetype detection.  For one reason or another, this broke python-mode quite a bit.  I removed it and everything works like a charm now.  Using MacVim snapshot 64 for OSX 10.7, by the way.
