### ISSUE TITLE
Indentation style

### ISSUE THREAD

**Issue by radaniba** [spf13/spf13-vim#981]
I would like to change indentation marker (I dont know if that's called like that) to something lighter than this (dotted lines may be ?)

Is that possible ?

![screen shot 2016-10-14 at 11 58 48 am](https://cloud.githubusercontent.com/assets/1666443/19399313/c1e833a2-9205-11e6-97b4-ea4fb00df315.png)

**Comment by dmolinae** [comment]
Hey @radaniba, did you finally know how to do it?
